### ISSUE TITLE
[0.4.8] Duping rock crystal with mekanism cardboard box

### ISSUE THREAD

**Issue by aqpoyo** [NillerMedDild/Enigmatica6#1984] opened 2021-04-14 13:46 UTC
**Modpack version**

0.4.8

**Describe the bug**
So I was moving chest around with the cardboard box of mekanism, it was actually an obsidian chest full of rock crystal from astral sorcery and when I used the box it duplicate and trew on the ground all of the crystals.

**Screenshots**
![image](https://i.imgur.com/O7AdonJ.jpg)

**Comment by BlueAgent** [comment] 2021-04-14 15:11
Duplicate of #1847

**Closed** 2021-04-14 15:15 UTC
Labels: Bug
