### ISSUE TITLE
Iron crafter requires pink crafter when creating a pattern

### ISSUE THREAD

**Issue by rLy07** [NillerMedDild/Enigmatica6#3136] opened 2021-08-30 15:59 UTC
### Modpack Version

0.5.11

### Describe your issue

Looking up the recipe for an Iron crafter from Extra Storage shows that the recipe needs a Crafter from Refined Storage but if used in a pattern grid when clicking the + button it ads a Pink crafter instead.
![20210830-175030](https://user-images.githubusercontent.com/702570/131368163-968e9baf-b2dc-41e7-9420-9959fd0dfd05.png)
![20210830-175040](https://user-images.githubusercontent.com/702570/131368164-08067dc2-bed5-47f0-8174-e22512e91402.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by Darkere** [comment] 2021-08-30 16:06
Disable exact and it will work fine. Duplicate of #2975

**Closed by Darkere** 2021-08-30 16:06 UTC
Labels: Bug
