### ISSUE TITLE
enigmatica 6Lead dupe bug

### ISSUE THREAD

**Issue by CryoChick** [NillerMedDild/Enigmatica6#1963] opened 2021-04-11 11:40 UTC
**Modpack Version**
Enigmatica 6 0.4.8

**Describe the bug**
Using a lead on a waterlogged fence then proceeding to use it on another waterlogged fence always leads to the lead getting duped into 2

**Screenshots**

![image](https://user-images.githubusercontent.com/81686836/114302864-a3435880-9a90-11eb-9456-381160491471.png)
![image](https://user-images.githubusercontent.com/81686836/114302884-c1a95400-9a90-11eb-9f52-deea8b13b81b.png)

**Comment by NillerMedDild** [comment] 2021-04-11 20:23
This seems to be a duplicate of https://github.com/NillerMedDild/Enigmatica6/issues/1622

**Closed by NillerMedDild** 2021-04-11 20:23 UTC
Labels: Bug
