### ISSUE TITLE
Astral Sorcery Crash

### ISSUE THREAD

**Issue by Ninjayatsu** [NillerMedDild/Enigmatica6#672] opened 2020-12-29 01:07 UTC
**Modpack version**
e6 0.3.2 Server

**Issue**
The server crashed after I connected a Crystel lens from Astral Sorcery to a Collecter Crystal(type is unknown, and is also from Astral Sorcery) with the Linking Tool. Then when I try to start the server up again I get the error listed below, which if you read enlists Astral Sorcery being wonky.
**Logs**
Edit: I put your log in a gist
https://gist.github.com/NillerMedDild/7f542ba95b7e5e92825cc3982fa0ec8e

**Comment by NillerMedDild** [comment] 2020-12-29 18:30
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment] 2020-12-29 20:34
This issue appears to have been fixed by an Astral Sorcery update, I cannot reproduce it in singleplayer or on a server.

**Closed by NillerMedDild** 2020-12-29 20:34 UTC
Labels: Bug

**Comment by Ninjayatsu** [comment] 2020-12-29 21:20
ok thanks
