### ISSUE TITLE
Iron bar and Wrapped Ice chains have the same recipe

### ISSUE THREAD

**Issue by C0WB0Y-Ducky** [NillerMedDild/Enigmatica6#3214] opened 2021-09-09 23:17 UTC
### Modpack Version

0.5.11

### Describe your issue

When crafting iron nuggets to iron bar, wrapped ice chains have the same recipe 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment] 2021-09-09 23:50
Duplicate of #3039

**Closed** 2021-09-09 23:50 UTC
Labels: Duplicate
