### ISSUE TITLE
Unusual high enderman spawning in overworld

### ISSUE THREAD

**Issue by ianwijma** [NillerMedDild/Enigmatica6#2237] opened 2021-05-21 13:47 UTC
**Modpack version**
0.4.14

**Describe the bug**
after I upgraded a server from 0.4.8 to 0.4.14, It's been like this for multiple nights. There is also eary music playing.

**Logs**

**Screenshots**
![image](https://user-images.githubusercontent.com/17692119/119147123-a61d6a00-ba8e-11eb-8611-c6f4e09dec7d.png)

**Comment by ianwijma** [comment] 2021-05-21 14:03
I also like to add that sleeping does not progress the night.

**Comment by Darkere** [comment] 2021-05-21 14:09
Did you add any mods to the pack?

**Comment by ianwijma** [comment] 2021-05-21 14:10
Nope, also didn't before i updated. the only thing I removed before was the cost of waystone traveling.

**Comment by RobuxShooters** [comment] 2021-05-21 14:11
It seems like your biome IDs have shifted. I'm going to say that before this, you weren't living in an Imparius Clearing?

**Comment by ianwijma** [comment] 2021-05-21 14:13
Honestly, I have no idea. You want me to check? I still have the old server files :D

**Comment by RobuxShooters** [comment] 2021-05-21 14:21
I think it's better to check but I'm pretty sure Imparius Clearing biomes are supposed to be in the End.

**Comment by ianwijma** [comment] 2021-05-21 14:26
Yeah, should be a Savanna scrub 
![image](https://user-images.githubusercontent.com/17692119/119153150-53df4780-ba94-11eb-9e5b-bc75e7a5c94a.png)

Is there a way to fix the biome IDs? I still have access to the old save.

**Comment by pm065** [comment] 2021-05-21 14:35
> Is there a way to fix the biome IDs? I still have access to the old save.

I think you need to:

1. Downgrade and open the old save.
2. Install the Biome ID Fixer mod. (Search it up on curse.)
3. Enter the world with it installed.
4. Backup the world, just in case.
5. Upgrade, and open the world.
6. Profit! Maybe.
7. If it doesn't work, go down on your knees and sob.

0.4.11 added Biome ID Fixer to the pack by default, so I don't think this should happen again after the successful upgrade.

**Comment by ianwijma** [comment] 2021-05-21 14:43
Awesome, I will check this once I'm back at my PC, thanks for the help!

**Comment by NillerMedDild** [comment] 2021-05-21 15:46
Duplicate of #2090 and a few others.

**Closed by NillerMedDild** 2021-05-21 15:46 UTC
Labels: Duplicate

**Comment by ianwijma** [comment] 2021-05-22 12:17
Thanks @pm065 This fixed it for me!
