### ISSUE TITLE
Quest Chapter Completion

### ISSUE THREAD

**Issue by Zyferus** [NillerMedDild/Enigmatica6#1893] opened 2021-04-02 21:52 UTC
I've completed 2 separate chapters on 0.4.8, and it shows the rewards as claimed, but I never received them.
I completed 'Storage" with the Bins, and never got the rewards, it just instantly put a check-mark on the rewards and never gave them to me.
The 2nd was the Diesel Gen in Immersive, same situation.

**Comment by NillerMedDild** [comment] 2021-04-03 16:45
Thank you for the report, I will investigate the issue.

**Comment by Zyferus** [comment] 2021-04-05 19:58
I do not know if this is important, however I did forget to note, this was on a server, not single player world.

**Comment by NillerMedDild** [comment] 2021-04-05 20:35
The items received from those quests aren't the exact ones shown as rewards, those are just loot tables containing different possible rewards. Could that be what's happening here?

**Comment by Zyferus** [comment] 2021-04-08 20:34
I could not say. When I completed crafting the items, it automatically applied the check marks on the reward indicators, and i did not receive any loot from them. However i tried to duplicate the issue by completing more chapters, and was unable to. Subsequent attempts gave me the ability to claim the loot, so now even I am confuse.

**Comment by NillerMedDild** [comment] 2021-04-08 20:45
Alright, I'll close this since neither of us can reproduce it, feel free to reopen/comment if you experience it again.

**Closed by NillerMedDild** 2021-04-08 20:45 UTC
Labels: Status: Cannot Reproduce
