### ISSUE TITLE
Unable to Craft Apiaries

### ISSUE THREAD

**Issue by keffermc** [NillerMedDild/Enigmatica6#3369] opened 2021-10-03 17:36 UTC
### Modpack Version

0.5.14

### Describe your issue.

I'm unable to craft a tier 1 or tier 2 apiaries.  I have the correct ingredients for both in my inventory: honey blocks, wet honeycomb blocks,  tier 1 beehives, tier 1 apiaries, and a nether star  Clicking the plus button moves the items to the crafting grid but the recipe does not give me the resulting apiary.  I'm not sure if the same is true for tier 3 and tier 4 apiaries as I can't craft the lower tiers yet.

I've been able to craft apiaries in prior versions.  I thought it may have been a config issue on the client or server since updating to 0.5.14 so I reinstalled both with no change

![Apiary_1](https://user-images.githubusercontent.com/6289918/135765047-8717921d-c5e8-4f64-8491-200e8db189eb.png)
![Apiary_2](https://user-images.githubusercontent.com/6289918/135765054-47b10c25-6abf-4450-b6e4-f2f1ed36dc62.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment] 2021-10-03 18:51
Thanks for the report. Are the beehives/apiaries you're using to craft with empty or filled?

**Comment by keffermc** [comment] 2021-10-03 19:25
All the hives and apiaries are empty.  I thought maybe it was an NBT issue so I placed both the nests and apiaries, let bees enter and removed them.  That didn't help either.

**Comment by NillerMedDild** [comment] 2021-10-03 19:53
Hmm, not sure what's going on, I can't reproduce the issue :s

**Comment by keffermc** [comment] 2021-10-03 20:54
I figured out what I was doing wrong.  From looking at the recipe I was trying to use Tier 0 nests I found in the world since the recipe shows both nests and hives as valid.  The problem is the recipe calls for Tier 4 nests, which I'm not sure is possible to get.  You can craft hives to Tier 4 but I didn't see a recipe for Tier 4 nests.  Once I crafted Tier 4 hives, I was able to craft the apiary.  

Question regarding this, is it possible to get a Tier 4 nest or are they only Tier 0?

![Apiary_3](https://user-images.githubusercontent.com/6289918/135771092-54866196-a429-4077-84ca-b854ce1c455d.png)

**Comment by Ridanisaurus** [comment] 2021-10-03 21:17
Nests are always Tier 0. Hives got for 1-4, and then Apiaries for 1-4.

**Comment by TemperedFool** [comment] 2021-10-03 21:19
> Question regarding this, is it possible to get a Tier 4 nest or are they only Tier 0?

You can! There are in-world upgrades that will upgrade a nest all the way up to function as a T4 Hive.

@NillerMedDild - this is some of the downside risk I was concerned about moving to the newer tiered ingredients; I still think it's worth it, but it will probably come up periodically.

**Closed** 2021-10-04 04:28 UTC
Labels: Invalid
