### ISSUE TITLE
Squid not spawning in E6 v0.3.2

### ISSUE THREAD

**Issue by Vespor** [NillerMedDild/Enigmatica6#797] opened 2021-01-06 21:17 UTC
**Modpack version**
v0.3.2

**Issue**
Squids don't seem to spawn in any of the appropriate biomes (rivers, oceans). All exposed to the sun/moon vertically. Several minecraft days spent exploring around to what should be elligible spawn locations as well as standing in one location waiting for spawns. Only seem to see varieties of fish spawn.

Not sure if I've done anything wrong or if I'm not fully understanding squid spawning mechanics. World was created with E6 v0.3.2, no version updates after world generation.

**Logs**
N/A

**Comment by NillerMedDild** [comment] 2021-01-06 21:19
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment] 2021-01-06 22:17
Ah I think I know the cause of this, I believe Aquaculture accidentally marked it's fish as the same group as squid, so they took all the spawning "places" :P 

I believe this is fixed in 0.3.3+, and I cannot reproduce it.

**Closed by NillerMedDild** 2021-01-06 22:17 UTC
Labels: Bug
