### ISSUE TITLE
Obtaining PITG Green Dye

### ISSUE THREAD

**Issue by ReverseZoom** [NillerMedDild/Enigmatica6#3872] opened 2021-12-08 09:17 UTC
### Modpack Version

0.5.20

### Describe your issue.

By using the Dye Mixer from Industrial Foregoing you can obtain "Green Dye" from "Pain In The Glass". You cannot obtain normal Green dye using the Dye mixer.
I checked the changelog from the 0.5.21 and didn't find a fix for it so I think it is a new bug.
![grafik](https://user-images.githubusercontent.com/37956499/145181581-86ee6b1e-7a35-4412-ad19-fd51f27d4a18.png)

### Have you modified the modpack?

Yes

### User Modifications

Just a few small changes to the Apotheosis spawners and added more Trinket slots.

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment] 2021-12-08 10:30
Duplicate of #2746

**Closed by NillerMedDild** 2021-12-08 10:30 UTC
Labels: Bug
