### ISSUE TITLE
[0.4.8] Unknown Crash

### ISSUE THREAD

**Issue by meerpaluten** [NillerMedDild/Enigmatica6#2012] opened 2021-04-19 18:36 UTC
**Modpack version**
0.4.8

**Describe the bug**
The Server Crash when i was explore the world

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
https://pastebin.com/bFnUqjjB

**Screenshots**

**Comment by NillerMedDild** [comment] 2021-04-19 18:41
Duplicate of #1742 
Replace the Simple Farming jar on the server with this one: https://drive.google.com/file/d/1ygAHyWvJhfrbkn2IWJo0rLY0xpqUFmzk/view?usp=sharing :)

**Closed by NillerMedDild** 2021-04-19 18:41 UTC
Labels: Bug
