### ISSUE TITLE
[0.5.0] BYG Nether biomes were removed, Glowstone bees only spawn in BYG Nether biomes

### ISSUE THREAD

**Issue by mouseas** [NillerMedDild/Enigmatica6#2501] opened 2021-06-22 17:31 UTC
**Modpack version**
0.5.0 via CurseForge

**Describe the bug**
0.5.0 removed/disabled the various Nether BYG biomes, but Resourceful Bees hasn't been fully updated to account for that. The Glowstone bee only spawns in Crimson Gardens, Wailing Garth, and Glowstone Gardens, all of which are from BYG and thus were removed. Glowstone bee is a required precursor for Blaze, Ghast, Quartz, Netherite, and Wither bees.

**Screenshots**
![glowstone_bee_biomes](https://user-images.githubusercontent.com/1171633/122972004-e3ef0600-d34c-11eb-81a8-ac61f3b4c527.png)

**Comment by NillerMedDild** [comment] 2021-06-22 17:53
Thanks for the report. This has been fixed in https://github.com/NillerMedDild/Enigmatica6/pull/2491 :)

**Comment by NillerMedDild** [comment] 2021-06-22 19:43
Duplicate of #2451 btw

**Closed** 2021-06-22 19:42 UTC
Labels: Duplicate
