### ISSUE TITLE
machine access

### ISSUE THREAD

**Issue by darell35** [NillerMedDild/Enigmatica6#1286] opened 2021-02-11 09:32 UTC
**Modpack version**
0.3.13

**Describe the bug**
I am having trouble accessing the vanilla furnace and the metallurgic infuser and the enrichment chamber

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5964138/latest.log)
[latest.zip](https://github.com/NillerMedDild/Enigmatica6/files/5964146/latest.zip)

**Screenshots**

**Comment by Darkere** [comment] 2021-02-11 09:33
try restarting your client

**Comment by Darkere** [comment] 2021-02-12 14:53
Assuming duplicate of #667

**Closed by Darkere** 2021-02-12 14:53 UTC
Labels: Bug, Status: Awaiting Information
