### ISSUE TITLE
The Endergetic Expansion

### ISSUE THREAD

**Issue by Cireric120** [NillerMedDild/Enigmatica6#2220] opened 2021-05-19 15:45 UTC
https://www.curseforge.com/minecraft/mc-mods/endergetic

**Mod description**
The focus of The Endergetic Expansion's is to improve every aspect of the end, despite being in early beta, it notably already adds an entire biome with unique mechanics and visuals, as well as visual improvements to the existing end well and end gateways used to teleport in vanilla. The poise forest can be located semi-rarely in the outer islands of the end (where the chorus biome can also spawn).
More biomes will be coming in the future, but for now, the mod notably adds a new and totally unique biome called the Poise Forest

**Why would you like the mod added?**
There is a bug with Decorative Blocks that will crash any client that renders the Ender Brazier. Adding this mod resolves that issue.

**Comment by pm065** [comment] 2021-05-19 16:09
I think this would have been added before if it was wanted, and I'm pretty sure they don't want any more end biomes

**Comment by Cireric120** [comment] 2021-05-19 16:22
That's fair! My concern is less of the mod itself and more of preventing servers from getting bricked due to the ender brazier. From what I've seen at least, the only options available at the moment are either removing Decorative Blocks or adding this mod.

**Comment by pm065** [comment] 2021-05-19 16:57
> That's fair! My concern is less of the mod itself and more of preventing servers from getting bricked due to the ender brazier. From what I've seen at least, the only options available at the moment are either removing Decorative Blocks or adding this mod.

Wait, how would anyone get access to it except in creative? That sounds like something you should report, though I don't think the Deco Blocks Compat author has a github for any of their mods.

**Comment by CletusMAngo** [comment] 2021-05-19 17:36
Duplicate of #808

**Closed** 2021-05-19 18:12 UTC
Labels: Status: Won't Fix, Suggestion
