### ISSUE TITLE
Opening Thermopneumatic Processing Plant GUI crashes game

### ISSUE THREAD

**Issue by Crazymonkay** [NillerMedDild/Enigmatica6#703] opened 2021-01-01 01:01 UTC
**Modpack version**
0.3.2

**Issue**
Opening up the Thermopneumatic Processing Plant GUI has a good chance (somewhere around 25% chance as a rough guess) of crashing the game.

**Logs**
https://pastebin.com/uMmZty4t

**Comment by NillerMedDild** [comment] 2021-01-01 19:27
Thanks for the report. It looks like it may be caused by showing certain errors in the GUI, do you know which they might be?

**Comment by Crazymonkay** [comment] 2021-01-01 20:33
> Thanks for the report. It looks like it may be caused by showing certain errors in the GUI, do you know which they might be?

The crashes are happening on newly placed processing plants with nothing connected to them and no fluid in them, so I imagine there would be a lot of potential errors.
If it helps, here are the problems listed when it _doesn't_ crash: https://i.gyazo.com/6e843c62cb9f8f3bc14e9686f6f88778.png

**Comment by NillerMedDild** [comment] 2021-01-01 20:41
I can't reproduce this. Are you on a server? Where did you place it?

**Comment by Crazymonkay** [comment] 2021-01-02 18:01
Yes, I am on a server, but it doesn't have any info about the crash.

It seems like I have the greatest chance of crashing after placing multiple processing plants side by side and opening the GUI. I have made 4 as part of the quests. Placing them 2 of them 1 block apart and then placing a 3rd between them and immediately opening its GUI may yield more crashes.

**Comment by NillerMedDild** [comment] 2021-01-02 18:59
Still nothing, maybe it has been fixed. Would you mind testing if this still happens in v0.3.3, when I release that? :)

**Comment by Crazymonkay** [comment] 2021-01-02 19:07
Sure. I've been doing a lot of testing to see if there is any sort of pattern and that was the only thing I could come up with.

**Comment by desht** [comment] 2021-01-07 23:13
This is fixed in PNC 2.9.0

**Closed** 2021-01-08 07:18 UTC
Labels: Bug, Status: Awaiting Information, Status: Cannot Reproduce
