### ISSUE TITLE
[Suggestion] The Outer End

### ISSUE THREAD

**Issue by stylzm** [NillerMedDild/Enigmatica6#2025] opened 2021-04-21 02:22 UTC
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/the-outer-end

**Mod description**
The Outer End adds new mobs, biomes, and structures to the end dimension.

**Why would you like the mod added?**
The mod adds two new dungeon structures to the end, along with two new biomes, making exploration more interesting. The new dungeons and mobs add some challenge to end exploration, and the mod also adds a feature to set the Ender Dragons health to a custom value.

**Screenshots if applicable.**
![image](https://user-images.githubusercontent.com/46853295/115487457-969bce80-a20d-11eb-8c91-f8d36ae097fb.png)
![image](https://user-images.githubusercontent.com/46853295/115487474-9f8ca000-a20d-11eb-9caa-f1563ca12dbc.png)

**Comment by NillerMedDild** [comment] 2021-04-21 04:32
Duplicate of #620

**Closed by NillerMedDild** 2021-04-21 04:32 UTC
Labels: Duplicate
