### ISSUE TITLE
Opening inventory while cursor is on painting makes background UI invisible.

### ISSUE THREAD

**Issue by miguetdev** [NillerMedDild/Enigmatica6#1570] opened 2021-03-06 17:56 UTC
**Modpack version** 0.4.2

**Describe the bug**
As a player, have your cursor/crosshair on a painting and press the keybind to open inventory ("E" by default). Inventory GUI will appear with no background images. JEI is not visible as well. Inventory is fully interactive in this state even while inventory slots are not visible. Inventory tool-tips do not appear.

**Logs**
View screenshot (no logs captured)

**Screenshots**
![2021-03-06_12 49 58](https://user-images.githubusercontent.com/1209079/110216034-d9caf980-7e7a-11eb-8dff-42687a89441d.png)

**Comment by NillerMedDild** [comment] 2021-03-06 18:21
Thanks for the report, it is however a duplicate.
Duplicate of #876

**Closed by NillerMedDild** 2021-03-06 18:21 UTC
Labels: Bug
