### ISSUE TITLE
Create Crafts & Additions

### ISSUE THREAD

**Issue by FilthySerf** [NillerMedDild/Enigmatica6#2364] opened 2021-06-06 05:51 UTC
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/createaddition

**Mod description**
Create Crafts & Additions extends Create and acts as a bridge between electricity and kinetic energy from Create by adding an Electric Motor which generates kinetic energy from Forge energy and an Alternator which does the opposite at 75% efficiency. To crafts these items you need to make a Rolling Mill which is a kinetic machine that is used to make rods and wires.

**Why would you like the mod added?**
Adds additional ways to generate power, expanding upon the usage of the Create mod.

**Comment by NillerMedDild** [comment] 2021-06-06 07:03
Duplicate of #1190

**Closed by NillerMedDild** 2021-06-06 07:03 UTC
Labels: Suggestion
