### ISSUE TITLE
Sophisticated Backpacks/Sorting Dupe bug

### ISSUE THREAD

**Issue by TemperedFool** [NillerMedDild/Enigmatica6#856] opened 2021-01-11 22:08 UTC
Pack version 0.3.2

I think this dupe is a weird cross-mod interaction - it's also mild.

I have a Diamond backpack with 4 upgrades: crafting, eating, adv. compressing & adv magnet. I've noticed that if I use the middle mouse button sort (I think Inv. Tweaks adds this?) it pulls all upgrades but the crafting upgrade from its slot into the main inventory, and duplicates the crafting upgrade. 

Seems repeatable on my setup - this is connecting to a server on the same LAN. Is there a log I can pull to help diagnose, or can someone else otherwise confirm they see this behavior? I'm going to see if I can replicate it on 0.3.5 tonight once I get a chance to install it.

**Comment by NillerMedDild** [comment] 2021-01-11 22:10
Fixed in 0.3.3, duplicate of #645 :)

**Closed by NillerMedDild** 2021-01-11 22:10 UTC

**Comment by TemperedFool** [comment] 2021-01-11 22:14
Yuck, search fail by me, for no good reason! Sorry about that!

**Comment by NillerMedDild** [comment] 2021-01-11 22:15
No worries :)
