### ISSUE TITLE
Emendatus Enigmatica lead ingots don't work in Eidolon magic workbench recipes 

### ISSUE THREAD

**Issue by Jams52** [NillerMedDild/Enigmatica6#795] opened 2021-01-06 20:05 UTC
**Modpack version**
E6 0.3.3

**Issue**
It seems like the magic workbench doesn't use the oredict for lead, it's only trying to get it's own lead

**Logs**
Here's 2 screenshots of what happens. I did it on the official server so I don't know if it could be a config issue on there.

https://feen.us/8eui8i.jpg
https://feen.us/36it89.jpg

**Comment by NillerMedDild** [comment] 2021-01-06 20:06
Duplicate of #794

**Closed by NillerMedDild** 2021-01-06 20:06 UTC
