### ISSUE TITLE
Mod Suggestion - Mana & Artiface

### ISSUE THREAD

**Issue by tristanmcm** [NillerMedDild/Enigmatica6#912] opened 2021-01-16 11:29 UTC
The official spiritual successor to Ars Magical 2. This would be a great addition to the pack! :D

https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice

**Comment by Merlo17** [comment] 2021-01-16 11:32
Duplicate of https://github.com/NillerMedDild/Enigmatica6/issues/275

I've also had a quick look and it seems like it hasn't changed much, so right now I don't really see a reason to include it myself. I still think the textures look awful too.

**Closed** 2021-01-16 11:32 UTC
Labels: Duplicate

**Comment by chrissikiller** [comment] 2021-02-20 21:59
why this mod is greate at least in my opinion? also the graphics are better than ars novae.

**Comment by Merlo17** [comment] 2021-02-20 22:01
I would argue that's subjective and I don't feel the same way at all. What rid says in the original issue says it best imo
