### ISSUE TITLE
[0.4.10] Diet mod Breaks when using lead on horse instead of fence pole

### ISSUE THREAD

**Issue by joniboychi** [NillerMedDild/Enigmatica6#2088] opened 2021-05-02 22:30 UTC
**0.4.10**

**Describe the bug**
When using the lead to tether a horse to a fence pole the diet mod breaks and the character is unable to destroy any blocks, however it only seems to do this if you tether to pole and try to tether the horse, the other way around, tether lead to horse and then to a fence pole is working fine.

**Logs**
https://dl.dropboxusercontent.com/s/107osnhet7lwx2d/latest.log

**Screenshots**
I can provide video if needed .

**Comment by NillerMedDild** [comment] 2021-05-03 04:31
Duplicate of #1622

**Closed by NillerMedDild** 2021-05-03 04:31 UTC
Labels: Bug
