### ISSUE TITLE
Refined Storage not reading external storage of drawers on world load/server restart

### ISSUE THREAD

**Issue by Shindur** [NillerMedDild/Enigmatica6#976] opened 2021-01-20 22:42 UTC
**Modpack version**
0.3.6

**Describe the bug**
>Have external storage from RS connected to drawer controller with items in connected drawers
>Restart the server/exit world and rejoin
>Go to RS grid/crafting grid, nothing from the connected drawers are in the system
>Causes anything to be put in the system to default to disks rather than the drawers that have the items

Only fix I've found is to break the controller for RS or the external storage and place back down

Saw this issue mentioned here: https://github.com/NillerMedDild/Enigmatica6/issues/225 but it wasn't addressed in the comments from what I saw. My drawers have items in them on world load, just the external storage not reading the drawers properly it seems.

**Comment by Darkere** [comment] 2021-01-20 23:43
Yep pretty much. Getting a new comment about the issue every 2 weeks or so.

Still no clue what causes it. But considering the state of Storage drawers, I'm also really not inclined to dig through their code.
Especially since it is not easy to reproduce.

**Comment by Shindur** [comment] 2021-01-21 03:07
The reproduction issue is the odd part :/ It was working fine I think on 0.3.2.. cause after that I updated my server to 0.3.5 then 0.3.6 and in 0.3.5 is when I noticed the issue.

**Comment by Sanguinely** [comment] 2021-01-21 18:57
I've been having this issue since the size on what is being stored has gotten higher. drawer controller linked to 18 compacting drawers with 100s of 1000s of items. Really hoping something could be done about it because i end up having to stop automining if i know a server restart is coming. else my disks fill with ingots that i have to use a disk manipulator to move. and the disk manipulator is laggy AF, causes TPS to drop by itself

**Comment by Merlo17** [comment] 2021-01-21 18:59
I don't think the size has anything to do with it. I've had systems with many more items be completely fine and systems with less be broken. I'd guess it's on their part but I wouldn't really know where to go look

**Comment by Darkere** [comment] 2021-01-21 19:01
Disk manipulator should not cause any lag issues anymore. Please report if it does on the latest RS version.

**Comment by NillerMedDild** [comment] 2021-01-21 19:49
duplicate of #225 (I do not blame you for not finding it :P)

**Closed by NillerMedDild** 2021-01-21 19:49 UTC
Labels: Bug
