### ISSUE TITLE
RFToolsDimensions Dimlet Workbench Recipes

### ISSUE THREAD

**Issue by The-Tarkol** [NillerMedDild/Enigmatica6#3178] opened 2021-09-05 03:31 UTC
### Modpack Version

0.5.11

### Describe your issue

Ever since the update to 0.5.11 (we started the server on 0.5.6), the Dimlet Workbench hasn't displayed the needed materials to create a dimlet. Tested with multiple machines, even tried a setup from scratch with brand new lost knowledge. Didn't see anything in the configs when I skimmed over, and the folks in Discord recommended popping a report in here.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment] 2021-09-05 17:07
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment] 2021-09-05 18:09
Does it look like this for you?
![billede](https://user-images.githubusercontent.com/21295394/132137078-a444dfa5-6abc-4ca2-afae-1376723c4fa6.png)

**Comment by The-Tarkol** [comment] 2021-09-05 21:42
![RFToolsDim](https://user-images.githubusercontent.com/24594751/132142168-ebe6c3fe-ded7-4ed4-aec6-c709ccd40590.png)

**Comment by The-Tarkol** [comment] 2021-09-05 21:43
Sorry, should've included the screenshot. That's what I've got when I hover over them.

**Comment by NillerMedDild** [comment] 2021-09-06 04:59
Thanks, all of them are similar to that I take it, with a blank  space above the mod name?

**Comment by The-Tarkol** [comment] 2021-09-06 06:00
Yes exactly. All the dimlets are just like that.

Just checked in 0.5.6, and the recipes all show like they're supposed to. Using that as a work-around currently to get the actual recipe info, since that doesn't appear to have changed.

**Comment by NillerMedDild** [comment] 2021-09-06 17:35
I recommend that you try doing a reinstall of the config and kubejs folders from both server and client, something wonky seems to be going on for sure :P

**Comment by The-Tarkol** [comment] 2021-09-07 08:29
Did a fresh install of both server and client, still seeing the issue

**Comment by NillerMedDild** [comment] 2021-09-07 08:39
Looks like it might be caused by outdated mods: https://github.com/McJtyMods/RFToolsDimensions/issues/380#issuecomment-908049263
Should be fixed in 0.5.12

**Closed** 2021-09-24 19:32 UTC
Labels: Status: Fixed In Next Release, Mod Issue
