### ISSUE TITLE
Some Servers Do Not Show Up Correctly On Client

### ISSUE THREAD

**Issue by r-mc2** [NillerMedDild/Enigmatica6#824] opened 2021-01-09 02:36 UTC
**Modpack version**
v0.3.5

**Issue**
Ever since updating past v0.3.2 the client's Servers list has been unable to query the server for its information. Every time I refresh the Servers page I get this on the remote server's console:

```[21:23:50] [Netty Server IO #1/ERROR] [minecraft/NettyPacketEncoder]: io.netty.handler.codec.EncoderException: String too big (was 33195 bytes encoded, max 32767)```

Not sure which mod may be doing it or if it's just the pack has gotten large enough to blow past this limit.

It currently does not effect one's ability to connect to the server, but hard to tell if it is ever *really* down.

**Comment by Firestorm7893** [comment] 2021-01-09 09:59
I'm having the same issues too

**Comment by NillerMedDild** [comment] 2021-01-09 20:04
Thanks for the report, may I have a screenshot please?

**Comment by r-mc2** [comment] 2021-01-09 23:27
Sure thing:
![MC-Enigmatica6-Server-Down-But-Not-Really](https://user-images.githubusercontent.com/36780233/104110675-ffd38380-52a7-11eb-92e8-05e0ac21b3c1.png)

Since I run the server I can check server-side to make sure it's up. So I can still click through to connect to the server anyway even though it shows it is "unavailable".

Log-wise and console wise, that's the only message that appears when I try to refresh the Servers list here.

**Comment by NillerMedDild** [comment] 2021-01-09 23:30
Hmm interesting. Our dev server and play server don't have this issue, I wonder what's up. Did you add any mods, on client or server?

**Comment by Firestorm7893** [comment] 2021-01-10 00:01
> Sure thing:
> ![MC-Enigmatica6-Server-Down-But-Not-Really](https://user-images.githubusercontent.com/36780233/104110675-ffd38380-52a7-11eb-92e8-05e0ac21b3c1.png)
> 
> Since I run the server I can check server-side to make sure it's up. So I can still click through to connect to the server anyway even though it shows it is "unavailable".
> 
> Log-wise and console wise, that's the only message that appears when I try to refresh the Servers list here.

The behavior is exactly the same. With no modifications to the mod pack whatsoever.


I don't know if it matters. But this error happened even while I was just publishing the world on the lan. My friends could connect if I gave them my ip, but it would result as unreachable in the multiplayer menu. 

After a while I moved the world from my single player client to a dedicated server. But it does the same thing. Really weird 🤔

**Comment by r-mc2** [comment] 2021-01-10 04:10
Yes, we did add 3 mods to the pack overall. Could be part of the issue? Although if Firestorm is having the same issue without the additional mods, I am not sure. Perhaps a situation of taking the same world from v0.3.2 to v0.3.4, then up to v0.3.5? Upgrading along the way.

i.e. maybe some lingering file from a previous version is keeping extra data in the query return that's overloading the limit?

#### Additional Mods
* Cyclic-1.16.4-1.0.2
* JustEnoughResources-1.16.4-0.12.0.103
* SimplyJetpacks2-1.16.4-2.6.5.2

**Comment by NillerMedDild** [comment] 2021-01-10 13:06
> Perhaps a situation of taking the same world from v0.3.2 to v0.3.4, then up to v0.3.5? Upgrading along the way.

Then the official server should have the same issue, it doesn't skip versions :/

I don't know ><

**Comment by r-mc2** [comment] 2021-01-10 19:39
Hmm, well one last thing to mention, whether it factors or not, this was originally a v0.3.2 single-player world I converted to a server to help alleviate load on my own machine. The upgrades to 0.3.4 and 0.3.5 were done after it was already a server. To mention the v0.3.2 server (converted from a SSP world) worked fine in the Servers list.

A secondary thing, do we know what exactly the server is aggregating from to produce that packet of data that is now too large? Maybe could help us figure out where this extra bloat has come from.

**Comment by NillerMedDild** [comment] 2021-01-10 19:46
I assume it's the datapack in the `kubejs/data` folder :)

**Comment by Darkere** [comment] 2021-01-10 19:53
datapacks only get synced on join. 

That said I don't know what might be the cause here.

**Comment by r-mc2** [comment] 2021-01-10 19:59
Hmm, well I know when upgrading the server I always started with a fresh Kubejs folder. Started fresh with all the folders in the server zip for that matter. Backported some config changes, but those were mostly around where FTBBackups puts the backups + restoring the config files for the 3 added mods.

**Comment by r-mc2** [comment] 2021-01-10 20:10
Random thought backed up by no real data, but could it have something to do with the `packmenu/` folder? The assets and information that looks directly related to how the server shows up in the Servers list?

**Comment by NillerMedDild** [comment] 2021-01-10 20:12
> Random thought backed up by no real data, but could it have something to do with the packmenu/ folder? The assets and information that looks directly related to how the server shows up in the Servers list?

Nope unfortunately not, the packmenu assets are client side only and haven't changed in quite some time.

**Comment by r-mc2** [comment] 2021-01-10 20:18
Hrm, darn. It was a shot in the dark 😄 
I took at look again at the byte size that the console error mentioned, then looked at the server folder hoping to find anything that seemed to be about 32Kb in size (`32.4169921875 Kb`). But I'm not really familiar enough with the pack's whole layout or what Minecraft decides to aggregate out of these files/folders to get that 32k data set.

**Comment by NillerMedDild** [comment] 2021-01-10 20:50
May I have a screenshot of your server folder? :)

**Comment by Firestorm7893** [comment] 2021-01-11 19:19
Since i have the same problem i could provide it if you want

**Comment by NillerMedDild** [comment] 2021-01-11 19:25
Yes please.

**Comment by Firestorm7893** [comment] 2021-01-11 19:25
Ok, give me one sec

**Comment by Firestorm7893** [comment] 2021-01-11 19:26
![Cattura](https://user-images.githubusercontent.com/12925730/104228543-50371680-544b-11eb-9432-6d6a6df3a03d.PNG)

**Comment by Firestorm7893** [comment] 2021-01-11 19:27
just noticed the folder called DELETE ME. Maybe i should...

**Comment by NillerMedDild** [comment] 2021-01-11 20:22
Interesting O_o did you try that? Which Forge version are you using?

**Comment by RixMixed** [comment] 2021-01-11 20:53
I've only had this issue trying to using my own server-icon.png

Have you modified anything that would display on the serverlist (MOTD, Player Slots, Icon?)

Maybe try a fresh unmodified E6 server properties file.

**Comment by r-mc2** [comment] 2021-01-11 21:23
Sorry for the delay, got caught up messing with automation of Powah's Orb... 😫 

```
    Directory: <App_Dir>\Enigmatica 6 - E6


Mode                LastWriteTime         Length Name                                       
----                -------------         ------ ----                                       
d-----       12/29/2020  10:25 PM                .mixin.out                                 
d-----         1/3/2021   8:29 PM                backups                                    
d-----       12/29/2020  10:26 PM                building_gadgets_patterns                  
d-----        1/10/2021   2:34 PM                config                                     
d-----         1/7/2021   3:35 PM                config[0.3.2].bak                          
d-----         1/8/2021   7:50 PM                config[0.3.4].bak                          
d-----         1/7/2021  11:58 PM                crash-reports                              
d-----         1/8/2021   8:18 PM                defaultconfigs                             
d-----         1/8/2021   8:25 PM                downloads                                  
d-----       12/29/2020  10:26 PM                emojiful                                   
d-----       12/31/2020   6:35 PM                ESM                                        
d-----         1/8/2021   8:18 PM                kubejs                                     
d-----       12/29/2020  10:26 PM                local                                      
d-----        1/11/2021   4:20 PM                logs                                       
d-----         1/8/2021   8:25 PM                mods                                       
d-----       12/29/2020  10:27 PM                packmenu                                   
d-----       12/29/2020  10:27 PM                patchouli_books                            
d-----         1/8/2021   8:25 PM                resourcepacks                              
d-----         1/8/2021   8:25 PM                saves                                      
d-----         1/9/2021   4:32 PM                schematics                                 
d-----       12/24/2020  12:47 AM                themes                                     
-a----        1/10/2021   2:34 PM             44 BotaniaVars.dat                            
-a----        1/11/2021   4:21 PM              0 dir_output.txt                             
-a----        1/10/2021   2:35 PM           6516 knownkeys.txt                              
-a----         1/8/2021   8:18 PM          24334 manifest.json                              
-a----        1/11/2021   4:20 PM         867195 minecraftinstance.json                     
-a----        1/10/2021   2:35 PM             73 mode.json                                  
-a----         1/8/2021   8:18 PM          29695 modlist.html                               
-a----         1/9/2021   9:59 PM          14417 options.txt                                
-a----        1/11/2021  12:12 AM          16812 patchouli_data.json                        
-a----        1/10/2021   2:34 PM            772 reauth.toml                                
-a----         1/4/2021   3:55 PM          12640 servers.dat                                
-a----         1/4/2021   3:55 PM             71 servers.dat_old                            
-a----         1/8/2021   8:51 PM            112 usercache.json                             
-a----       12/22/2020  11:24 PM             61 usernamecache.json                         
```

**Comment by NillerMedDild** [comment] 2021-01-11 21:25
That looks like client files?

**Comment by r-mc2** [comment] 2021-01-11 21:26
> Have you modified anything that would display on the serverlist (MOTD, Player Slots, Icon?)

You may be on to something. I did update my MOTD with the pack version at the front of the default one the devs here added:
`[0.3.5] Enigmatica 6 Server`

---

> That looks like client files?

Some, yes. I did the "quick and dirty" zip up the client dir and copy to the server dir, then replace with the specific server files from the ZIP you all provide.

**Comment by NillerMedDild** [comment] 2021-01-11 21:28
Does removing `[0.3.5]` help?

**Comment by NillerMedDild** [comment] 2021-01-11 21:28
> Some, yes. I did the "quick and dirty" zip up the client dir and copy to the server dir, then replace with the specific server files from the ZIP you all provide.

Please use the server files :P

**Comment by Firestorm7893** [comment] 2021-01-11 21:29
> Interesting O_o did you try that? Which Forge version are you using?

I did, but nothing changed unfortunately. Those files were leftovers from the forge installer that came with the server I think

**Comment by Firestorm7893** [comment] 2021-01-11 21:30
> I've only had this issue trying to using my own server-icon.png
> 
> Have you modified anything that would display on the serverlist (MOTD, Player Slots, Icon?)
> 
> Maybe try a fresh unmodified E6 server properties file.

I changed nothing. I only removed spawn protection because it was messing with our house 😅

**Comment by Firestorm7893** [comment] 2021-01-11 21:30
If you are curious I could zip and give you the entire server folder! It's not a game breaking bug, It's just really odd

**Comment by NillerMedDild** [comment] 2021-01-11 21:31
That'd be nice actually :)

**Comment by Firestorm7893** [comment] 2021-01-11 21:31
Will do right now

**Comment by r-mc2** [comment] 2021-01-11 21:39
> Please use the server files :P

You wouldn't happen to know which ones I should remove? 😄

**Comment by NillerMedDild** [comment] 2021-01-11 21:41
I do not, the script I made that generates the serverfiles knows very well though :P

**Comment by Firestorm7893** [comment] 2021-01-11 21:45
https://silvavault.duckdns.org/nextcloud/s/KTgnitCfikMKp6j
here you go! In theory this is a server with just a world from a single player game. It should be as untouched as possibile

**Comment by Firestorm7893** [comment] 2021-01-11 21:52
Oh yeah I forgot. In the mods folder I installed vivecraft forge extensions because I wanted to try playing in VR. Unfortunately the mod pack crashes instantly. 
Anyway I had the problem even before adding that mod

(love how friendly you are guys 😁)

**Comment by NillerMedDild** [comment] 2021-01-11 22:12
Please try removing the packmenu folder from the server.

**Comment by Firestorm7893** [comment] 2021-01-12 01:03
Unfortunately it didn't fix it

**Comment by Firestorm7893** [comment] 2021-01-12 01:20
![Cattura](https://user-images.githubusercontent.com/12925730/104256901-6f9a6780-547c-11eb-995e-e28a20d0d053.PNG)
just noticed this from the client log. Every time i try to ping this error pops up. looks like the problem is client side? maybe ?

**Comment by r-mc2** [comment] 2021-01-12 03:36
So, apparently in my rush to respond I whole-derped and actually gave you the `dir` output of the *client* after all 😩 

Comparing the current *actual* server folder:
```
 Directory of C:\Servers\Minecraft Modded

01/11/2021  10:29 PM    <DIR>          .
01/11/2021  10:29 PM    <DIR>          ..
01/04/2021  03:36 PM    <DIR>          .mixin.out
01/04/2021  03:35 PM            39,605 1.16.4.json
01/11/2021  10:18 PM    <DIR>          2020
01/08/2021  02:55 AM    <DIR>          backups
01/08/2021  09:35 PM                 2 banned-ips.json
01/08/2021  09:35 PM                 2 banned-players.json
01/08/2021  09:33 PM    <DIR>          config
01/08/2021  09:30 PM    <DIR>          crash-reports
01/08/2021  09:02 PM    <DIR>          defaultconfigs
01/04/2021  03:36 PM                11 eula.txt
01/07/2021  04:37 PM           209,636 forge-1.16.4-35.1.29.jar
01/07/2021  04:37 PM         1,866,428 installer.log
01/08/2021  09:02 PM    <DIR>          kubejs
01/07/2021  04:37 PM    <DIR>          libraries
01/04/2021  04:52 PM    <DIR>          local
01/11/2021  12:13 AM    <DIR>          logs
01/07/2021  04:37 PM        37,961,464 minecraft_server.1.16.4.jar
01/08/2021  09:34 PM                73 mode.json
01/08/2021  09:32 PM    <DIR>          mods
01/10/2021  02:44 PM               275 ops.json
01/08/2021  09:02 PM    <DIR>          packmenu
01/08/2021  09:02 PM    <DIR>          patchouli_books
11/10/2020  03:04 PM             1,184 server-guide.txt
11/10/2020  03:04 PM             3,296 server-start-license.md
11/10/2020  03:04 PM               690 server-start-readme.md
11/10/2020  03:04 PM            45,884 server-start.bat
11/10/2020  03:04 PM            10,203 server-start.sh
01/11/2021  04:24 PM             1,136 server.properties
01/08/2021  09:12 PM               718 settings.cfg
01/11/2021  06:24 PM               435 usercache.json
01/09/2021  08:17 PM               228 usernamecache.json
01/09/2021  08:14 PM               348 whitelist.json
              20 File(s)     40,141,618 bytes
              15 Dir(s)  12,881,661,952 bytes free
```
(`2020` is the world folder)

to a clean fresh install of the server with zero modifications:

```
 Directory of C:\Servers\Test

01/11/2021  10:29 PM    <DIR>          .
01/11/2021  10:29 PM    <DIR>          ..
01/11/2021  10:23 PM    <DIR>          .mixin.out
01/11/2021  10:22 PM            39,605 1.16.4.json
01/11/2021  10:25 PM                 2 banned-ips.json
01/11/2021  10:25 PM                 2 banned-players.json
01/11/2021  10:23 PM    <DIR>          config
01/11/2021  10:20 PM    <DIR>          defaultconfigs
01/04/2021  03:36 PM                11 eula.txt
01/11/2021  10:22 PM         1,865,686 forge-1.16.4-35.1.29-installer.jar.log
01/11/2021  10:22 PM           209,636 forge-1.16.4-35.1.29.jar
01/11/2021  10:20 PM    <DIR>          kubejs
01/11/2021  10:22 PM    <DIR>          libraries
01/11/2021  10:26 PM    <DIR>          local
01/11/2021  10:23 PM    <DIR>          logs
01/11/2021  10:22 PM        37,961,464 minecraft_server.1.16.4.jar
01/11/2021  10:24 PM                71 mode.json
01/11/2021  10:20 PM    <DIR>          mods
01/11/2021  10:25 PM                 2 ops.json
01/11/2021  10:20 PM    <DIR>          packmenu
01/11/2021  10:20 PM    <DIR>          patchouli_books
11/10/2020  03:04 PM             1,184 server-guide.txt
11/10/2020  03:04 PM             3,296 server-start-license.md
11/10/2020  03:04 PM               690 server-start-readme.md
11/10/2020  03:04 PM            45,884 server-start.bat
11/10/2020  03:04 PM            10,203 server-start.sh
01/11/2021  10:24 PM             1,138 server.properties
01/03/2021  04:02 PM               717 settings.cfg
01/11/2021  10:25 PM                 2 usercache.json
01/11/2021  10:25 PM                 2 whitelist.json
01/11/2021  10:26 PM    <DIR>          world
              19 File(s)     40,139,595 bytes
              13 Dir(s)  12,881,657,856 bytes free

```

The only different file I can see is `usernamecache.json` exists in the actual server vs the clean server and I assume that's only because the clean server never had anyone connect to it considering this file has the usernames and MD5 hashes of those players I know have been on the real server.

**Comment by r-mc2** [comment] 2021-01-12 03:46
I also tried changing the MOTD. Reduced it all the way down to `Enigmatica` for extreme brevity. Error says the data packet is actually bigger than it used to be:

```
[22:44:20] [Netty Server IO #1/ERROR] [minecraft/NettyPacketEncoder]:
io.netty.handler.codec.EncoderException:
String too big (was 33470 bytes encoded, max 32767)
```

When I first reported this issue the byte size was `33195 bytes`.

**Comment by Ev1dentFir3** [comment] 2021-01-12 06:00
I just downloaded 0.3.5 for the first time today, trying to get it setup on Heavy Node, ran the install script on my local PC then uploaded the folder to Heavy Node. After that I merged region files from the official curseforge Skyblock 4 map. I'm getting the same issue, server throws error any time I refresh the server list page, and it doesn't show the server status or MOTD.

I'm also getting alot of other errors on boot that are not related to this, but here is the entire log anyway.
[https://raw.githubusercontent.com/Ev1dentFir3/Console-Logs/main/log.log](https://raw.githubusercontent.com/Ev1dentFir3/Console-Logs/main/log.log)

I'm almost positive this is related to the world folder some how because when I generate a blank standard world it fixes the issue. Would love to get this to work with skyblock.

**Comment by NillerMedDild** [comment] 2021-01-12 10:28
Hmm. Would one of you mind removing the mod RecipeBuffers from server and client, and trying again?

**Comment by Firestorm7893** [comment] 2021-01-12 16:41
I'll try right now

**Comment by Firestorm7893** [comment] 2021-01-12 16:55
nope 😥

**Comment by r-mc2** [comment] 2021-01-13 20:29
So, decided to try and dig a bit deeper than just the main files/dirs in the root directory. Threw it into BeyondCompare to do the digging for me:
![image](https://user-images.githubusercontent.com/36780233/104506855-f00fb400-55b3-11eb-8c83-b4bf0b262877.png)

Almost nothing is really different that I can see, at least that shouldn't be different (e.g. whitelist, settings, server props, the addition of the 3 mods mentioned earlier, etc)

Anything jump out at you all?

**Comment by NillerMedDild** [comment] 2021-01-13 21:38
What are you comparing there? 😄

**Comment by r-mc2** [comment] 2021-01-13 21:39
Ahh, sorry.

Left: Current Server Install <-----> Right: Clean Server Install (unmodified)

**Comment by NillerMedDild** [comment] 2021-01-13 21:41
Hmm, what's the difference in `settings.cfg`? Just RAM?
May I see the `server.properties` file for both?

**Comment by r-mc2** [comment] 2021-01-13 21:44
`server.properties`:
![image](https://user-images.githubusercontent.com/36780233/104513847-51d51b80-55be-11eb-8b2a-e459b4d88304.png)
(Same comparison to above. Left is current server, right is clean install)

`settings.cfg`
```
; Just the changes I've made
MAX_RAM=10G
HIGH_CPU_PRIORITY=1
```

**Comment by NillerMedDild** [comment] 2021-01-13 21:57
Phew, view-distance=12 might cause some lag :P Other than that, I still have no idea.

**Comment by r-mc2** [comment] 2021-01-13 22:01
That could explain some of the TPS issues we've been seeing when 4 of us are on and spread far apart. I set it more as an option for others to have up to 12 if they wanted thinking it'd allow the client to at least go up that far if they desired.

**Comment by NillerMedDild** [comment] 2021-01-13 22:02
Client and server view-distance are separate, client can go above the server's view-distance if they want :)

**Comment by Ev1dentFir3** [comment] 2021-01-14 02:29
@NillerMedDild I was able to just generate a new world from scratch instead of trying to use the pre-existing world that I originally imported for skyblock, and this fixed it for me without removing any mods at all. I ran the installer batch file on my local machine, then uploaded directly to the host. (heavynode)

**Comment by r-mc2** [comment] 2021-01-14 21:42
Hmm, checking the error again today; whatever it is it is growing:

`33616 bytes` in size now. Originally `33195` then later `33470` bytes.

So maybe something to do with region data? Or something else that grows as players progress in a world? I realize wild speculation isn't too helpful, but hopefully it can help others narrow their focus as they come to help/report.

**Comment by Pandora1337** [comment] 2021-01-17 23:39
Hi,
I just had the same issue, I solved it by changing the server-icon.png to something lightweight (in my case a 5kb picture, it also must not exceed 64x64 resolution).

 The error is also logged whenever the client pings the server, and is likely caused due to the server sending things like motd, player count, latency, and a server icon to the client, and exceeding the inbuilt limit.

I am guessing that in your case the picture associated with the server is too large for the ping to handle, and so corrupting the entire ping info so that clients percieve the server as offline.

I hope this was helpful!

**Comment by r-mc2** [comment] 2021-01-19 04:13
Well, I gave Pandora's comment a try (thank you for suggesting it!) and grayscaled the existing PNG file. Shaved a whopping 0.5KB off the file size... but it's working now. Looks a little silly with it in grayscale, but it's nice to see the mod compatibility check and number of players online again.

![image](https://user-images.githubusercontent.com/36780233/104986946-70824a80-59e2-11eb-9cbc-e907d84b5e9a.png)


I do wonder though would it be worth deleting the PNG entirely? Would the server regenerate the PNG with something more server-friendly?

I'll leave this issue open for now as it still feels weird for a fix and would like to see if others who reported it here as well have as much success.

**Comment by InfinitiesLoop** [comment] 2021-01-25 20:57
For what it is worth, I ran into this and worked around it.

1. Started with a fresh install of 0.3.7 server
2. Replaced the world directory with data from a single player world (just wholesale replaced the entire directory)
3. --> Server was not appearing as online, and I could see the 'String too big' error in the server log every time I refreshed the server list on the client.
4. As suggested I modified `server-icon.png` -- but for me there was no such file in the server directory at all to begin with. So I found `icon.png` in the world directory (it was 11kb), copied it into the root, renamed it to `server-icon.png`, then edited it to grayscale (it became 5kb).
5. --> Now the server appears online in the server list of a client.

Perhaps it is something about using a copied single player world? Like it's using a larger icon by default in that situation? Presumably the ping comes back with a list of mods, so might just be a straw/camel's back situation as mods are added.

**Comment by NillerMedDild** [comment] 2021-01-26 19:38
For clarity for people finding this issue:

Fix and cause found by @InfinitesLoop:

This can happen when singleplayer worlds are copied into servers.

Modify `server-icon.png` in the server folder: If no such file exists, add one. One way to do the latter is to find `icon.png` in the world directory, copy it into the root, and make it smaller or grayscale using paint or similar.

**Closed** 2021-02-23 19:17 UTC
Labels: Bug, Status: Fixed In Next Release

**Comment by timename** [comment] 2023-12-09 23:54
我也遇到了相似的问题：Internal Exception: io.netty.handler.codec.EncoderException: String too big
为了解决这个问题，我排查了许多文件。终于，我在服务器文件：server.properties 中发现了许多无意义的乱码，类似\u00C3\u0083\u00C2\u0083\u00C3\u0082\u00C2\u0083\u00C3\u0083 我将他们全部删除后，服务器就可以正常运行了。     

Translate through Bing
I'm also having a similar issue: Internal Exception: io.netty.handler.codec.EncoderException: String too big
To solve this problem, I troubleshoot a number of files. Finally, I found a lot of meaningless garbled characters in the server file: server.properties, like \u00C3\u0083\u00C2\u0083\u00C3\u0082\u00C2\u0083\u00C3\u008. After I deleted them all, the server was running normally.
