### ISSUE TITLE
Constellation paper dupe ( It may work with other astral sorcery itens )

### ISSUE THREAD

**Issue by Losangulo** [NillerMedDild/Enigmatica6#3725] opened 2021-11-14 11:40 UTC
### Modpack Version

0.5.20

### Describe your issue.

When you have constellation papers inside a chest and use the cardbox from mekanism, the constellations that are inside the chest will drop and when you unbox the chest and open it, the constellation papers will be there, you just duped constellation papers, it may work with other astral sorcery itens, i haven´t tested it yet

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment] 2021-11-14 11:51
Duplicate of #1847

**Closed by MuteTiefling** 2021-11-14 11:51 UTC
Labels: Bug
