### ISSUE TITLE
Diamond crafters for refined storage deleting all patterns upon login/logout

### ISSUE THREAD

**Issue by Wolfog288** [NillerMedDild/Enigmatica6#3396] opened 2021-10-07 21:13 UTC
### Modpack Version

1.16.5 0.5.14

### Describe your issue.

This has happened 3 times now so im pretty sure its a bug. Essentially i use a diamond crafter to store my crafting recipes for refined storage and whenever i log back on all are gone and all upgrades in that crafter are gone too almost like its wiping the inventory, when i look in the crafting manager, the other machines i have with patterns in keep theirs its just the diamond crafter ive got for direct crafting table crafts, i tried moving the crafter, i checked it was within a chunk and not near the edge and even re-made a crafter and all the patterns 3 times now, would like to hear back because its making playing rather annoying having to use time and resources to re-set up a bunch of recopies each time.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment] 2021-10-08 03:55
Duplicate of #3076

**Closed by NillerMedDild** 2021-10-08 03:55 UTC
Labels: Bug
