### ISSUE TITLE
[0.4.10] Nether mob into the overworld

### ISSUE THREAD

**Issue by Kero34** [NillerMedDild/Enigmatica6#2086] opened 2021-05-02 18:06 UTC
After update and the fix with IntergatedTunnels (crash server : issue #2083 ), we have all mob from nether into overworld.
**Screenshots**
https://i.imgur.com/m1VgDla.jpeg

**Comment by NillerMedDild** [comment] 2021-05-02 18:09
Duplicate of #2078, I'm afraid there's nothing we can do about it, it shouldn't happen again in chunks you've been in with version 0.4.10 if that's any consolation ^^'

**Comment by NillerMedDild** [comment] 2021-05-02 18:49
There's a possible sucky workaround btw:
> Downgrade to 0.4.8, load a backup, add the mod Chocolate fix, visit all places you want not to change and then update to 0.4.10

**Closed by NillerMedDild** 2021-05-02 18:49 UTC
Labels: Duplicate
