### ISSUE TITLE
bountiful baubles wormhole potion

### ISSUE THREAD

**Issue by p5ychedelik** [NillerMedDild/Enigmatica6#1317] opened 2021-02-15 17:19 UTC
**Modpack version**

**Describe the bug**
when the wormhole potion is used it crashes the game. it does not generate a crash report but this is what was posted to my server 

**Logs**
[11:06:41] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID bdf82eeb-fb40-43cb-9ca6-9e84ac281263
[11:06:41] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /192.168.1.229:65238
net.minecraft.crash.ReportedException: Ticking player
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:467) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,pl:mixin:A}
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}
Caused by: java.lang.ClassCastException: net.gigabit101.shrink.cap.ShrinkImpl$DefaultImpl cannot be cast to cursedflames.bountifulbaubles.common.capability.CapabilityWormholePins$IWormholePins
        at cursedflames.bountifulbaubles.common.wormhole.ContainerWormhole.<init>(ContainerWormhole.java:55) ~[bountifulbaubles:?] {re:classloading,pl:runtimedistcleaner:A}
        at cursedflames.bountifulbaubles.common.item.items.ItemPotionWormhole$1.createMenu(ItemPotionWormhole.java:72) ~[bountifulbaubles:?] {re:classloading}
        at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:222) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:169) ~[forge:?] {re:classloading}
        at cursedflames.bountifulbaubles.common.item.items.ItemPotionWormhole.doWormhole(ItemPotionWormhole.java:81) ~[bountifulbaubles:?] {re:classloading}
        at cursedflames.bountifulbaubles.common.item.items.ItemPotionWormhole.func_77654_b(ItemPotionWormhole.java:89) ~[bountifulbaubles:?] {re:classloading}
        at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:218) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:apotheosis:apothitemusehook,xf:fml:astralsorcery:add_missing_tag_enchantment_tooltip,xf:fml:astralsorcery:add_enchantment_tooltip,xf:fml:forge:filled_map.4,pl:mixin:APP:dankstorage.mixins.json:ItemStackMixin,pl:mixin:APP:losttrinkets.mixins.json:ItemStackMixin,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_71036_o(LivingEntity.java:2843) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf:fml:astralsorcery:water_movement_slowdown_prevention,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:eidolon.mixins.json:LivingEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.ServerPlayerEntity.func_71036_o(ServerPlayerEntity.java:1056) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.entity.LivingEntity.func_184608_ct(LivingEntity.java:2723) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf:fml:astralsorcery:water_movement_slowdown_prevention,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:eidolon.mixins.json:LivingEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf:fml:astralsorcery:water_movement_slowdown_prevention,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:eidolon.mixins.json:LivingEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:dankstorage.mixins.json:MixinPlayerEntity,pl:mixin:APP:losttrinkets.mixins.json:PlayerEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        ... 9 more
[11:06:41] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: p5ychedelik lost connection: Internal server error
[11:06:41] [Server thread/INFO] [minecraft/DedicatedServer]: p5ychedelik left the game
[ApotheosisCore]: Patching CombatRules#getDamageAfterMagicAbsorb

**Screenshots**

**Comment by theboo** [comment] 2021-02-15 18:11
This bug has been around for a minute now, no clue when it will actually get fixed... Duplicate of https://github.com/NillerMedDild/Enigmatica6/issues/1150#issue-797508803

**Closed** 2021-02-15 18:12 UTC
Labels: Bug, Duplicate, Mod Issue
