### ISSUE TITLE
Warm Void may be causing a client freeze?

### ISSUE THREAD

**Issue by coolbot100s** [NillerMedDild/Enigmatica6#3036] opened 2021-08-19 09:51 UTC
### Modpack Version

0.5.9 (modded)

### Describe your issue

Fell into the void with the Warm Void trinket equipped in an RFtoolsDimensions dimension, then given the "Loading World..." screen for a few minutes before giving up and rebooting the client, whenever trying to connect to my server since I've gotten soft frozen again, one time getting an "out of memory" error. According to the server I'm still in the RFtools Dimension. 
![image](https://user-images.githubusercontent.com/76798835/130045821-388a504b-af81-4015-8d11-2fcbdacf9ef4.png)
Not sure what else would be causing the issue as before equipping the Warm Void falling in an rftools dimension would result in a normal death.

Moving myself to my bed spawn point I connect to the server again fine, however, dead.

### Have you modified the modpack?

Yes

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment] 2021-08-19 17:45
Duplicate of #2299

**Closed** 2021-08-19 17:49 UTC
Labels: Duplicate
