### ISSUE TITLE
Obsidian Honeycomb Still missing centrifuger recipe

### ISSUE THREAD

**Issue by rjulib00** [NillerMedDild/Enigmatica6#1672] opened 2021-03-12 19:54 UTC
**Modpack version**
0.4.3
**Describe the bug**
Obsidian honeycomb (and block) still missing the centrifuger recipe

**Comment by Halfdeaf** [comment] 2021-03-12 20:02
Duplicate of #1411

**Closed** 2021-03-12 21:41 UTC
Labels: Duplicate
