### ISSUE TITLE
[Bug] TheOneProbe-Create oddities

### ISSUE THREAD

**Issue by Shines113** [NillerMedDild/Enigmatica6#727] opened 2021-01-03 11:25 UTC
**Modpack version**
0.3.2

**Issue**
When TheOneProbe is installed alongside Create, the carriage structures will not turn when on rails, and will be aligned oddly. Removing TOP resolved the issue, but left me without a probe option. (Should I submit this to one or the other mod specific githubs?) (Is there an alternative indicator mod that would be possible to use?)

**Comment by NillerMedDild** [comment] 2021-01-03 15:14
Could you perhaps supply screenshots of this behaviour?

HWYLA in an alternative indicator mod, I haven't tested it recently though so I can't promise how well it'll work in E6.

**Comment by Shines113** [comment] 2021-01-03 21:08
I'll post some screenshots in a few hours. I'm in an unusual timezone, so it might be a little.

**Comment by NillerMedDild** [comment] 2021-01-03 21:11
No rush, I just appreciate the help :)

**Comment by Shines113** [comment] 2021-01-04 05:49
All right, here is a very simple train I cobbled together in the pack, and as you can see rather than rotate, it stays linked to one cart. Both carts are still one carriage, it just creates this... Oddity. duplicating my profile and removing TOP makes the carriages behave like they normally do.

[https://cdn.discordapp.com/attachments/786702365997793290/795528818864685086/2021-01-03_23.45.26.png](url)
[https://cdn.discordapp.com/attachments/786702365997793290/795528816893493288/2021-01-03_23.45.27.png](url)
[https://cdn.discordapp.com/attachments/786702365997793290/795528821470003260/2021-01-03_23.45.29.png](url)
[https://cdn.discordapp.com/attachments/786702365997793290/795528823403839488/2021-01-03_23.45.30.png](url)

**Comment by Darkere** [comment] 2021-01-04 07:19
How did you determine this to be caused by the one probe? Cause I kind of doubt that...

Much more likely caused by Quark or Transport.

**Comment by Shines113** [comment] 2021-01-04 07:47
Due to some comments in the create discord. When I deleted the one probe from my duplicated profile, it began behaving normally.

I have no idea *why* it performs this way, but it seems to. 

EDIT: Either that, or one of the mods that turning TOP off also seems to have disabled. I'll try to do some more testing

**Comment by Shines113** [comment] 2021-01-04 08:03
Both quark and transport are still enabled, but mekanism and some RFtools mods are disabled by disabling of TOP. 

However based on the comments in the other discord, it seems like it may be TOP. Here are some screenshots of it with it disabled. The pasted structure turns just fine.

[Turning](https://cdn.discordapp.com/attachments/786702365997793290/795562609599578143/2021-01-04_02.01.13.png)
[Another angle](https://cdn.discordapp.com/attachments/786702365997793290/795562612112228372/2021-01-04_02.01.08.png)
[and straight again](https://cdn.discordapp.com/attachments/786702365997793290/795562616067981312/2021-01-04_02.01.18.png)

**Comment by kil0byt3** [comment] 2021-01-04 14:12
Relevant Create issue here, seems to be fixed by the new release: https://github.com/Creators-of-Create/Create/issues/638

release notes: https://www.curseforge.com/minecraft/mc-mods/create/files/3158185

`- Fixed incompatibility with The One Probe`

**Closed** 2021-01-07 22:06 UTC
Labels: Mod Issue, Status: Fixed In Next Release
