### ISSUE TITLE
World Gen

### ISSUE THREAD

**Issue by Lithnane** [NillerMedDild/Enigmatica6#2251] opened 2021-05-23 18:36 UTC
**Modpack version**
0.4.14
**Describe the bug**
After updating the pack on my server World Generation issues can be found all over
**Logs**
No Crashes so logs dont matter
**Screenshots**
![2021-05-23_14 34 53](https://user-images.githubusercontent.com/84678623/119272506-40d39100-bbd4-11eb-9f65-9494415ac3cf.png)

**Comment by NillerMedDild** [comment] 2021-05-23 20:46
From which version? :)

**Comment by Lithnane** [comment] 2021-05-23 20:55
from 0.4.10 to latest

**Comment by NillerMedDild** [comment] 2021-05-23 20:57
duplicate of #1796 #2058 #2090 
You can fix it by:
- Reverting the modpack to 0.4.10
- Add the mod Biome Id Fixer
- Load a backup of your world and join it
- Now you can safely update

**Closed by NillerMedDild** 2021-05-23 20:57 UTC
Labels: Bug
