### ISSUE TITLE
[0.4.8] The server crashes when specific people join (java.lang.stackoverflowerror)

### ISSUE THREAD

**Issue by LittleWolfy** [NillerMedDild/Enigmatica6#1995] opened 2021-04-15 22:12 UTC
[0.4.8]

[Describe the bug]
So the bug happened when a player in our server joined and the server immediately crashed with the error java.lang.stackoverflowerror so the main thing we figured was that this person had lots of items on their person, in the back packs and inside them too, we did a few more tests and they crashed the server every time while they loaded in- but then on another time another new player just picked up a berry and jumped and the same issue happened- complete server crash, and we really have no idea why

[Logs]
https://pastebin.com/rN4fq8GP <-- here is a link to our crash report
https://pastebin.com/s5yaB2L6 <-- here is a link to our latest

Our server is run on https://serverminer.com/ with 8gb of ram

Thank you for taking your time to read through!

**Comment by NillerMedDild** [comment] 2021-04-16 04:00
Duplicate of #1742 
Replace the Simple Farming jar on the server with this one: https://drive.google.com/file/d/1ygAHyWvJhfrbkn2IWJo0rLY0xpqUFmzk/view?usp=sharing :)

**Closed by NillerMedDild** 2021-04-16 04:00 UTC
Labels: Bug

**Comment by LittleWolfy** [comment] 2021-04-17 00:29
Thank you so much! just got the chance to test it and it worked straight away! thank you so much!
