### ISSUE TITLE
Bug in auto crafters from RFTools and Bees

### ISSUE THREAD

**Issue by SyButter** [NillerMedDild/Enigmatica6#3262] opened 2021-09-17 01:32 UTC
### Modpack Version

0.5.11

### Describe your issue

Using RFTools auto crafters and bee honeycomb drops 
I was trying to craft tuna in order to make sushi but when I applied the tuna recipe in the auto crafter the auto-generated output showed up as nori and then the physical outp[ut came through as cucumbers. Is this a pack error or was there an update I didn't know about?

![carafterthang](https://user-images.githubusercontent.com/61396233/133709358-f2b1b161-09c4-4385-8b74-d4092d5776e3.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by TemperedFool** [comment] 2021-09-17 02:20
You're totally forgiven for missing this, but this is a duplicate of #3089. This should be resolved in the next release.

**Closed by TemperedFool** 2021-09-17 02:20 UTC
Labels: Duplicate
