### ISSUE TITLE
Windowlogging - Mod Suggestion

### ISSUE THREAD

**Issue by ejgibs** [NillerMedDild/Enigmatica6#2222] opened 2021-05-20 01:41 UTC
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/windowlogging
**Mod description**
Allows glass panes to be placed in stair and slab blocks for seamless window facades.

**Why would you like the mod added?**
Would open up window building options.
**Screenshots if applicable.**

**Comment by NillerMedDild** [comment] 2021-05-20 05:37
Duplicate of #1399

**Closed by NillerMedDild** 2021-05-20 05:37 UTC
Labels: Suggestion
