### ISSUE TITLE
Crafting Emitter disappears after being broken

### ISSUE THREAD

**Issue by NurikSakura** [NillerMedDild/Enigmatica6#3245] opened 2021-09-16 00:03 UTC
### Modpack Version

0.5.11

### Describe your issue

The crafting emitter from RSRequestify does not drop an item, when broken after being placed.

https://www.twitch.tv/nuriksakura/clip/ImpartialDifferentLardOhMyDog-6bMyMeh7ofpcu5of

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment] 2021-09-16 04:53
Thanks for the report, I relayed it here: https://github.com/Buuz135/RS-Requestify/issues/25

**Comment by Quezler** [comment] 2021-09-16 04:58
duplicate of https://github.com/NillerMedDild/Enigmatica6/issues/3016 😇

**Comment by NillerMedDild** [comment] 2021-09-16 05:16
Woops 😅

**Closed** 2021-09-16 05:16 UTC
Labels: Status: Reported, Mod Issue

**Comment by NurikSakura** [comment] 2021-09-16 09:20
Although it's a duplicate, in the original post it was said to be fixed in 0.5.11. Still, this is a report on 0.5.11 and the bug is still present.

**Comment by Quezler** [comment] 2021-09-16 09:28
the "fixed" mentioned there was another issue (check the edit history of the messages in 3016): https://github.com/NillerMedDild/Enigmatica6/issues/2948

**Comment by NillerMedDild** [comment] 2021-09-16 09:48
The issue is still open, that means it has not yet been released :)
