### ISSUE TITLE
Random minecraft kicks from server after update 0.4.0

### ISSUE THREAD

**Issue by Staffid-code** [NillerMedDild/Enigmatica6#1431] opened 2021-02-26 09:55 UTC
Hey,
Im playing on minecraft server with my friends. We use radmin and sometimes server kicks us with that error.
![image](https://user-images.githubusercontent.com/57596942/109284905-b079f000-7820-11eb-8097-28c66f905d2d.png)

I'm hosting server on my PC.
i9 9900K
rtx 2080
32GB ram (16gb for server)

We don't rly know what to do and where is the problem (our game, server or java maybe)

**Comment by Merlo17** [comment] 2021-02-26 09:58
Duplicate of https://github.com/NillerMedDild/Enigmatica6/issues/1409, but thanks for reporting ^^

**Closed by Merlo17** 2021-02-26 09:58 UTC
