### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by Ghordath** [NillerMedDild/Enigmatica6#3034] opened 2021-08-19 08:57 UTC
### Modpack Version

Enigmatca6-0.5.9

### Describe your issue

When using a Cardboard box to move a chest with Astral Sorcery Rock crystals or Constellation papers in it, they will duplicate.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Darkere** [comment] 2021-08-19 08:59
Duplicate of #1847

**Closed by Darkere** 2021-08-19 08:59 UTC
Labels: Bug
