### ISSUE TITLE
RFTools Machine Infuser does not accept Dimensional Shards from Emendatus Enigmatica

### ISSUE THREAD

**Issue by AgentUndertaker** [NillerMedDild/Enigmatica6#2256] opened 2021-05-24 08:34 UTC
Enigmatica 6, Version 0.4.14

Description:
As the title says, the RFTools Machine Infuser seems to not accept the normal Dimensional Shards for infusion. They can be forced into the Infuser via a hopper, but even when you use that method, the infusion does not take place. I suspect it may be due to the mod expecting the RFTools shards and not recognizing the E.E. shards as a valid input.

[Video Demonstration](https://youtu.be/o70sutYa4gc)

**Comment by NillerMedDild** [comment] 2021-05-24 10:35
Duplicate of #1456 
You can convert them via crafting 🙂

**Closed by NillerMedDild** 2021-05-24 10:35 UTC
Labels: Bug

**Comment by pm065** [comment] 2021-05-24 19:23
Would it be possible to simply override the EE loot tables and make RFTools dim shards drop instead, at least until this is fixed? That would remove the need for a slightly immersion-breaking conversion recipe.

**Comment by NillerMedDild** [comment] 2021-05-24 19:28
Yes it would :/ tbh I thought McJty would've looked into this by now.

**Comment by NillerMedDild** [comment] 2021-05-24 19:29
Looks like we got help :D https://github.com/McJtyMods/RFToolsBase/pull/50

**Comment by pm065** [comment] 2021-05-24 20:25
I'm not entirely convinced that will get merged, though, given the author's response to the related issue.

**Comment by NillerMedDild** [comment] 2021-05-25 05:16
No that's true, if it doesn't we'll implement the loot tables fix :)
