### ISSUE TITLE
Using Cardboard boxes with rock crystals will dupe them

### ISSUE THREAD

**Issue by llayoudontknow1** [NillerMedDild/Enigmatica6#2764] opened 2021-07-17 20:26 UTC
When attempting to rearrange my base, I was using the cardboard boxes to move the chests or barrels around. Upon using the cardboard box on the storage with the astral rock crystals in it, it duplicated them and dropped them on the ground. Take the cardboard box off the storage and the rock crystals are still in there, plus the ones that dropped to the ground.

**Comment by NillerMedDild** [comment] 2021-07-18 16:01
Duplicate of #1847, thanks anyhow :)

**Closed by NillerMedDild** 2021-07-18 16:01 UTC
