### ISSUE TITLE
Foliet Crusher crashes Enigmatica 6 server

### ISSUE THREAD

**Issue by HowToDiscord** [NillerMedDild/Enigmatica6#2700] opened 2021-07-11 23:35 UTC
SERVER Version 1.16.5

Ticking Entity SERVER Crash:
Happens when foliet crusher attempts to crush ores. Voicechat Mod and Login Shield Mod are installed alongside mod pack.

Crash Log:
https://gist.github.com/HowToDiscord/fc58e70ba9bbb2ba004dae78f7ba38f4

How to fix? I am a noob at server management and have zero coding experience.

**Comment by theboo** [comment] 2021-07-11 23:42
this was fixed in occultism, but that version is not in the pack yet, should be fixed in next update of e6... could fix it by updating occultism, but everyone on your server would need to do the same

**Comment by HowToDiscord** [comment] 2021-07-11 23:42
Thanks! Sent from Mail for Windows 10 From: thebooSent: Sunday, July 11, 2021 7:42 PMTo: NillerMedDild/Enigmatica6Cc: HowToDiscord; AuthorSubject: Re: [NillerMedDild/Enigmatica6] Foliet Crusher crashes Enigmatica 6 server (#2700) this was fixed in occultism, but that version is not in the pack yet, should be fixed in next update of e6... could fix it by updating occultism, but everyone on your server would need to do the same—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by theboo** [comment] 2021-07-12 12:41
Duplicate of #2661

**Closed** 2021-07-12 12:43 UTC
Labels: Duplicate, Mod Issue
