### ISSUE TITLE
Mekanism:Additions

### ISSUE THREAD

**Issue by Sanguinely** [NillerMedDild/Enigmatica6#902] opened 2021-01-15 18:46 UTC
Mekanism:additions adds glow panels and plastic blocks as well as balloons. as of right now i have no use to have 80k+ HDPE sheets. I'd like to be able to turn them into blocks and use them for building/lighting but that's not possible right now. IK Mekanism additions also adds the baby mobs and not everyone likes them, perhaps they can be disabled and additions can be added so that there is a use for the hdpe besides having to trash it??

**Comment by NillerMedDild** [comment] 2021-01-15 19:40
Duplicate of #572

**Closed by NillerMedDild** 2021-01-15 19:40 UTC
Labels: Duplicate
