### ISSUE TITLE
Pretty Pipes don't extract if a drawer with a void upgrade is the target

### ISSUE THREAD

**Issue by Ieldra2** [NillerMedDild/Enigmatica6#3067] opened 2021-08-24 13:59 UTC
### Modpack Version

0.5.11

### Describe your issue

If you use Pretty Pipes to extract items from inventories, items are not extracted if they would go into a Storage Drawer that has a void upgrade on it, regardless of whether it is actually full. Other items are extracted normally, and the extraction of the problematic items resumes immediately if you remove the void upgrade from the target drawer. 
The problem is retained if you have a secord target inventory with a lower priority in your system. If the target with the highest priority is a drawer with a void upgrade, the items will remain in their source inventory.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment] 2021-08-24 17:00
Thanks for the report, I'll relay it

**Comment by NillerMedDild** [comment] 2021-08-24 18:53
Most likely caused by Storage Drawers, and the chances of getting anything fixed from that mod is close to 0. I'm afraid I might as well close this :/ sorry.

**Closed by NillerMedDild** 2021-08-24 18:53 UTC
Labels: Status: Reported, Mod Issue
