### ISSUE TITLE
Immersive Engineering Wire Cutter

### ISSUE THREAD

**Issue by RacingEcho** [NillerMedDild/Enigmatica6#3378] opened 2021-10-05 04:06 UTC
### Modpack Version

0.5.14

### Describe your issue.

For some reason, if the I.E wire cutters have been used once they won't wor
![1](https://user-images.githubusercontent.com/50756326/135958480-7fe2275d-4837-44b9-8785-fbb20e0cf89b.png)
![2](https://user-images.githubusercontent.com/50756326/135958485-09280fa2-691b-4824-973a-7cdfb3c5e067.png)
k.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment] 2021-10-05 04:39
Duplicate of #3329

**Closed by NillerMedDild** 2021-10-05 04:39 UTC
Labels: Bug
