### ISSUE TITLE
Random loot reward always empty

### ISSUE THREAD

**Issue by dgobi** [NillerMedDild/Enigmatica6#730] opened 2021-01-03 17:43 UTC
**Modpack version**
Enigmatica 6 0.32 / Minecraft 1.16

**Issue**
The random loot reward (red die icon) in the quest book always produces no reward. The screen for the reward is blank.

**Comment by MuteTiefling** [comment] 2021-01-03 17:47
There's an issue with the quest loot tables being read properly on servers. This is already fixed in the next update.

**Comment by NillerMedDild** [comment] 2021-01-03 18:17
Duplicate of #717

**Closed by NillerMedDild** 2021-01-03 18:17 UTC
Labels: Duplicate
