### ISSUE TITLE
Facing game crash when exploring

### ISSUE THREAD

**Issue by useenzhekoay** [NillerMedDild/Enigmatica6#1235] opened 2021-02-06 13:58 UTC
**Modpack version**
0.3.13

**Describe the bug**
Crash when exploring.

**Logs**
[crash-2021-02-06_21.39.22-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/5936918/crash-2021-02-06_21.39.22-server.txt)
[crash-2021-02-06_21.50.59-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/5936919/crash-2021-02-06_21.50.59-server.txt)

**Screenshots**
No screensho.

**Comment by Darkere** [comment] 2021-02-06 14:24
Duplicate of #813

**Closed by Darkere** 2021-02-06 14:24 UTC
Labels: Bug
