### ISSUE TITLE
Refined storage shows more items in storage drawers than are actually there

### ISSUE THREAD

**Issue by Zosu** [NillerMedDild/Enigmatica6#721] opened 2021-01-02 22:02 UTC
**Modpack version**
0.32

**Issue**
If using more than 1 external storage interface to the same set of storage drawers, items will appear in the refined storage interface as multiples of what's actually in the storage drawer array depending on how many interfaces are connected. For example, with two external storage interfaces connected to the drawers 1 item in the drawer will appear as 2 items in the refined storage system. 3 storage interfaces connected to the drawers will make 1 item in the drawers appear as 3 items in the refined storage system, etc. 

**Logs**
N/A

**Comment by Buuz135** [comment] 2021-01-02 22:10
I don't think that can be easily fixed its like if 3 players opened a chest and reported the items that the chest had, they don't know about each other and they can't know if its the same stack or not.

It's more of a player not using the mod properly.

Does extracting the items work properly?

**Comment by Octr** [comment] 2021-01-02 22:56
As far as I experienced it's just a visual thing, no actual issues occur the system won't let you take out more than exists etc.
My friend ran into this when using multiple controllers on the same wall of drawers plugged into external storage interfaces, because the connected drawers were still within the drawers limit all 3 ended up reading the same drawers 3times
multiplying all the values in RS by 3.

again just a visual thing resolved by spreading controllers correctly or in this case using only 1 external storage on the controller.

**Closed** 2021-01-02 22:59 UTC
Labels: Status: Won't Fix

**Comment by Zosu** [comment] 2021-01-02 23:19
Yeah besides visual everything functions fine. I'll just orient things differently from now one :).

**Comment by TemperedFool** [comment] 2021-01-02 23:45
Yeah, this sounds like external storage working as designed. Having not tried it, will the same thing not happen if you put 2 external storages on a chest?

**Comment by Zosu** [comment] 2021-01-03 00:16
The same thing does happen when multiple interfaces are placed on a chest.
