### ISSUE TITLE
Sophisticated backpacks can't pull from slot 1 in toolbar

### ISSUE THREAD

**Issue by DocHuzz** [NillerMedDild/Enigmatica6#834] opened 2021-01-09 17:25 UTC
**Modpack version**
0.3.5 Beta

**Issue**
When putting items in the backpack, you cannot add the item in the first slot of your hotbar.  This was tested both in chest slot and on baubles back slot.  Shift clicking does nothing and clicking on the item closes the inventory completely.  Works for all 35 other slots fine, just first toolbar slot.

**Comment by NillerMedDild** [comment] 2021-01-09 21:13
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment] 2021-01-09 22:56
The toolbar slot you're currently on cannot be put in the backpack, to prevent duping and other odd interactions. Could that be the cause? :) I could not reproduce this without having toolbar slot 1 selected.

**Comment by P3pp3rF1y** [comment] 2021-01-10 11:23
This happens when you have backpack in curios slot and open it using a keybind. There was an issue in the logic that I had there where it incorrectly checked for changes in slot 0 in player's inventory to prevent dupe bugs when in fact it didn't need to check anywhere as backpack stack isn't accessible when you open it from curios slot.

It's fixed in the latest version of SBP

**Closed** 2021-01-14 21:39 UTC
Labels: Mod Issue, Status: Fixed In Next Release
