### ISSUE TITLE
Skipping Entity spam messages in console

### ISSUE THREAD

**Issue by KangyKSLG** [NillerMedDild/Enigmatica6#781] opened 2021-01-06 00:36 UTC
**Modpack version**
0.3.4

**Issue**
Hi, i'm constantly getting the following repeating error on my server running 0.3.4. I'm getting 10+ messages every second

![image](https://user-images.githubusercontent.com/42292756/103714913-1ed7ca00-4fb7-11eb-8771-59cedb6de052.png)

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5773276/latest.log)

**Comment by stefment** [comment] 2021-01-06 05:23
Try this. https://www.curseforge.com/minecraft/mc-mods/delogger

**Comment by KangyKSLG** [comment] 2021-01-06 10:12
Thanks for the suggestion!

While that seems like it would remove the messages, on further testing, whatever the server is doing to display those messages it causing lag and by "waiting for server" messages

**Comment by Darkere** [comment] 2021-01-06 11:05
check for a spawner going wild. Although that shouldn't cause that many duplicates...

**Comment by KangyKSLG** [comment] 2021-01-06 11:44
> check for a spawner going wild. Although that shouldn't cause that many duplicates... 

The only spawner in that area is my creeper spawner that you have to stand right next to for it to work.

Could this message also apply to laser drills? Where I was standing at the time has 5 laser drills

**Comment by KangyKSLG** [comment] 2021-01-06 11:57
To add to this, there is currently no one logged into the server and the console is still throwing up this message

**Comment by KangyKSLG** [comment] 2021-01-06 17:14
Okay it doesn't seem to be the Laser Ore Miners

**Comment by NillerMedDild** [comment] 2021-01-06 20:02
Which entity / entities is it?

**Comment by KangyKSLG** [comment] 2021-01-06 20:12
I wish I knew, the messages start like that, never actually mentioning the entity in question. 

Unless you know of another way I can find out?

**Comment by NillerMedDild** [comment] 2021-01-06 20:42
Huh, that's super weird. The entity name is usually at the end. Maybe the `debug.log` has the names?

**Comment by KangyKSLG** [comment] 2021-01-06 20:55
Not that I can see

I've shared the debug.log from OneDrive as it's too big to attach here.

https://1drv.ms/u/s!AtsfINBFkWrdg5lxRsvjmT_wUL36Aw?e=9uyh83

If it helps, you're more than welcome to log onto my server to test if it helps?

**Comment by NillerMedDild** [comment] 2021-01-06 21:24
This might be fixed by 0.3.5, but would you mind updating Resourceful Bees and see if that resolves the issue?

**Comment by KangyKSLG** [comment] 2021-01-06 21:25
Sure, give me 10- 15 minutes and i'll report back

**Comment by KangyKSLG** [comment] 2021-01-06 21:42
Okay, updating Resourceful bees didn't resolve the issue. If it helps, this didn't happen on 0.3.2

**Comment by NillerMedDild** [comment] 2021-01-06 22:03
Alright, thanks. I don't have any ideas at the moment, will keep thinking on it :)

**Comment by Darkere** [comment] 2021-01-06 22:08
If the messages are actually related to lag then running spark might reveal what is actually doing it.

**Comment by KangyKSLG** [comment] 2021-01-06 22:23
Spark?

**Comment by Darkere** [comment] 2021-01-06 22:32
https://www.curseforge.com/minecraft/mc-mods/spark

**Comment by KangyKSLG** [comment] 2021-01-06 22:52
Spark installed and server rebooting. Any recommendations on which command to run?

**Comment by Darkere** [comment] 2021-01-06 23:01
Something like /spark sampler --timeout 60 --only-ticks-over 200

200 should hopefully filter out anything that's just normal minecraft running... But it depends on the tps of your server.

**Comment by KangyKSLG** [comment] 2021-01-06 23:04
Okay I have the sampler results but i'm not sure what i'm looking for

Here's the link: https://spark.lucko.me/#Fbtjkix5Qg

**Comment by Darkere** [comment] 2021-01-06 23:10
Well I'm not sure this is the cause, but I do have a solution for your lag problem.

There seems to be either a large amount or very performance heavy fish on the server. The server is spending almost a third of its time on those.

**Comment by KangyKSLG** [comment] 2021-01-06 23:12
I did notice there was a lot of fish around. Anyway to permanently reduce their spawn short of running /kill every now and then?

**Comment by KangyKSLG** [comment] 2021-01-07 18:16
So my server is still throwing up skipping entity messages and I'm not sure how to remove the aquaculture fish to see if they will make a difference

Is there anything else I can do to help find the issue?

**Comment by NillerMedDild** [comment] 2021-01-07 18:49
`/kill @e[type=aquaculture:fishname]` ought to do it.
You can see the names with `/forge entity list`

**Comment by KangyKSLG** [comment] 2021-01-07 19:08
Roger Roger :) although I will say, contrary to the spark report, last time I ran the forge entity command the fish didn't appear to have enough of them to cause issues

**Comment by NillerMedDild** [comment] 2021-01-07 19:14
It doesn't have to be amount, a single entity can do it if the AI is laggy enough 😄 So is your issue resolved?

**Comment by KangyKSLG** [comment] 2021-01-07 19:26
Can you give me a couple of hours to test? I'm not at my computer yet

**Comment by NillerMedDild** [comment] 2021-01-07 19:28
Of course.

**Comment by KangyKSLG** [comment] 2021-01-07 20:12
Okay, I liked of the aqua culture fish and the skipping entity messages is still there

Could it be related to the world file due to it being used from 0.3.0? Were any mods removed that added mobs?

**Comment by NillerMedDild** [comment] 2021-01-07 20:44
A few bees were removed, a few were added, that is most likely the cause. It shouldn't cause lag though - Is the lag issue gone? :)

**Comment by KangyKSLG** [comment] 2021-01-07 21:00
I'll see if I can find the rogue bees in my world save. 

I think the lag has gone yes, it may have been coincidence, I just noticed the 2 around the same time

**Comment by KangyKSLG** [comment] 2021-01-07 22:21
Okay I think I found my skipping entity source. Forge entity list is saying that there are 5 bees in the area and I can hear them buzzing. So I ran the kill command for one of the bees and I get a no entity found message. Now I just need to find a way to clear these entities, any ideas?

![image](https://user-images.githubusercontent.com/42292756/103951527-c0d1f080-5136-11eb-9f96-cd45f99fd2ac.png)

**Comment by NillerMedDild** [comment] 2021-01-07 22:33
They're somewhere in the region file I guess? No idea how to remove all traces of them :/

**Comment by KangyKSLG** [comment] 2021-01-07 22:40
That was my thought and navigated to where I thought they were with NBTExplorer but I came up blank

**Comment by KangyKSLG** [comment] 2021-01-07 23:05
Okay i've resolved this. Turns out it was one of my tier 2 bee hives! I'll close this now and thanks for all the assistance!

**Closed** 2021-01-07 23:07 UTC
Labels: Bug, Support
