### ISSUE TITLE
Can't smelt starmetal ore

### ISSUE THREAD

**Issue by phgilde** [NillerMedDild/Enigmatica6#1715] opened 2021-03-16 13:58 UTC
I cant smelt astral sorcery starmetal ore into ingots. When pressing "U" it shows no uses and when putting it in a furnace it also doesnt smelt.
Im in version 0.4.3.

**Comment by TemperedFool** [comment] 2021-03-16 14:26
Duplicate of #1542 - fixed in #1544

**Closed as completed** 2021-03-16 15:04 UTC
Labels: Duplicate
