### ISSUE TITLE
Villager trades require Immersive Engineering Steel Ingots

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2253] opened 2021-05-23 22:56 UTC
**Modpack version**
0.4.10

**Describe the bug**
Villager trades require Immersive Engineering Steel Ingots that are uncraftable. Using a Stonecutter to change a Block of Steel into the Immersive Engineering version does not help, as "unpacking" it gives EE Steel Ingots.

**Screenshots**
![image](https://user-images.githubusercontent.com/12349921/119279198-74d9a100-bc2a-11eb-8b55-4509f097ce08.png)

**Comment by TemperedFool** [comment] 2021-05-24 15:06
I think this is a dupe of #1975, which spawned https://github.com/BluSunrize/ImmersiveEngineering/issues/4791#issue-861299320. According to that it looks like this was resolved just a few hours ago, so I imagine we'll get the fix whenever IE releases an update.

**Closed** 2021-05-24 15:11 UTC
Labels: Bug
