### ISSUE TITLE
Minecart with chest able to dupe item in it.

### ISSUE THREAD

**Issue by hkpyro08** [NillerMedDild/Enigmatica6#1176] opened 2021-02-01 15:54 UTC
**Modpack version**
0.3.13

**Describe the bug**
Minecart with chest can dupe the item inside it, and I able to take loot inside multiple time

here the video that I upload on YouTube
https://youtu.be/KJ1r2vo3wI0

**Comment by Merlo17** [comment] 2021-02-01 15:55
Duplicate of https://github.com/NillerMedDild/Enigmatica6/issues/1165, thanks for the report though ^^

**Closed by Merlo17** 2021-02-01 15:55 UTC
Labels: Bug, Duplicate

**Comment by hkpyro08** [comment] 2021-02-01 15:57
i forgot to mention that i play LAN with my sister and my sister to can dupe the loot

**Comment by hkpyro08** [comment] 2021-02-01 15:57
i forgot to mention that i play LAN with my sister and my sister to can dupe the loot
