### ISSUE TITLE
Quest Progress not syncing up

### ISSUE THREAD

**Issue by wyt333333** [NillerMedDild/Enigmatica6#899] opened 2021-01-15 16:02 UTC
Started playing modpack with friends and are allies and in the same FTB Team but our quest progress does not link, any suggestions?

**Comment by MuteTiefling** [comment] 2021-01-15 17:11
This feature isn't yet implemented in ftb quests, unfortunately.

**Comment by NillerMedDild** [comment] 2021-01-15 19:39
duplicate of #616

**Closed by NillerMedDild** 2021-01-15 19:39 UTC
