### ISSUE TITLE
Ice And Fire

### ISSUE THREAD

**Issue by YashTFEM** [NillerMedDild/Enigmatica6#3819] opened 2021-12-01 09:21 UTC
### URL

https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons

### Why would you like the mod added?

It's a exploration/boss fight mod that adds a whole bunch of mythical creatures like cyclops, dragons, hydras, etc, tha tyou can fight for amazing loot. There are also some great armor sets and weapons for you to use against these creatures. Its a great mod that adds a lot to the game.

**Comment by NillerMedDild** [comment] 2021-12-01 10:07
Duplicate of #312

**Closed by NillerMedDild** 2021-12-01 10:07 UTC
Labels: Suggestion
