### ISSUE TITLE
Dupe Bug - Astral Crystals + cardboard box

### ISSUE THREAD

**Issue by mcion3** [NillerMedDild/Enigmatica6#2234] opened 2021-05-21 03:01 UTC
I didn't see a post about this one. I had all of my astral items in a Gold Chest (Iron Chests) and I used a cardboard box from mekanism on the chest to move it ad all of the astral crystals and constellation papers spilled out onto the ground. I took off the cardboard box and all of the items were still in the chest. I tried again and every time I used the cardboard box all of the crystals and papers duplicated. I discovered it on v0.4.13 and verified it was still there on the newest version 0.4.14

**Comment by NillerMedDild** [comment] 2021-05-21 04:28
Duplicate of #2132

**Comment by NillerMedDild** [comment] 2021-05-21 04:28
Thanks anyway :)

**Closed by NillerMedDild** 2021-05-21 04:28 UTC
