### ISSUE TITLE
Created/Used Nether Portals in v0.3.0, Updated to v0.3.2 Today - All nether portal functionality now broken.

### ISSUE THREAD

**Issue by Vespor** [NillerMedDild/Enigmatica6#615] opened 2020-12-23 05:56 UTC
**Modpack version**
v0.3.2

**Issue**
When my world was operating under E6 v0.3.0 I was able to build and enter Nether portals. After updating to E6 v0.3.2 today nether portals no longer function (pre-existing and new). I just get an infinite purple swirling animation and the teleport doesn't go through.

**Logs**
No crashes occur, just a failure to teleport.

**Comment by NillerMedDild** [comment] 2020-12-23 06:18
Please read the top of the changelog for 0.3.1 :)
Duplicate of #606

**Closed by NillerMedDild** 2020-12-23 06:18 UTC

**Comment by Vespor** [comment] 2020-12-23 06:23
I assume this is where I should be looking? https://github.com/NillerMedDild/Enigmatica6/blob/master/changelogs/CHANGELOG_MODS_0.3.1.txt

I noticed the other post about the same nether portal issue and saw the same reference to the 0.3.1 changelog, but both times I've read through I haven't seen anything relevant to the nether. Am I looking in the wrong place or just blind?

**Comment by NillerMedDild** [comment] 2020-12-23 06:24
Close :) https://github.com/NillerMedDild/Enigmatica6/blob/master/changelogs/CHANGELOG.md
It's also in the changelog on CurseForge app/website.

**Comment by Vespor** [comment] 2020-12-23 06:40
Aha, thanks for the clarification! Seems like the workaround to patch existing worlds is a bit above my head, but I'll keep the guide bookmarked just in case.

Thanks again!

**Comment by NillerMedDild** [comment] 2020-12-23 06:47
Myeah it's a bit complicated :/ 

You're welcome!
