### ISSUE TITLE
Step assist doesn't work

### ISSUE THREAD

**Issue by taillow40** [NillerMedDild/Enigmatica6#2927] opened 2021-08-08 21:42 UTC
Enigmatica6-0.5.6

No step assist items work
Tested with:
Mekanism mech boots
Astral Sorcery Vicio attunment
Trinkets horseshoe

Turning on and off the disable step assist option from client tweaks doesn't change anything.

**Comment by Darkere** [comment] 2021-08-08 21:46
Duplicate. 

This is caused by environmental and will be fixed in the next update.

**Closed by Darkere** 2021-08-08 21:46 UTC
Labels: Bug
