### ISSUE TITLE
Astral Sorcery serverconfig resets to mod defaults on world start

### ISSUE THREAD

**Issue by eturner** [NillerMedDild/Enigmatica6#3619] opened 2021-10-31 14:17 UTC
### Modpack Version

0.5.17

### Describe your issue.

On loading a world or starting a new one, some parts of astralsorcery.toml from defaultconfig are deemed 'incorrect' according to the logs, and some or all changes from the mods default are discarded. I've been trying to get more than vanilla ores from the mineralis ritual, but the 'registries.mineralis_ritual_ore' line changes back every launch.

I'm relatively new to modded minecraft in general, but this is the first pack I've played beyond 1.12. Serverconfig is new to me, and the addition of configswapper and serverconfigupdater is especially confusing. I can't make mineralis_ritual_ore changes stick. Let me know if it's just me.

This affects new worlds created in fresh instances in both multimc and gdlauncher, with both java 8 and 16

`./latest.log:[31Oct2021 08:21:22.573] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Configuration file /home/turnbomb/.config/gdlauncher_next/instances/Enigmatica 6/saves/Balls/serverconfig/astralsorcery.toml is not correct. Correcting
./latest.log:[31Oct2021 08:21:22.735] [Server thread/WARN] [com.darkere.configswapper.ModeConfig/]: Config Swapper: Error in serverconfig/astralsorcery.toml. Real config does not have an entry called tools.chargedToolsRevert
./latest.log:[31Oct2021 08:21:22.735] [Server thread/WARN] [com.darkere.configswapper.ModeConfig/]: Config Swapper: Error in serverconfig/astralsorcery.toml. Real config does not have an entry called tools.chargedToolsRevertStart
./latest.log:[31Oct2021 08:21:22.735] [Server thread/WARN] [com.darkere.configswapper.ModeConfig/]: Config Swapper: Error in serverconfig/astralsorcery.toml. Real config does not have an entry called tools.chargedToolsRevertChance
./latest.log:[31Oct2021 08:21:22.735] [Server thread/WARN] [com.darkere.configswapper.ModeConfig/]: Config Swapper: Error in serverconfig/astralsorcery.toml. Real config does not have an entry called perks.type.miningsize.chargeCost
./latest.log:[31Oct2021 08:21:22.735] [Server thread/WARN] [com.darkere.configswapper.ModeConfig/]: Config Swapper: Error in serverconfig/astralsorcery.toml. Real config does not have an entry called constellation.mantle.aevitas.chargeCostPerBlock
./latest.log:[31Oct2021 08:21:22.736] [Thread-0/WARN] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Configuration file /home/turnbomb/.config/gdlauncher_next/instances/Enigmatica 6/saves/Balls/serverconfig/astralsorcery.toml is not correct. Correcting
[...]`

[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/7448963/latest.log)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Darkere** [comment] 2021-10-31 14:37
Which config are you changing?

**Comment by Darkere** [comment] 2021-10-31 14:44
Ohhh nvm I see what you are doing.

The new config system is only slightly different. Completely ignore the configswapper folder. That is for changing between normal and expert mode. And generally shouldn't be modified at all by users. 

In 1.13+ forge changed to 2 config folders. The normal one, and a serverconfig folder that is in the world folder of your current save.
All configs can have a default config in the defaultconfigs folder, which will be used when a new config is generated. 

Meaning, if you want to change the astralsorcery serverconfig you need to go to world/serverconfig/astralsorcery.toml and change the values there.


All that said... This change seems like something we should be doing? Anyone know why we don't have all ores in the Mineralis ritual?

**Comment by eturner** [comment] 2021-10-31 15:09
That much I've figured out. I never made any changes to astralsorcery.toml in the first place, but trying to fix the config problem hasn't worked, is what I'm trying to say.

If I copy defaultconfig/astralsorcery.toml, which is exactly the same as in this repository, to world/serverconfig/astralsorcery.toml, the file gets reset on world load. And this apparently happens in every single new world.

1. defaultconfig/astralsorcery.toml gets copied to world/serverconfig, `Loading default config file from path [...] defaultconfigs/astralsorcery.toml`
2. Then it's considered 'not correct' multiple times `Configuration file [...]/serverconfig/astralsorcery.toml is not correct. Correcting`
3. Now it has default settings and only vanilla ores in mineralis

**Comment by Darkere** [comment] 2021-10-31 15:15
Ah I see. Not sure why you modified config/configswapper/normal/astralsorcery.toml then? This might actually be the reason for the behavior you are seeing.

**Comment by eturner** [comment] 2021-10-31 15:28
I hadn't touched that file. I made fresh instances in both gdlauncher and multimc, and even tested with both java 8 and 16 before I made this report. I've been playing with openjdk 16 that I compiled myself with march=native for performance, but I've heard there's some obscure problems with certain mods on java >8. But this happens in java 8 too.

**Comment by Darkere** [comment] 2021-10-31 15:43
The logs you posted indicate that the file has a bunch of stuff in it that shouldn't be there. Can you check the file? It should have like 3 lines in it.

**Comment by eturner** [comment] 2021-10-31 16:18
I may have uploaded the wrong one by mistake. For this one I made yet another new instance of the latest, in multimc, with java 8 on linux. Made a new world, then quit.
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/7449224/latest.log)

configswapper/normal/serverconfig/astralsorcery.toml looks alright. Just 3 lines. I changed literally nothing in this instance. /serverconfig/astralsorcery.toml was still wrong.

**Comment by eturner** [comment] 2021-10-31 17:11
I just found this in the logs, possibly unrelated
`Configuration file [...]/config/astralsorcery-client.toml is not correct. Correcting` 
followed by this line, among others
`Incorrect key rendering.maxEffectRenderDistance was corrected from null to its default, 64.0.`

Even though rendering.maxEffectRenderDistance was actually defined as 64.0 in config/astralsorcery-client.toml

I see no mention of registries.mineralis_ritual_ore being 'corrected' anywhere in the logs, which is why I thought serverconfigupdater or configswapper may be involved somehow

**Comment by Darkere** [comment] 2021-10-31 17:58
The client config is unrelated. I can't reproduce this. Any new worlds I create have the correct configs. Our default config is a bit outdated, but the important bits work just fine. 

A thing to try. I've updated Configswapper today and it changes when the serverconfig will be updated by it slightly. Might be worth a try.

**Comment by NillerMedDild** [comment] 2021-10-31 18:32
I was able to reproduce this, and have tried to regen the file somewhat to fix it.

**Comment by NillerMedDild** [comment] 2021-10-31 18:44
Should be fixed now, at least I can't reproduce it anymore 😄 your current astralsorcery serverconfig will be automatically removed once during the 0.5.18 update.

**Comment by eturner** [comment] 2021-10-31 21:26
Yeah this appears to be fixed for me on the develop branch. Thanks, that was fast lol

**Closed** 2021-11-01 19:12 UTC
Labels: Bug, Status: Fixed In Next Release
