### ISSUE TITLE
Map Crash to Desktop

### ISSUE THREAD

**Issue by DizzyDJW** [NillerMedDild/Enigmatica6#3617] opened 2021-10-31 02:31 UTC
### Modpack Version

0.5.17

### Describe your issue.

Opening map freezes game then crashes to desktop

### Crash Report

https://pastebin.com/BXjD1wDk

### Have you modified the modpack?

Yes

### User Modifications

RFTools Dimensions Re-added

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment] 2021-10-31 13:56
Duplicate of #2922

To fix the crash, delete `/world/ftbchunks` from the server :)

**Closed by NillerMedDild** 2021-10-31 13:56 UTC
Labels: Bug
