### ISSUE TITLE
Iron nuggets/ingots

### ISSUE THREAD

**Issue by Tedy-Play** [NillerMedDild/Enigmatica6#3133] opened 2021-08-30 13:05 UTC
### Modpack Version

0.5.11

### Describe your issue

nine iron nuggets recipe in may create automated ore processing system is not making iron ingots.
It is after the update now making by default icy chains.
I spotted it in may create automated ore processing system's output this is a small thing but it is the kind of thing that is annoying.
it is not a major issue but needs to be dealt white :-)

### Have you modified the modpack?

Yes

### User Modifications

augment waystone wilderness spawn chance from zero to posibel

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by TemperedFool** [comment] 2021-08-30 13:14
Dupe of #3039, fixed in dev.

**Closed by TemperedFool** 2021-08-30 13:14 UTC
Labels: Bug
