### ISSUE TITLE
Quest Rewards: Random Loot/Loot Reward not giving an item

### ISSUE THREAD

**Issue by SpatenWueste252** [NillerMedDild/Enigmatica6#717] opened 2021-01-02 12:26 UTC
**Modpack version**
Enigmatica 6 0.3.2

**Issue**
We are playing on a server and no one gets items from rewards that are "Loot Reward" or "Random Reward"

**Comment by Merlo17** [comment] 2021-01-02 12:40
Known issue, fixed in next release :D

**Comment by NillerMedDild** [comment] 2021-01-02 18:02
Duplicate of #680

**Closed by NillerMedDild** 2021-01-02 18:02 UTC
Labels: Duplicate
