### ISSUE TITLE
End Stone Smelter's GUI is not rendering

### ISSUE THREAD

**Issue by cryoxerxes** [NillerMedDild/Enigmatica6#1484] opened 2021-03-01 06:49 UTC
**Modpack version**
Enigmatica 6 ver. 0.4.0
**Describe the bug**
The Gui for this alloying block is not showing properly and is difficult to use. I have a work around with the crafting station but it's difficult

**Screenshots**
![20210301_004341](https://user-images.githubusercontent.com/79828535/109461112-4f703900-7a27-11eb-8495-cca4b678121f.jpg)

**Comment by Merlo17** [comment] 2021-03-01 08:57
Duplicate of https://github.com/NillerMedDild/Enigmatica6/issues/1426

**Closed** 2021-03-01 08:57 UTC
Labels: Duplicate
