### ISSUE TITLE
Game crashing after updating to 0.2.17

### ISSUE THREAD

**Issue by Earendilgrey** [NillerMedDild/Enigmatica6#301] opened 2020-09-24 04:36 UTC
**Modpack version**
0.2.17

**Issue**
Game crashes without warning.  Has happened multiple times today with the same error code of 0

**Logs**
![Untitled-1](https://user-images.githubusercontent.com/7344454/94101162-fb688500-fdf4-11ea-88df-c98443246b26.jpg)

Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment] 2020-09-24 05:46
We need your crash report please :)

**Comment by Earendilgrey** [comment] 2020-09-24 17:03
I thought I posted it, it must not of loaded up.
[crash-2020-09-23_23.13.39-server.txt](https://github.com/NillerMedDild/Enigmatica6/files/5277879/crash-2020-09-23_23.13.39-server.txt)

**Comment by NillerMedDild** [comment] 2020-09-24 20:22
It seems to be caused by a gravestone at `-19,63,80`

**Comment by Earendilgrey** [comment] 2020-09-24 23:27
Okay, checked that out and there is no gravestone at that location that I can see.  I went to check the nether even just in case and ended up dying (forgot gold armor) and no gravestone popped up there only a map tag saying latest death.

**Comment by NillerMedDild** [comment] 2020-09-25 18:20
Hmm... Is the crash still happening? Could you supply other logs perhaps? :)

**Comment by Earendilgrey** [comment] 2020-09-26 00:39
It was still happening.  But as a test, I started a new world and it is working fine.  The location that was giving the issue was the world spawn so I am wondering if it just wasn't a bug with that world.

**Comment by NillerMedDild** [comment] 2020-09-26 17:25
Alright, well I'm glad it's "fixed" :) I'm closing this for now, but it can always be reopened if you or anyone else experiences the issue.

**Closed by NillerMedDild** 2020-09-26 17:25 UTC
Labels: Bug
