### ISSUE TITLE
Edmentus Enigmatica Silicone: Unable to use for "Refined storage"

### ISSUE THREAD

**Issue by Scorch1977** [NillerMedDild/Enigmatica6#3018] opened 2021-08-16 15:55 UTC
**Description**
I've recently noticed that the "Edmentus Enigmatica" silicone, is unable to create processors from Refined storage, this could be a issue for new players and alike.
**Why would you like this added/changed?**
so that if we tweak the Refined storage, and extra disks mod recipes to be able to use "Edmentus enigmatica" Silicone
Please consider this little tweak for more recipes that need some fixing.

- Tangerine#8230, aka "Scorch1977"

**Comment by theboo** [comment] 2021-08-16 15:57
looks like u noticed this is a duplicate of #2997 , putting this here so other people searching notice

**Closed** 2021-08-16 15:56 UTC
Labels: Suggestion
