### ISSUE TITLE
[ModpackVersion] Short_Bug_Description

### ISSUE THREAD

**Issue by TheOnlyMann** [NillerMedDild/Enigmatica6#2049] opened 2021-04-25 08:38 UTC
**Modpack version**
0.4.8
**Describe the bug**
When equipping a Pneumatic Reforged minigun with a Wither 2 tipped minigun ammo(wither 2 potion comes from apothesis) will permanently disconnect you from the server.
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**
![2021-04-25_17 32 56](https://user-images.githubusercontent.com/82017462/115986823-11d5f980-a5ed-11eb-8047-ab3390627726.png)

**Comment by TheOnlyMann** [comment] 2021-04-25 08:40
[17:38:47] [Render thread/INFO]: Client cache cleared!
[17:38:47] [Render thread/INFO]: Connecting to 63.251.240.58, 25565
[17:38:54] [Render thread/INFO]: Built PerkTree with 417 perks!
[17:38:56] [Render thread/INFO]: Injecting existing registry data into this CLIENT instance
[17:39:13] [Netty Client IO #10/WARN]: Configuration file SimpleCommentedConfig:{tagPreferences=[minecraft, tconstruct, tmechworks, immersiveengineering, mekanism, thermalfoundation, thermalexpansion]} is not correct. Correcting
[17:39:13] [Netty Client IO #10/WARN]: Incorrect key tagPreferences was corrected from [minecraft, tconstruct, tmechworks, immersiveengineering, mekanism, thermalfoundation, thermalexpansion] to its default, [minecraft, tconstruct, tmechworks, immersiveengineering, mekanism, thermalfoundation, thermalexpansion]. 
[17:39:13] [Netty Client IO #10/WARN]: Configuration file SimpleCommentedConfig:{tools=SimpleCommentedConfig:{steel=SimpleCommentedConfig:{steelBootArmor=3, steelAxeAtkSpeed=-3.0, steelToughness=1.0, steelChestplateArmor=7, steelAttackDamage=3.0, steelSwordAtkSpeed=-2.4000000953674316, steelPaxelMaxUses=1750, steelLeggingDurability=600, steelPaxelHarvestLevel=3, steelPaxelDamage=4.0, steelPickaxeDamage=1.0, steelSwordDamage=3.0, steelHoeDamage=-4.0, steelPickaxeAtkSpeed=-2.799999952316284, steelToolMaxUses=1561, steelLeggingArmor=6, steelPaxelEnchantability=14, steelEfficiency=8.0, steelKnockbackResistance=0.0, steelHelmetDurability=440, steelShieldDurability=1792, steelBootDurability=520, steelPaxelAtkSpeed=-2.4000000953674316, steelAxeDamage=1.5, steelShovelDamage=1.0, steelShovelAtkSpeed=-3.0, steelChestplateDurability=640, steelPaxelEfficiency=10.0, steelHelmetArmor=3, steelHarvestLevel=3, steelEnchantability=10, steelHoeAtkSpeed=1.0}, refined_glowstone=SimpleCommentedConfig:{refined_glowstonePaxelAtkSpeed=-2.4000000953674316, refined_glowstoneLeggingArmor=6, refined_glowstoneShieldDurability=806, refined_glowstoneAxeAtkSpeed=-3.0999999046325684, refined_glowstoneHoeAtkSpeed=2.0, refined_glowstoneToughness=0.0, refined_glowstoneHelmetDurability=198, refined_glowstonePickaxeDamage=1.0, refined_glowstonePaxelMaxUses=450, refined_glowstoneSwordAtkSpeed=-2.4000000953674316, refined_glowstoneEnchantability=18, refined_glowstoneChestplateArmor=7, refined_glowstoneHarvestLevel=2, refined_glowstoneShovelAtkSpeed=-3.0, refined_glowstoneHelmetArmor=3, refined_glowstoneToolMaxUses=250, refined_glowstoneHoeDamage=-5.0, refined_glowstonePaxelEfficiency=14.0, refined_glowstoneEfficiency=11.0, refined_glowstonePaxelHarvestLevel=3, refined_glowstoneAxeDamage=1.5, refined_glowstoneBootDurability=234, refined_glowstoneChestplateDurability=288, refined_glowstoneShovelDamage=1.0, refined_glowstonePickaxeAtkSpeed=-2.799999952316284, refined_glowstoneSwordDamage=3.0, refined_glowstoneKnockbackResistance=0.0, refined_glowstonePaxelEnchantability=22, refined_glowstonePaxelDamage=3.0, refined_glowstoneLeggingDurability=270, refined_glowstoneAttackDamage=3.3, refined_glowstoneBootArmor=3}, lapis_lazuli=SimpleCommentedConfig:{lapis_lazuliPaxelHarvestLevel=2, lapis_lazuliPickaxeAtkSpeed=-2.799999952316284, lapis_lazuliShieldDurability=582, lapis_lazuliHelmetArmor=2, lapis_lazuliPaxelDamage=6.0, lapis_lazuliEfficiency=5.0, lapis_lazuliKnockbackResistance=0.0, lapis_lazuliHoeAtkSpeed=-1.0, lapis_lazuliBootArmor=2, lapis_lazuliPaxelEfficiency=6.0, lapis_lazuliPaxelEnchantability=10, lapis_lazuliPaxelAtkSpeed=-2.4000000953674316, lapis_lazuliPickaxeDamage=1.0, lapis_lazuliToolMaxUses=200, lapis_lazuliLeggingArmor=6, lapis_lazuliSwordAtkSpeed=-2.4000000953674316, lapis_lazuliAxeDamage=6.0, lapis_lazuliLeggingDurability=195, lapis_lazuliBootDurability=169, lapis_lazuliShovelDamage=1.5, lapis_lazuliSwordDamage=3.0, lapis_lazuliToughness=0.0, lapis_lazuliAttackDamage=2.0, lapis_lazuliPaxelMaxUses=250, lapis_lazuliHoeDamage=-2.0, lapis_lazuliHarvestLevel=2, lapis_lazuliHelmetDurability=143, lapis_lazuliEnchantability=8, lapis_lazuliChestplateDurability=208, lapis_lazuliAxeAtkSpeed=-3.0999999046325684, lapis_lazuliChestplateArmor=5, lapis_lazuliShovelAtkSpeed=-3.0}, osmium=SimpleCommentedConfig:{osmiumSwordDamage=3.0, osmiumChestplateArmor=5, osmiumPaxelEfficiency=9.0, osmiumEfficiency=6.5, osmiumPickaxeAtkSpeed=-2.799999952316284, osmiumToolMaxUses=500, osmiumShieldDurability=1344, osmiumHarvestLevel=2, osmiumEnchantability=12, osmiumShovelAtkSpeed=-3.0, osmiumHoeDamage=-4.0, osmiumKnockbackResistance=0.0, osmiumPaxelDamage=4.0, osmiumHoeAtkSpeed=1.0, osmiumBootDurability=390, osmiumHelmetDurability=330, osmiumAxeDamage=1.5, osmiumHelmetArmor=3, osmiumShovelDamage=1.0, osmiumAttackDamage=2.2, osmiumPaxelMaxUses=500, osmiumToughness=1.0, osmiumPaxelHarvestLevel=3, osmiumPaxelEnchantability=16, osmiumChestplateDurability=480, osmiumAxeAtkSpeed=-3.0, osmiumPaxelAtkSpeed=-2.4000000953674316, osmiumPickaxeDamage=1.0, osmiumBootArmor=3, osmiumLeggingArmor=6, osmiumLeggingDurability=450, osmiumSwordAtkSpeed=-2.4000000953674316}, refined_obsidian=SimpleCommentedConfig:{refined_obsidianChestplateArmor=9, refined_obsidianAxeDamage=5.0, refined_obsidianPickaxeAtkSpeed=-2.799999952316284, refined_obsidianPaxelHarvestLevel=3, refined_obsidianToughness=3.0, refined_obsidianHoeAtkSpeed=6.0, refined_obsidianAttackDamage=5.0, refined_obsidianSwordAtkSpeed=-2.4000000953674316, refined_obsidianEnchantability=40, refined_obsidianShieldDurability=2240, refined_obsidianAxeAtkSpeed=-2.0, refined_obsidianPaxelDamage=4.0, refined_obsidianPaxelEnchantability=50, refined_obsidianSwordDamage=3.0, refined_obsidianShovelDamage=1.0, refined_obsidianHoeDamage=-10.0, refined_obsidianBootDurability=650, refined_obsidianPaxelEfficiency=13.0, refined_obsidianEfficiency=10.0, refined_obsidianToolMaxUses=2500, refined_obsidianChestplateDurability=800, refined_obsidianLeggingDurability=750, refined_obsidianPickaxeDamage=1.0, refined_obsidianKnockbackResistance=0.10000000149011612, refined_obsidianHarvestLevel=3, refined_obsidianPaxelAtkSpeed=-2.4000000953674316, refined_obsidianBootArmor=4, refined_obsidianHelmetArmor=4, refined_obsidianShovelAtkSpeed=-3.0, refined_obsidianLeggingArmor=7, refined_obsidianHelmetDurability=550, refined_obsidianPaxelMaxUses=2500}, mobArmorSpawnRate=SimpleCommentedConfig:{general=0.03, steel=SimpleCommentedConfig:{chestplateChance=0.5, bootsChance=0.5, leggingsChance=0.5, helmetChance=0.5, swordChance=0.5}, refined_glowstone=SimpleCommentedConfig:{chestplateChance=0.5, bootsChance=0.5, leggingsChance=0.5, helmetChance=0.5, swordChance=0.5}, lapis_lazuli=SimpleCommentedConfig:{chestplateChance=0.5, bootsChance=0.5, leggingsChance=0.5, helmetChance=0.5, swordChance=0.5}, osmium=SimpleCommentedConfig:{chestplateChance=0.5, bootsChance=0.5, leggingsChance=0.5, helmetChance=0.5, swordChance=0.5}, refined_obsidian=SimpleCommentedConfig:{chestplateChance=0.5, bootsChance=0.5, leggingsChance=0.5, helmetChance=0.5, swordChance=0.5}, bronze=SimpleCommentedConfig:{chestplateChance=0.5, bootsChance=0.5, leggingsChance=0.5, helmetChance=0.5, swordChance=0.5}}, bronze=SimpleCommentedConfig:{bronzeToughness=0.0, bronzeBootArmor=2, bronzeHoeAtkSpeed=3.0, bronzeHarvestLevel=2, bronzeChestplateArmor=6, bronzePickaxeDamage=1.0, bronzeAxeAtkSpeed=-3.0999999046325684, bronzePaxelMaxUses=250, bronzeShieldDurability=1568, bronzePickaxeAtkSpeed=-2.799999952316284, bronzeHelmetArmor=3, bronzeAxeDamage=1.5, bronzeToolMaxUses=250, bronzeBootDurability=455, bronzeLeggingArmor=5, bronzePaxelHarvestLevel=3, bronzeKnockbackResistance=0.0, bronzeEfficiency=7.0, bronzeEnchantability=10, bronzeSwordDamage=3.0, bronzeShovelAtkSpeed=-3.0, bronzeChestplateDurability=560, bronzeLeggingDurability=525, bronzePaxelEnchantability=14, bronzeAttackDamage=2.0, bronzeSwordAtkSpeed=-2.4000000953674316, bronzeHelmetDurability=385, bronzeShovelDamage=0.5, bronzeHoeDamage=-6.0, bronzePaxelAtkSpeed=-2.4000000953674316, bronzePaxelDamage=3.0, bronzePaxelEfficiency=9.0}}} is not correct. Correcting
[17:39:13] [Netty Client IO #10/WARN]: Incorrect key tools.bronze.bronzeHoeDamage was corrected from -6.0 to its default, -6.0. 
[17:39:13] [Netty Client IO #10/WARN]: Incorrect key tools.osmium.osmiumHoeDamage was corrected from -4.0 to its default, -4.0. 
[17:39:13] [Netty Client IO #10/WARN]: Incorrect key tools.refined_glowstone.refined_glowstoneHoeDamage was corrected from -5.0 to its default, -5.0. 
[17:39:13] [Netty Client IO #10/WARN]: Incorrect key tools.refined_obsidian.refined_obsidianHoeDamage was corrected from -10.0 to its default, -10.0. 
[17:39:13] [Netty Client IO #10/WARN]: Incorrect key tools.steel.steelHoeDamage was corrected from -4.0 to its default, -4.0. 
[17:39:13] [Netty Client IO #10/INFO]: SERVER CONFIG LOADED
[17:39:13] [Netty Client IO #10/INFO]: Config file changed engineersdecor-server.toml
[17:39:13] [Netty Client IO #10/WARN]: Configuration file SimpleCommentedConfig:{Extraction=SimpleCommentedConfig:{reservoir_chance=0.5, pumpjack_consumption=1024, pumpjack_speed=15, req_pipes=false, pipe_check_ticks=100}, Refining=SimpleCommentedConfig:{distillationTower_energyModifier=1.0, distillationTower_timeModifier=1.0}, Generation=SimpleCommentedConfig:{fuels=[immersivepetroleum:gasoline, 5, 256]}, Miscellaneous=SimpleCommentedConfig:{boat_fuels=[immersivepetroleum:gasoline, 1], autounlock_recipes=true, asphalt_speed=true}} is not correct. Correcting
[17:39:13] [Netty Client IO #10/WARN]: Incorrect key Generation.fuels was corrected from [immersivepetroleum:gasoline, 5, 256] to its default, [immersivepetroleum:gasoline, 5, 256]. 
[17:39:13] [Netty Client IO #10/WARN]: Incorrect key Miscellaneous.boat_fuels was corrected from [immersivepetroleum:gasoline, 1] to its default, [immersivepetroleum:gasoline, 1]. 
[17:39:13] [Netty Client IO #10/INFO]: Connected to a modded server.
[17:39:15] [Render thread/INFO]: Successfully loaded generators
[17:39:15] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:39:21] [Render thread/INFO]: Client cache cleared!

**Comment by MuteTiefling** [comment] 2021-04-25 08:55
Please use pastebin or gist to post logs.

**Comment by TheOnlyMann** [comment] 2021-04-25 09:21
im sorry, i dont know how to use both :(

**Comment by MuteTiefling** [comment] 2021-04-25 09:36
You can just drag the log file into the text area of the issue and it'll do everything for you.

**Comment by TheOnlyMann** [comment] 2021-04-25 09:37
...imafuckingidiot
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6371666/latest.log)

**Comment by NillerMedDild** [comment] 2021-04-25 12:21
Duplicate of #1871

**Closed by NillerMedDild** 2021-04-25 12:21 UTC
Labels: Bug
