### ISSUE TITLE
[Mod Suggestion]  Ice and Fire: Dragons

### ISSUE THREAD

**Issue by docsenf** [NillerMedDild/Enigmatica6#799] opened 2021-01-06 22:52 UTC
Maybe this Mod ?
https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons/

**Comment by Merlo17** [comment] 2021-01-06 22:53
Duplicate of https://github.com/NillerMedDild/Enigmatica6/issues/312 :)

**Closed** 2021-01-06 23:01 UTC
Labels: Duplicate
