### ISSUE TITLE
Obsidian honeycomb has no centrifuge output

### ISSUE THREAD

**Issue by UppityDragon** [NillerMedDild/Enigmatica6#1657] opened 2021-03-11 20:07 UTC
**Modpack version**
0.4.3

**Describe the bug**
Obsidian honeycomb has no centrifuge output in JEI, when placed in a centrifuge it isn't processed and just clogs the input.

**Comment by NillerMedDild** [comment] 2021-03-11 20:09
Duplicate of #1411

**Closed by NillerMedDild** 2021-03-11 20:09 UTC
Labels: Bug
