### ISSUE TITLE
Mod suggestion: Mana and Artifice

### ISSUE THREAD

**Issue by RevenantWendigo** [NillerMedDild/Enigmatica6#486] opened 2020-12-06 04:52 UTC
Ars Magica 2 developer released this a few hours ago. Looks like it has lots of content already. The gist of the mod is crafting spells like Ars Nouveau and doing other magic things. Definitely worth taking a look at imo.

https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice

**Comment by NillerMedDild** [comment] 2020-12-06 05:30
Duplicate of #275 :)

**Closed by NillerMedDild** 2020-12-06 05:30 UTC
