### ISSUE TITLE
Dimensional shards not accepted by RFTools Machine Infuser

### ISSUE THREAD

**Issue by ThreePonies** [NillerMedDild/Enigmatica6#2934] opened 2021-08-09 17:46 UTC
Version:  0.5.9

Diescription:
Emendatus Enigmatica mod dimensional shards are not a valid input for the RFTools Machine Infuser

**Logs**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/61923354/128750321-5b0bba18-5803-4922-ab1d-3dc6e4e30815.png)
![image](https://user-images.githubusercontent.com/61923354/128750385-5edc4e0a-14de-43c1-afcd-802a1a957198.png)
![image](https://user-images.githubusercontent.com/61923354/128750431-8234d34d-de25-48c9-a3a1-6dc05a6ef680.png)

**Comment by theboo** [comment] 2021-08-09 18:12
Known issue, rftools hardcoded that recipe to use their dim shards, there is a recipe to convert ee shards to rftools dim shards for this purpose

**Comment by NillerMedDild** [comment] 2021-08-09 18:21
Duplicate of #1456

**Closed by NillerMedDild** 2021-08-09 18:21 UTC
Labels: Duplicate

**Comment by ThreePonies** [comment] 2021-08-09 18:41
Not sure how I missed that.  I did a search for @rftools dimensional as well as @rftools shard but JEI had no entry.  Additionally, a search for @rftoolsbase (the mod listed for the converted shard) also has no JEI entry.
![image](https://user-images.githubusercontent.com/61923354/128756957-ee04b376-228a-48db-9f75-293ab327badf.png)
![image](https://user-images.githubusercontent.com/61923354/128757017-dca95436-4139-43c6-b17d-1a9d669c3402.png)
![image](https://user-images.githubusercontent.com/61923354/128757092-5bc94f23-7d7b-47de-a6e7-7d566c0fa588.png)

**Comment by NillerMedDild** [comment] 2021-08-09 20:25
That's on me 😄 RFTools Dimensional Shards will be unhidden from JEI as of 0.5.10
