### ISSUE TITLE
Disabled Wormhole Mirror

### ISSUE THREAD

**Issue by EightBitRG** [NillerMedDild/Enigmatica6#1854] opened 2021-03-29 06:53 UTC
After trying to use the wormhole potion or wormhole mirror in the same dimension as another player (which is the main prerequisite to use it) you are kicked from the server immediately

**Comment by Merlo17** [comment] 2021-03-29 06:57
Duplicate of https://github.com/NillerMedDild/Enigmatica6/issues/1150, known issue unfortunately. I believe it should be disabled/there should be a tooltip telling you not to use it however? What pack version are you on?

**Comment by willbattel** [comment] 2021-03-29 07:31
> Duplicate of #1150, known issue unfortunately. I believe it should be disabled/there should be a tooltip telling you not to use it however? What pack version are you on?

I noticed that the warning is only on the potion, and not the mirror. Might save a few headaches by adding the warning to the mirror until it's fixed.

**Comment by EightBitRG** [comment] 2021-03-29 18:01
I'm running on version 0.4.3, I ran it by downloading the curseforge launcher, so there wasn't any warning. Actually, I found my first couple potions inside a naturally generated chest.

**Comment by NillerMedDild** [comment] 2021-03-29 18:44
I added the note and tooltip to the Mirror as well, and disabled it's recipe.

**Closed** 2021-04-21 20:40 UTC
Labels: Mod Issue, Status: Fixed In Next Release, Status: Reported
