### ISSUE TITLE
Iron Ingots have a conflicting recipe making it impossible to autocraft Iron Ingots from them.

### ISSUE THREAD

**Issue by JustJinxed** [NillerMedDild/Enigmatica6#3164] opened 2021-09-03 06:15 UTC
### Modpack Version

0.5.11

### Describe your issue

'Dustrial Decore uses 9 Iron Nuggets to create Wrapped Ice Chains which directly conflicts with the classic 9 nuggets to create an Iron Ingot. One of these recipes should be changed for coherence sake. It confuses Create and Refined Storage patterns leaving us no way to automatically turn nuggets into ingots without smelting them using Tinker's Construct

### Crash Report

no crash

### Latest Log

no log

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by WorldTeacher** [comment] 2021-09-03 06:20
This was already reported, Duplicate of #3039

**Closed** 2021-09-03 06:22 UTC
Labels: Bug
