### ISSUE TITLE
Duplicate Redstone Comparators

### ISSUE THREAD

**Issue by spdkils** [NillerMedDild/Enigmatica6#953] opened 2021-01-18 20:02 UTC
Modpack version
Enigmatica 6 0.3.6

Applying a Redstone Comparator to a blaze spawner doesn't allow it to be toggled. It just dupes the Comparator.

**Comment by NillerMedDild** [comment] 2021-01-18 21:47
Duplicate of #939, believe it or not :P fixed in 0.3.7

**Closed by NillerMedDild** 2021-01-18 21:47 UTC
Labels: Bug
