### ISSUE TITLE
Nether Portal not working in multiplayer

### ISSUE THREAD

**Issue by DragonScale6** [NillerMedDild/Enigmatica6#622] opened 2020-12-23 22:08 UTC
**Modpack version**
0.3.1
**Issue**
Nether Portal not working in multiplayer, after the portal is constructed in multiplayer when you stand in the portal it doesn't take you to the Nether. It just spins.

**Logs**

**Comment by NillerMedDild** [comment] 2020-12-24 07:30
Please read the change log :)
 duplicate of #615

**Closed by NillerMedDild** 2020-12-24 07:30 UTC
