### ISSUE TITLE
Some Emendatus Enigmatica liquids have no recipes

### ISSUE THREAD

**Issue by duck-mon** [NillerMedDild/Enigmatica6#3253] opened 2021-09-16 08:55 UTC
### Modpack Version

0.5.11

### Describe your issue

Emendatus Enigmatica equivalent liquids do not have recipes. Liquids generated from RFtools dimensions run into this problem. Ex. Molten Cobalt, Molten Cloggrum, Molten Froststeel.
Each of the respective liquid containers (Mekanism tanks, buckets, and source blocks) have duplicate entries in the creative menu but is hidden in JEI.
Fluid absorbers from RFtools only accept fluids from Emendatus Enigmatica.
![image](https://user-images.githubusercontent.com/46102557/133581752-efa58a7c-86b1-487d-8b53-77e18d7f00c1.png)
Screenshot shows the different items between the creative window and JEI under the same filter.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment] 2021-09-16 09:06
Duplicate of #3226 I believe

**Comment by NillerMedDild** [comment] 2021-09-16 09:06
Ah wrong one, #3159

**Closed by NillerMedDild** 2021-09-16 09:06 UTC
Labels: Bug
