### ISSUE TITLE
3.2 makes the Crafting station uncraftable

### ISSUE THREAD

**Issue by CjayIsBack** [NillerMedDild/Enigmatica6#602] opened 2020-12-21 22:13 UTC
**Modpack version**
Enigmatica 6 3.2

**Issue**
The Crafting station from the "Crafting Station" mod is uncraftable within the crafting table nor inventory.

**Logs**
no logs
![unknown](https://user-images.githubusercontent.com/52092098/102827027-10769500-439f-11eb-89db-0ba8d0d5d9f0.png)
![unknown2](https://user-images.githubusercontent.com/52092098/102827032-140a1c00-439f-11eb-93a4-5351d12906ab.png)

**Comment by CjayIsBack** [comment] 2020-12-21 23:24
This issue was not present within 3.1

**Comment by NillerMedDild** [comment] 2020-12-22 05:33
Woops, my bad :)

**Comment by Octr** [comment] 2020-12-22 16:05
> This issue was not present within 3.1

I am on 0.3.1 and the issue is also there.
Issue did not exist in 0.3.0

**Comment by Octr** [comment] 2020-12-23 14:46
If anyone is like me and too annoyed by the crafting table not crafting into crafting stations on 0.3.1 and 0.3.2 you can do a quick hotfix 
issue is caused by the forge:workbench tag being added to the base crafting table
you can delete: Enigmatica 6 - E6\kubejs\server_scripts\enigmatica\kubejs\base\tags\items\forge\workbench.js
to remove the tag from it (this file was not present in 0.3.0)

Anything with the forge:workbench tag crafts into the crafting table (such as the crafting tables from byg) which is why this crafting loop now exists.
I'm sure it will be fixed by 0.3.3 otherwise.

(tested in singleplayer and server)

**Comment by Merlo17** [comment] 2020-12-24 13:21
https://www.curseforge.com/minecraft/mc-mods/polymorph

Someone on discord suggested this for recipe conflicts. Now clearly this is something that needs to be fixed by us but maybe it'd be worth including the mod so oversights are at least tollerable until we get to them?

**Comment by Darkere** [comment] 2020-12-24 14:08
It is an option. But it does mean that we will no longer get as many reports about recipe conflicts

**Comment by NillerMedDild** [comment] 2020-12-24 20:15
We already have the Metal Crafting table from Engineer's Decor that can help with this, I'd really prefer not including Polymorph, it feels lazy to add.

**Comment by Merlo17** [comment] 2020-12-25 16:40
I'm not sure what you mean, I'd see it more as a "failsafe" for conflicting recipes we overlooked. We'd still patch them out eventually, but at least there'd be a way for players not to be locked in the meantime. I feel like telling them to use a specific crafting table is worse than having polymorph for that

**Comment by NillerMedDild** [comment] 2020-12-25 19:11
Hmm true, I'll add it :)

**Closed** 2021-01-03 22:28 UTC
Labels: Bug, Status: Fixed In Next Release
