### ISSUE TITLE
serverstarter.jar forge-NONE-NONE failures

### ISSUE THREAD

**Issue by Splutty** [NillerMedDild/Enigmatica6#2801] opened 2021-07-23 07:58 UTC
**Modpack version**
E6 any.

**Describe the bug**
On installation of the E6 server, people get an error that forge-NONE-NONE is not found and the install/start keeps looping without doing anything.

**Cause**
The serverstarter.jar fails to resolve the given installerUrl properly by not following redirects, the given installerUrl results in a "Moved permanently" error, which can get resolved by using a download method that follows HTTP Redirects.

This causes the download of the forge installer to fail, and consequently causes the actual install to fail.

Either the URL needs to be updated to the new location (not ideal) or the serverstarter.jar needs to be changed to actually honour HTTP Redirects.

As reference the same happens with E2E as per https://github.com/NillerMedDild/Enigmatica2Expert/issues/1909 and the Unix shell script if you do not have wget installed. Curl requires the -L flag to resolve HTTP Redirects, otherwise the download will fail, the install will fail, and the script will give useless errors.

**Comment by NillerMedDild** [comment] 2021-07-24 20:02
Thanks for the report.

Curl already uses the -L flag:

https://github.com/NillerMedDild/Enigmatica6/blob/master/server_files/start-server.sh#L29

I have updated the forge link in the server-setup-config.yaml, that should resolve this issue. I was however not able to reproduce i t.

**Comment by Splutty** [comment] 2021-07-24 20:51
Hmm. That's a commit from the 14th, so that'd be.. 0.5.6. So then the only thing left is E2E, I guess, E6 is fixed.

**Comment by NillerMedDild** [comment] 2021-07-25 20:00
Fixed in-dev for E2E :)

**Closed** 2021-07-28 19:41 UTC
Labels: Bug, Status: Fixed In Next Release

**Comment by Shadowgar** [comment] 2021-09-29 05:07
So this just started again. I attempted to install versions 0.5.11, 0.5.13, 0.5.14 and I run into the same issues. When getting to the step of downloading the forge jar, the script errors with java.net.ConnectException: Failed to connect to maven.minecraftforge.net

[https://pastebin.com/0kiACb1h](url)
