### ISSUE TITLE
0.5.9 - Hellshelf and Endshelf recipes missing in JEI

### ISSUE THREAD

**Issue by Trostmm** [NillerMedDild/Enigmatica6#2954] opened 2021-08-11 18:06 UTC
**Modpack version**
0.5.9
**Describe the bug**
The basic Hellshelf and Endshelf recipes are missing in JEI. The items are still craftable if you know the recipe, It just can't be looked up.
**Logs**
n/a

**Screenshots**
![image](https://user-images.githubusercontent.com/10382598/129080544-a9d1ec03-16b4-4adc-a5be-59a5cd173224.png)
![image](https://user-images.githubusercontent.com/10382598/129080570-c53aeb37-f892-441e-8625-fff59cfcbcb8.png)

**Comment by NillerMedDild** [comment] 2021-08-11 18:07
Duplicate of #2928

**Closed by NillerMedDild** 2021-08-11 18:07 UTC
Labels: Bug
