### ISSUE TITLE
Refined Storage Silicon

### ISSUE THREAD

**Issue by Katon152021** [NillerMedDild/Enigmatica6#3033] opened 2021-08-19 02:33 UTC
### Modpack Version

5.10

### Describe your issue

Can't make any processors because the recipe for them calls for the Refined Storage version of silicon as opposed to the Emendus Enigmatica version. See pictures for reference
![2021-08-18_21 30 53](https://user-images.githubusercontent.com/85213540/129998245-f88d8e20-56a8-44c3-8611-560295940d1e.png)
![2021-08-18_21 30 55](https://user-images.githubusercontent.com/85213540/129998248-3774c9da-4f54-4b10-ac9b-f27b3a58d991.png)
![2021-08-18_21 30 59](https://user-images.githubusercontent.com/85213540/129998251-9fd46018-7cde-478e-b45b-0b57c41fc5ef.png)
![2021-08-18_21 31 00](https://user-images.githubusercontent.com/85213540/129998255-1b3ea46f-deb2-4ec5-9f4e-ee7b3093e689.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment] 2021-08-19 02:36
duplicate of #2997 and is fixed in e6 version 0.5.11 which was released today.

**Closed by theboo** 2021-08-19 02:36 UTC
Labels: Bug
