### ISSUE TITLE
Wormhole potion drink crashes game

### ISSUE THREAD

**Issue by Arteneko** [NillerMedDild/Enigmatica6#1150] opened 2021-01-30 19:17 UTC
**Modpack version**

0.3.9

**Describe the bug**

On a two-player LAN game, when the host drinks the wormhole potion from Bountiful Baubles, the game crashes.

**Logs**

See [attached latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5898569/latest.log) file.

**Comment by NillerMedDild** [comment] 2021-01-30 19:17
Thank you for the report, I will investigate the issue.

**Comment by r-mc2** [comment] 2021-01-30 19:47
I can confirm, at least back in v0.3.5, this was a thing as well on dedicated servers so we just stopped using them entirely.

**Comment by NillerMedDild** [comment] 2021-01-30 19:49
I could really use the crash report, that latest.log doesn't really help :/

**Comment by NillerMedDild** [comment] 2021-01-30 19:50
Actually, found this reported issue: https://github.com/CursedFlames/BountifulBaubles/issues/48
Which has the log, so we're good!

**Comment by BlackFlameMN** [comment] 2021-01-31 18:28
this effect also crashes the worm hole mirror the same way when teleporting to other players if you were wondering

**Comment by NillerMedDild** [comment] 2021-02-15 19:36
Tbh I was expecting this to be fixed by now. I can't directly remove the potion, but I've added tooltip and JEI description to it saying not to use it.

**Comment by ochotonida** [comment] 2021-02-17 16:06
This issue seems to be caused by Shrink, not Bountiful Baubles. I've submitted a PR that fixes it (https://github.com/gigabit101/Shrink/pull/16)

**Comment by glentakahashi** [comment] 2021-06-16 01:34
With the update to Shrink, is this fixed? https://github.com/NillerMedDild/Enigmatica6/blob/develop/changelogs/changelog_mods_0.5.0.md#shrink-shrink-1164-107jarshrink-1164-110jar

**Comment by NillerMedDild** [comment] 2021-06-16 18:03
Not sure, we removed the mod though, so... fixed?

**Closed** 2021-06-26 18:47 UTC
Labels: Mod Issue, Status: Fixed In Next Release, Status: Reported
