### ISSUE TITLE
Terrasteel Bee can not free from jar

### ISSUE THREAD

**Issue by krakel** [NillerMedDild/Enigmatica6#3132] opened 2021-08-30 11:26 UTC
### Modpack Version

0.5.11

### Describe your issue

I createt a Terrasteel Bee with the Mana-Infuser. But I can not set these bee on a flower or use the filled jar in a apiary. I got a empty jar but no flying bee.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by krakel** [comment] 2021-08-30 11:28
The Elven Bee works.

**Comment by TemperedFool** [comment] 2021-08-30 11:41
Dupe of #3110. This is fixed in dev (#3116). While we wait for a release, use the Terrestrial Agglomeration Plate instead.

**Closed** 2021-08-30 11:41 UTC
Labels: Duplicate
