### ISSUE TITLE
Impossible to make Nitro Crystal tools.

### ISSUE THREAD

**Issue by sniggyfigbat** [NillerMedDild/Enigmatica6#3289] opened 2021-09-20 18:48 UTC
### Modpack Version

0.5.11

### Describe your issue.

Nitro Crystal appears as an excellent top-tier material in the final Tinker's book, and I can see how to make the parts shown in JEI, but there's no apparent way to make Molten Nitro crystal. It appears to be an unimplemented recipe.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by DarkAngel22579** [comment] 2021-09-20 18:51
Duplicate of https://github.com/NillerMedDild/Enigmatica6/issues/3158

**Closed** 2021-09-20 19:00 UTC
Labels: Bug
