### ISSUE TITLE
Ulteria ritual trait is reversed 

### ISSUE THREAD

**Issue by TheAnimaDust** [NillerMedDild/Enigmatica6#1067] opened 2021-01-26 05:11 UTC
**Modpack version**
0.3.9
**Describe the bug**
The ulteria ritual trait of astral sorcery is expanding range and reducing the effect.

**Screenshots**

**Comment by NillerMedDild** [comment] 2021-01-26 10:05
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment] 2021-01-26 19:29
Are you sure you're on modpack version 0.3.9? This was fixed in Astral Sorcery some time ago.

**Comment by TheAnimaDust** [comment] 2021-01-26 19:47
i updated the modpack then make the crystals to the ritual so i`m pretty sure

**Comment by NillerMedDild** [comment] 2021-01-26 20:02
Alright thanks. They can't reproduce it, I'll try to as well.

**Comment by TheAnimaDust** [comment] 2021-01-26 20:13
i`ll try in single player to see if is a server config problem (my server) or if its the modpack because the server world was created in 3.6 idk if this maybe be the cause of the problem

**Comment by TheAnimaDust** [comment] 2021-01-26 21:07
in single player it work likes its intended so it`s probably a server config or a conflict with the world generated in 3.6

**Comment by NillerMedDild** [comment] 2021-01-26 21:14
I can't even get my Ulteria Attunement Altar set up, so :P

**Comment by TheAnimaDust** [comment] 2021-01-26 21:16
kk just finished reinstalling the server from zero it looks like it`s working fine 
probably some config files corrupting in the middle of the last update

**Comment by NillerMedDild** [comment] 2021-01-26 21:17
Awesome, thanks.

**Comment by TheAnimaDust** [comment] 2021-01-26 21:17
my bad from reporting too soon without testing properly, sorry for yout time but thank for the help.

**Closed by NillerMedDild** 2021-01-26 21:17 UTC
Labels: Mod Issue, Status: Reported

**Comment by NillerMedDild** [comment] 2021-01-26 21:20
I don't expect you to try on a fresh install, no worries :D
I never managed to finish the setup required to test this, would you mind giving me and outline of your steps?

**Comment by TheAnimaDust** [comment] 2021-01-26 21:36
its easy to make the astral setups in creative 
just shift right click the block (crystal collector, attunment altar, ritual altar) with a resonant wand and it will construct the multiblock instantly, you can`t be flying, after that i just setup the relays for the constellations needed and used a domic resonator to see the range, the hard part was to get the right crystal by getting a lot of random ones from the creative tab and cutting them into parts fusing again in the right setup to see if its not the crystal caracteristics that are bugged, it definitly seens like the ritual was a bit too big and too weak for a ritual effect 3 and 0 ritual range but i think its intended
