### ISSUE TITLE
Kicking Players with Java Error (0.2.16)

### ISSUE THREAD

**Issue by JRCLARK25** [NillerMedDild/Enigmatica6#261] opened 2020-09-08 01:13 UTC
**Modpack version**
Enigmatica 6 0.2.16

**Issue**
Kicking users with this error: "[INFO] *username* lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: LazyOptional is empty or otherwise returned null from getValue() unexpectedly"
Started since 0.2.16 update

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5185558/latest.log)

**Comment by NillerMedDild** [comment] 2020-09-08 07:50
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment] 2020-09-08 07:50
I would like the full latest.log please, debug.log if you have it, and latest.log from one client that was kicked.

**Comment by JRCLARK25** [comment] 2020-09-08 22:40
Client Log  [logs.zip](https://github.com/NillerMedDild/Enigmatica6/files/5191476/logs.zip)
Server Logs 
[debug-1.log.gz](https://github.com/NillerMedDild/Enigmatica6/files/5191478/debug-1.log.gz)
[2020-09-08-1.log.gz](https://github.com/NillerMedDild/Enigmatica6/files/5191479/2020-09-08-1.log.gz)
[2020-09-08-2.log.gz](https://github.com/NillerMedDild/Enigmatica6/files/5191480/2020-09-08-2.log.gz)
[debug-2.log.gz](https://github.com/NillerMedDild/Enigmatica6/files/5191481/debug-2.log.gz)

**Comment by Darkere** [comment] 2020-09-08 22:43
The client log indicates that they are missing mods. Are they on the same version as the server?

**Comment by JRCLARK25** [comment] 2020-09-08 22:54
Yes both on 0.2.16

**Comment by JRCLARK25** [comment] 2020-09-08 22:58
[debug-3.log.gz](https://github.com/NillerMedDild/Enigmatica6/files/5191529/debug-3.log.gz)
[2020-09-08-3.log.gz](https://github.com/NillerMedDild/Enigmatica6/files/5191530/2020-09-08-3.log.gz)
We did try to roll back to 0.2.14 which i believe is maybe the latest.log

**Comment by NillerMedDild** [comment] 2020-09-09 21:56
Does it only happen to some, or all players?

**Comment by JRCLARK25** [comment] 2020-09-09 23:12
Happened to 4 out of the 5 that were online. The other player wasn’t near our base. The 4 players kicked were all in the same base. Usually happened when a player was interacting with AE2. When it started kicking a lot one player would log on and it immediately kicked closest player.

John Randall Clark


On Sep 9, 2020, at 4:56 PM, Niels Pilgaard Grøndahl <notifications@github.com> wrote:

﻿

Does it only happen to some, or all players?

**Comment by NillerMedDild** [comment] 2020-09-10 18:26
Interesting. In a bad way ^^'

**Comment by JRCLARK25** [comment] 2020-09-11 02:25
Server Logs:
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5205562/latest.log)
[debug.log](https://github.com/NillerMedDild/Enigmatica6/files/5205563/debug.log)

**Comment by JRCLARK25** [comment] 2020-09-11 02:26
Client
[latest.zip](https://github.com/NillerMedDild/Enigmatica6/files/5205571/latest.zip)

**Comment by JRCLARK25** [comment] 2020-09-11 02:27
Logged in with my Alt and received same error once more of my base-mates logged in.

**Comment by NillerMedDild** [comment] 2020-09-11 12:52
Do you happen to have an Enderman spawner at the base?

**Comment by JRCLARK25** [comment] 2020-09-11 13:13
We do. It is redstone controlable. Will remove it ASAP

**Comment by JRCLARK25** [comment] 2020-09-11 13:36
Will test tonight (in roughly 12 hours).

**Comment by JRCLARK25** [comment] 2020-09-12 05:32
No luck. Will try to pick up all spawners.

**Comment by JRCLARK25** [comment] 2020-09-12 22:35
No luck. 
Still saying same error

**Comment by NillerMedDild** [comment] 2020-09-12 23:01
Dammit, I'll dig deeper through the logs tomorrow :)

**Comment by mfriedrich74** [comment] 2020-09-13 15:35
my small group has that too. it is influenced by where the players are and where they spawn in. It seems to kick out the player in the same chunk, or close to the chunk where the new one spawns in.
It also seem to be related to block updates.

You may need a world copy to reproduce.

**Comment by corhean** [comment] 2020-09-19 22:35
I see fixed in 16.3, do we know the culprit?

**Comment by NillerMedDild** [comment] 2020-09-19 22:37
Nope not at all, not sure what to do here tbh.

**Comment by corhean** [comment] 2020-09-19 22:44
we're near 100% certain its related to the apothesis spawners - after a fresh server restart we only started having issues after using a lever to control spawners that also have the ignore players tag.  I do notice that the spawners record a xyz location for redstone control in the NBT, may also impact usability.  Curiously though we have one player who is consistently not part of the impacted group, even though they have interacted with spawners and are part of the allies group for the claimed areas.

**Comment by corhean** [comment] 2020-09-22 17:54
> my small group has that too. it is influenced by where the players are and where they spawn in. It seems to kick out the player in the same chunk, or close to the chunk where the new one spawns in.
> It also seem to be related to block updates.
> 
> You may need a world copy to reproduce.

we also began experiencing this once players began moving between dimensions using Mekanism portals, It seems specific to some sort of load check when players enter/spawn into the area.

In your world Mike, was it specific to an area, or any areas where certain players loaded?

**Comment by mfriedrich74** [comment] 2020-09-22 18:24
Yes, close to the chunk that had the storage and ME and mekanism machines
(connected to ME). All this is in just 2 or 3 chunks.

**Comment by NillerMedDild** [comment] 2020-10-22 07:32
I think 0.3.0 will fix this, I can't know for sure though since I can't reproduce it ^^'

**Closed** 2020-11-22 19:57 UTC
Labels: Bug, Status: Fixed In Next Release
