### ISSUE TITLE
[Mod Suggestion] Rats

### ISSUE THREAD

**Issue by AbedMir31** [NillerMedDild/Enigmatica6#647] opened 2020-12-26 20:17 UTC
Rats and Ratlantis:
https://www.curseforge.com/minecraft/mc-mods/rats
https://www.curseforge.com/minecraft/mc-mods/rats-ratlantis

**Comment by NillerMedDild** [comment] 2020-12-26 20:40
duplicate of #587

**Closed by NillerMedDild** 2020-12-26 20:40 UTC
