### ISSUE TITLE
Only 1 Gem drops from EE Dimensional Ore

### ISSUE THREAD

**Issue by lamb3664** [NillerMedDild/Enigmatica6#867] opened 2021-01-12 19:13 UTC
**Modpack version**
0.3.5

**Issue**
This never happens in the overworld to my knowledge, but in the Nether and End, both the base RFTools mod's Dimensional Shard Ore and the one added by Emendatus Enigmatica both spawn, even in the same stone types.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment] 2021-01-12 19:42
Duplicate of #822

**Comment by NillerMedDild** [comment] 2021-01-12 19:42
Thanks for the report anyhow :)

**Comment by lamb3664** [comment] 2021-01-12 20:13
You're welcome; tho another thing to note is that the RFTools Dimensional Shard ore drops multiple Dimensional Shards, while the Emendatus Enigmatica one only drops one, making the former more desirable esp. when combined with fortune.

**Comment by NillerMedDild** [comment] 2021-01-12 21:02
@Ridanisaurus Master of EE! It would appear EE Dimensional Shard only drops 1 Gem, 'tis bugged!

**Closed** 2021-01-14 21:39 UTC
Labels: Mod Issue, Status: Fixed In Next Release, Status: Reported
