### ISSUE TITLE
My character's height has decreased after 0.5

### ISSUE THREAD

**Issue by Azelza** [NillerMedDild/Enigmatica6#2545] opened 2021-06-27 03:37 UTC
**Modpack version**

E6 0.5.1

**Describe the bug**

I created my world in 0.4.14. After 0.5 update my character is bugged and my height has decreased and when i sneak my height wont change, i'm always have 1.5 block height and step assist (horse shoe trinket) wont work.

**Screenshots**
![2021-06-27_06 15 55](https://user-images.githubusercontent.com/52320862/123531996-dac9b480-d711-11eb-8f4f-71073f2da172.png)
![2021-06-27_06 19 52](https://user-images.githubusercontent.com/52320862/123531997-de5d3b80-d711-11eb-888c-2747adb27bf2.png)

**Comment by RobuxShooters** [comment] 2021-06-27 04:50
Have you used a shrinking device to shrink yourself before? I remember there was a bug (not sure if it has been fixed) about the player's head height being reduced by 0.5 blocks when teleporting or changing dimensions. You can try shrinking and unshrinking yourself to see if that fixes the problem.

As for step-assist not working, duplicate of issue #2472.

**Comment by Master2Mind88** [comment] 2021-06-27 05:53
E6 0.5.1 Dev

My height has decreased also and I have not used the shrinking device and it is when I died on hardcore and had to create a new world it is there.

**Comment by SirArevacoso** [comment] 2021-06-27 09:58
Have you checked that your character is not sitting?

**Comment by Azelza** [comment] 2021-06-27 14:47
> Have you used a shrinking device to shrink yourself before? I remember there was a bug (not sure if it has been fixed) about the player's head height being reduced by 0.5 blocks when teleporting or changing dimensions. You can try shrinking and unshrinking yourself to see if that fixes the problem.
> 
> As for step-assist not working, duplicate of issue #2472.

I tried shrinking device bug didn't work, and when i shrink myself i cant walk cause im goin in blocks.
And i tried kill myself and teleporting but didn't work too


![2021-06-27_17 43 14](https://user-images.githubusercontent.com/52320862/123548951-a7b60e00-d76f-11eb-9efc-c3d17a45e81f.png)
![2021-06-27_17 43 20](https://user-images.githubusercontent.com/52320862/123548961-adabef00-d76f-11eb-9f3a-0e8223e23838.png)

**Comment by MuteTiefling** [comment] 2021-06-27 16:25
Try this please
- Close the game
- Disable shrink
- Load the game. Crouch, make sure you're back to normal
- Close the game again
- Re-enable shrink
- Load back in and test

That took care of it for me the one time this happened. Hasn't come back.

**Comment by Azelza** [comment] 2021-06-27 18:19
> Try this please
> 
> * Close the game
> * Disable shrink
> * Load the game. Crouch, make sure you're back to normal
> * Close the game again
> * Re-enable shrink
> * Load back in and test
> 
> That took care of it for me the one time this happened. Hasn't come back.

I completely deleted shrink mod and fixed. I didn't re-enable for now cause my friend is streaming in our server for now. I'll try re-enable soon. Thanks for your help!

**Comment by General-Mudkip** [comment] 2021-06-30 23:54
> ![2021-06-27_17 43 14](https://user-images.githubusercontent.com/52320862/123548951-a7b60e00-d76f-11eb-9efc-c3d17a45e81f.png)

Pretty sure this is just an issue with the player's model/viewpoint being so close to the wall that FOV changes will clip into the blocks and show the unrendered regions.

I've been having the same issue for a while now after using the Personal Shrinking Device, but shrinking myself and then unshrinking myself again seemed to fix it. I've noticed that it happens after I've gone below <1 block gaps, such as RS cables. In F5 it looks like the player model is in the swimming mode.

Hope this helps in some way..

**Comment by NillerMedDild** [comment] 2021-07-11 20:05
We continued discussing this here: https://github.com/NillerMedDild/Enigmatica6/issues/2635
Closing this as a duplicate, even though this one was first.

**Closed by NillerMedDild** 2021-07-11 20:05 UTC
Labels: Bug, Status: Ready For Testing
