### ISSUE TITLE
Resourceful Bees Never go Back Into Apiaries (Creative and Survival)

### ISSUE THREAD

**Issue by HoneyBeesAreCool** [NillerMedDild/Enigmatica6#802] opened 2021-01-07 07:17 UTC
**All The Mods 6**
1.3.9b

**Issue**
Resourceful bees never return to apiary after collecting pollen regardless of tier.

**Expected Behavior**
Bees return to apiary and make honeycomb.

**Before I proceed**
Earlier I had made an apiary in a creative world (standard 7x7x6 apiary) it had a tier 4 apiary and an apiary storage block. I imported my bees and they were doing their business. Few hours later I'm on survival, recreate the creative apiary and it doesn't work. I went to the same creative world and recreated the apiary, now it also doesn't work, but the original creative one still does.
**To Recreate**
- Make an apiary.
- Place flowers for whichever resourceful bee you have.
- Import and unlock bee
- Wait for the bee to come out of the apiary and collect pollen.
- This is where the bee refuses to go back into the apiary and endlessly flies around.

**Comment by Merlo17** [comment] 2021-01-07 08:27
I tried that on E6 and it seems to work fine with me. I don't fully understand why you reported a bug for All the Mods in here?

**Comment by NillerMedDild** [comment] 2021-01-07 08:30
This has been fixed in Resourceful Bees, duplicate of #763 
Thanks for the report anywho.

**Closed by NillerMedDild** 2021-01-07 08:30 UTC
