### ISSUE TITLE
Entering commands in chat or command blocks results in temporary lookup or sometimes java becomes unresponsive

### ISSUE THREAD

**Issue by Arcitect-X** [NillerMedDild/Enigmatica6#694] opened 2020-12-30 15:26 UTC
**Modpack version**
Enig 6 0.3.2

**Issue**
While entering commands in chat or a command block sometimes the cursor becomes unresponsive and there is either a delay (where the cursor does not respond and you can not enter any more text 30sec to 1min) or sometimes Java becomes unresponsive and you must close it.     This is occurs in both single player and multiplayer worlds.

**Logs**
[2020-12-29-2.log.gz](https://github.com/NillerMedDild/Enigmatica6/files/5754693/2020-12-29-2.log.gz)
^^^ became unresponsive around 10:30PM

[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5754695/latest.log)
^^^ this one is when there was a 30sec to 1min delay around 10:00am

**Comment by Arcitect-X** [comment] 2020-12-30 20:29
Did a test on 1.16.4 vanilla and the delay doesn't seem to happen, Also tested on Valhelsia 3 1.16.4 and issue does not happen.

**Comment by NillerMedDild** [comment] 2020-12-30 20:36
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment] 2020-12-30 20:39
Would you mind removing FTB Essentials and see if the issue persists?

**Comment by NillerMedDild** [comment] 2020-12-30 20:41
In the `latest.log` a `/reload` was triggered, which was the cause of the freeze/lag.

**Comment by NillerMedDild** [comment] 2020-12-30 20:42
The other log you supplied doesn't seem to have entries after 20:56

**Comment by Arcitect-X** [comment] 2020-12-30 22:39
Ok sure I can try disabling FTB essentials.  20:56 may be the time it happened,  I stopped playing around that time as it had crashed.  Would the server log be of any help?

**Comment by NillerMedDild** [comment] 2020-12-30 22:49
They might, yeah :)

**Comment by Arcitect-X** [comment] 2020-12-30 23:18
[2020-12-29-2.log.gz](https://github.com/NillerMedDild/Enigmatica6/files/5755989/2020-12-29-2.log.gz) server logs
[2020-12-30-1.log.gz](https://github.com/NillerMedDild/Enigmatica6/files/5755991/2020-12-30-1.log.gz)

**Comment by Arcitect-X** [comment] 2020-12-31 00:44
So removing FTB essentials did not change the issue.  I used the  /give [player]     command and java/mc  went to not responding up before I could select the block to give.

**Comment by Arcitect-X** [comment] 2020-12-31 00:47
[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/5756121/latest.log)
The latest log, doesnt seem to be anything in it other then the startup though

**Comment by Dracos99** [comment] 2020-12-31 04:25
i may be able to contribute something to this...
I have the same delay when using the /give command, but removing emojiful-1.16.3-2.1.1 gets rid of the delay
Looking at their issue log, it could possibly be related to https://github.com/InnovativeOnlineIndustries/Emojiful/issues/11

**Comment by stefment** [comment] 2020-12-31 05:00
I also have a delay when using give command but only a few secs. just have to wait

**Comment by NillerMedDild** [comment] 2020-12-31 13:22
@Arcitect-X would you mind removing Emojiful and seeing if that helps? :P

**Comment by Arcitect-X** [comment] 2020-12-31 16:03
Ok ran E6  in single player and w/o emojiful and the issue no longer happens either in chat or in the command block.  good catch @Dracos99

**Comment by KangyKSLG** [comment] 2021-01-06 01:30
Just tested this on our server at Arcitect-X's request and the issue is still there. I saw the status as Fixed in Next Release so thought i'd update as there have beet 2 releases since :)

**Comment by NillerMedDild** [comment] 2021-01-06 16:42
Does it happen with any command, or just /give?

**Comment by Arcitect-X** [comment] 2021-01-06 17:15
any command  that parses the catalog of id's.  for example  /playsound minecraft:block.bell      so when getting to the minecraft part it locks up (you cant move cursor).  The lock up duration is much shorter than before but still an issue

**Comment by NillerMedDild** [comment] 2021-01-06 20:07
I'd say that's normal, lookups in large registries take time.

**Closed by NillerMedDild** 2021-01-06 20:07 UTC
Labels: Bug
