### ISSUE TITLE
[0.5.0] Inconsistent Step-Assist

### ISSUE THREAD

**Issue by Stephen10023** [NillerMedDild/Enigmatica6#2472] opened 2021-06-20 03:15 UTC
### **Modpack version**
0.5.0 Alpha (MultiMc Client)

### **Describe the bug**
Certain items are unable to step-assist in this version of the modpack. Below is a list of items that I have tested in both single and multiplayer worlds. Restarting the client and making new worlds did not alleviate the problem. I have made sure that items with toggleable step-assist was enabled during testing. The *Client Tweaks* mod config for "Toggle Off Step Assist" was disabled, both in game and in files.

**Step-assist *does not* work on:**
* Pneumatic Boots (*PneumaticCraft: Repressurized* | Toggled on and pressure supplied)
* Horseshoe (*Lost Trinkets*)
* Free Runners (*Mekanism* | Toggled on and power supplied)

**Step-assist *does* work on:**
* Sojourner's/Globetrotter's/Planestrider's Sash (*Botania* | Mana supplied)
* Running Shoes (Artifacts | You have to sprint to use it)

**Untested for Step-assist:**
* Mekasuit (*Mekanism* | Module and power needed)

**Comment by RobuxShooters** [comment] 2021-06-20 05:53
Tested the MekaSuit's step assist function and can confirm that it does not work either.

**Comment by NillerMedDild** [comment] 2021-06-20 17:37
Thank you for the report, I will investigate the issue.

**Comment by WindFox** [comment] 2021-06-21 21:55
Take a look at this: https://github.com/team-abnormals/environmental/issues/188

**Comment by Xetaxheb** [comment] 2021-07-20 10:26
This can probably be closed as it should be fixed by https://github.com/team-abnormals/environmental/issues/218 / https://github.com/team-abnormals/environmental/commit/cb3a700faa352d10f9cfc60b2fc1aa9c99768fad

But as of this comment the environmental release hasn't happened; I imagine it will be in next update.

Haven't tested in enigmatica6 myself but if anyone wants to double check that it's what was breaking, just try removing environmental completely.

**Comment by voxelv** [comment] 2021-07-28 02:59
> ...if anyone wants to double check that it's what was breaking, just try removing environmental completely.

Confirmed.

I removed Environmental (`environmental-1.16.5-1.0.0`) from Enigmatica6, and Step-Assist via LostTrinkets' Horseshoe is now working.

**Comment by elbim** [comment] 2021-08-08 09:30
Can confirm that updating to environmental-1.16.5-1.1.0 and abnormals_core-1.16.5-3.2.0 (dependency) fixes the problem at least for the mekanism free runners. I didn't test the other items, but the underlying issue should probably be fixed as well for them.
Due to updating the mod some changes have to be done elsewhere as KubeJs is reporting errors now:
`[11:25:06] [ERR ] server_scripts:enigmatica/kubejs/base/unification/unify_growables.js:137: Failed to create recipe for type 'botanypots:crop': {"item":"environmental:rice"} is not a valid ingredient!
[11:25:06] [ERR ] server_scripts:enigmatica/kubejs/base/unification/unify_growables.js:233: Failed to create recipe for type 'thermal:insolator': Item.of('environmental:rice').chance(2.0) is not a valid result!`

**Closed** 2021-08-14 19:39 UTC
Labels: Status: Reported, Status: Fixed In Next Release, Mod Issue
