### ISSUE TITLE
Biomes seem to be swapped around after the update

### ISSUE THREAD

**Issue by HaxtonSale1** [NillerMedDild/Enigmatica6#1146] opened 2021-01-30 09:45 UTC
**Modpack version**
0.3.11 (updated from 0.3.8)

**Describe the bug**
As title; No blocks has been changed, biome boundaries are seem to be as before, but the biome names and grass colors are different
My base was in Prairie biome before the update, now it is in Orchard; Any type of "Clearing" biome seem to have became Polluted Lake; etc.
Unlike #1105 compass works correctly (ie, it points to the changed biome)

**Screenshots**
Before: 
![2021-01-30_18 34 48](https://user-images.githubusercontent.com/13237198/106353081-583bf500-632b-11eb-866b-6492e4525acc.png)

After:
![2021-01-30_18 44 42](https://user-images.githubusercontent.com/13237198/106353087-5eca6c80-632b-11eb-90c3-56fcc4270607.png)

**Comment by NillerMedDild** [comment] 2021-01-30 19:19
Thanks for the report. I can't reproduce this, it didn't happen in any of my test worlds :/ But one such issue has been present in Forge, it was only very recently fixed.

Did you add any mods to the pack?

**Comment by TheCurle** [comment] 2021-01-30 19:34
:concern: 
This should have been fixed in [36.0.2](https://github.com/MinecraftForge/MinecraftForge/commit/50d75a27e1e8ff94797fecae29c2f18d4503f0d4). 
Do you have a backup of your world pre-swap, and can you upload it to mega or google drive or something for further investigation?

**Comment by HaxtonSale1** [comment] 2021-01-30 22:05
> Did you add any mods to the pack?
I added AE2, then removed it after

> Do you have a backup of your world pre-swap, and can you upload it to mega or google drive or something for further investigation?
https://mega.nz/file/CmQDyKjB#MMR7o2SrU35AQSDClExsPBNRyUEk8okDRKCNbLBIdZU
I made this save in 0.3.5, might be old save weirdness

> This should have been fixed in 36.0.2.
I'll try updating forge, because I forgot to do that when I updated that save

**Comment by NillerMedDild** [comment] 2021-01-30 22:13
How are you downloading/updating the modpack? The CurseForge App updates Forge for you :)

**Comment by HaxtonSale1** [comment] 2021-01-30 22:15
I use multiMC, so I have to manually update

**Comment by NillerMedDild** [comment] 2021-01-30 22:20
I don't think updating Forge now will fix your biomes, you will most likely also have to load the backup, just so you know :)

**Comment by HaxtonSale1** [comment] 2021-01-30 22:34
> I don't think updating Forge now will fix your biomes

No, it didn't :(

**Comment by NillerMedDild** [comment] 2021-02-01 04:56
Any update on this? :)

**Comment by HaxtonSale1** [comment] 2021-02-01 08:04
Nope, tried 36.0.10 and 36.0.13 on E6 0.3.13, both didn't fixed that

**Comment by NillerMedDild** [comment] 2021-02-01 14:40
- With the backup?

**Comment by HaxtonSale1** [comment] 2021-02-01 14:40
yep

**Comment by NillerMedDild** [comment] 2021-02-01 17:42
Hm I'm sorry to hear that :/ I'm afraid there's not much I can do tbh.

**Closed** 2021-02-02 21:35 UTC
Labels: Bug
