### ISSUE TITLE
broken in linux and BSD

### ISSUE THREAD

**Issue by korncola** [NillerMedDild/Enigmatica6#3225] opened 2021-09-12 11:11 UTC
### Modpack Version

0.5.11

### Describe your issue

*  linux scripts rely on powershell (wtf!)
* syntax error in if statements (unary operator expected)
* ping probes to goggle etc needs to be cancelled with ctrl-c
** hint: in linux ping runs indefenitly when you dont give the argument -n<times to run ping> 
* eula.txt does not get created
* some files cannot be found

seems like this modpack is for windows servers only

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment] 2021-09-12 12:04
Thanks for the report.

- When you say BSP, is it [this?](https://en.wikipedia.org/wiki/Berkeley_Software_Distribution)
- Which script(s) did you run?
- 
>  linux scripts rely on powershell (wtf!)

What's wrong with that? Powershell is compatible with Linux operating systems with Powershell Core.

> syntax error in if statements (unary operator expected)

The exact error would be very helpful

> ping probes to goggle etc needs to be cancelled with ctrl-c
** hint: in linux ping runs indefenitly when you dont give the argument -n

I was made aware of this issue in the `start-automated-server.sh` script, and it has been fixed in-dev, the fix will be released with update 0.5.12

> eula.txt does not get created

I am unable to reproduce this issue, do you get any error messages indicating what went wrong?

> some files cannot be found

The exact error would be helpful

**Comment by WorldTeacher** [comment] 2021-09-12 12:05
I'm running my Enigmatica6 Server on Linux Server just fine.
The script relying on Powershell might bother some, but why would you create a new script when a working one already exists (my opinion)

> ping probes to goggle etc needs to be cancelled with ctrl-c
this has never happened on my end, but i don't know enough about linux to say that it might be your system only
> eula.txt does not get generated
for me, the script says to write TRUE in the command line, afterwards the installation continues
> some files cannot be found
is your install correct, maybe some things didn't download correctly?

**Closed** 2021-09-19 12:38 UTC
Labels: Bug, Status: Awaiting Information
