### ISSUE TITLE
[0.4.8] T1 Beehive fewer combs at honey level 5

### ISSUE THREAD

**Issue by anivlys** [NillerMedDild/Enigmatica6#1950] opened 2021-04-09 07:23 UTC
**Modpack version**
0.4.8
**Describe the bug**
When a Beehive goes from Honey Level 4 to Honey Level 5 it gives fewer honeycombs than before.

**Screenshots**

![2021-04-09_03 14 56](https://user-images.githubusercontent.com/41839144/114143940-c3351980-98e2-11eb-9ced-e4e2ddd0e23f.png)
![2021-04-09_03 18 56](https://user-images.githubusercontent.com/41839144/114143966-c9c39100-98e2-11eb-9f00-f0806d9f95fa.png)
![2021-04-09_03 15 03](https://user-images.githubusercontent.com/41839144/114143972-cc25eb00-98e2-11eb-817c-6652b4fdc58e.png)
![2021-04-09_03 16 44](https://user-images.githubusercontent.com/41839144/114143977-cdefae80-98e2-11eb-9678-f51bd8f61fc8.png)

**Comment by NillerMedDild** [comment] 2021-04-09 18:18
Thanks for the report!

Have you checked that this is not just The One Probe seeing it incorrectly?

**Comment by anivlys** [comment] 2021-04-09 21:00
When harvested by both dispenser and using shears myself I only received two honeycombs.

**Comment by Leftoveru** [comment] 2021-04-10 00:16
can also confirm this happening in my world.

**Comment by NillerMedDild** [comment] 2021-04-10 20:55
I can't reproduce this consistently, I could only get it to happen once :/

**Comment by NillerMedDild** [comment] 2021-04-11 18:11
It will be fixed in the next RB update \o/

**Closed** 2021-04-21 20:40 UTC
Labels: Mod Issue, Status: Fixed In Next Release
