### ISSUE TITLE
Out of memory Issue with Ars Nouveau Position Setting Wand (on server)

### ISSUE THREAD

**Issue by DClarkyd** [NillerMedDild/Enigmatica6#2271] opened 2021-05-25 20:42 UTC
Enigmtic6-0.4.12

I was playing on a server and created the Ars Nouveau wand that lets you set the position(I can't remember the name). I set the position a couple of times and the server crashed due to an out of memory issue. I reproduced this issue twice.

**Comment by NillerMedDild** [comment] 2021-05-25 20:43
Thanks for the report! Could you please provide the crash report? :)

**Comment by NillerMedDild** [comment] 2021-05-27 20:13
@baileyholl I've had two reports of the AN Position Wand causing memory leaks when used, could you perhaps investigate? :) 

- I hope you don't mind being pinged like this 😄

**Comment by baileyholl** [comment] 2021-05-27 21:38
Ive not touched the wand, or its related connection systems, since December. I need a bit more context and logs, like what is actually being connected, etc.

This looks a bit like the issue long ago where the world worker threads were just vanishing, and what caused a crash was the Mana Condenser checking that a given position in the world was chunk loaded. The chunk threads were all locked up from some other issue, and this caused the crash.
Could this be a related issue only being caused by the Mana Relays checking that the position is loaded before spawning particles?

Ive been playing around in a server world for a bit, spamming the wand, connecting carbuncles and relays all around etc. The server memory usage looks consistent and unchanged. 

I can't do much without any additional info, or knowing what they are actually using.

Some things I would check: 
run /forge entity list and check that there are not a massive amount of entities spawned
Check any relays on the server that may be sending between unloaded chunks

**Comment by NillerMedDild** [comment] 2021-05-28 05:20
Additional info is in this issue: https://github.com/NillerMedDild/Enigmatica6/issues/2281 - I think I may have pinged you in the wrong place ^^'

**Comment by NillerMedDild** [comment] 2021-05-28 05:20
Alright this issue was first I'm going to close it and continue in #2281 as it has more info.

**Closed by NillerMedDild** 2021-05-28 05:20 UTC
Labels: Duplicate
