### ISSUE TITLE
Construction Wands place ghost/unrendered Chisel blocks

### ISSUE THREAD

**Issue by tiwuno** [NillerMedDild/Enigmatica6#3234] opened 2021-09-13 02:52 UTC
### Modpack Version

0.5.11

### Describe your issue

Construction Wands place ghost/unrendered Chisel blocks when building several blocks at a time, only the block that is right-clicked on is rendered correctly.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment] 2021-09-13 03:42
duplicate of https://github.com/NillerMedDild/Enigmatica6/issues/3130

add connectivity-2.2-1.16.5.jar to the server to fix for now, will be fixed in e6 version 0.5.12

https://www.curseforge.com/minecraft/mc-mods/connectivity/files/3360927

**Closed** 2021-09-13 03:43 UTC
Labels: Duplicate
