### ISSUE TITLE
Refined Storage Patterns Missing

### ISSUE THREAD

**Issue by ItsChase7** [NillerMedDild/Enigmatica6#3834] opened 2021-12-02 22:45 UTC
### Modpack Version

0.5.21

### Describe your issue.

I was crafting the ultimate induction cell with refined storage, and I left it for a couple minutes it crashed, then when I load it back up everything is fine, but when i look through the crafting monitor it was just stuck on 80% not moving, and when I look into my netherite crafter all my patterns are gone, pls help. I will show picture
![2021-12-02_17 39 43](https://user-images.githubusercontent.com/84806565/144515111-51b2e256-6963-4eb6-bd41-ce961167c5d9.png)
re

### Have you modified the modpack?

Yes

### User Modifications

I have added mob grinding and optifine

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment] 2021-12-03 08:51
Duplicate of #3076 
I recommend you load a recent backup if the Crafter is a big loss :)

**Closed** 2021-12-03 08:52 UTC
Labels: Duplicate
