### ISSUE TITLE
exiting singleplayer worlds opens multiplayer browser

### ISSUE THREAD

**Issue by BlackFlameMN** [NillerMedDild/Enigmatica6#1318] opened 2021-02-15 18:20 UTC
this happens in every version ive played. every time i save and exit to the main menu it takes me to the multiplayer selet screen instead. pretty minor thing but kind of weird and very consistent.

**Comment by NillerMedDild** [comment] 2021-02-15 18:20
duplicate of #1079

**Closed by NillerMedDild** 2021-02-15 18:20 UTC
Labels: Bug
