### ISSUE TITLE
Two By Two Advancement Showing Strange Results

### ISSUE THREAD

**Issue by zedekblue** [NillerMedDild/Enigmatica6#3173] opened 2021-09-04 19:53 UTC
### Modpack Version

0.5.11

### Describe your issue

I have been working on the breeding & taming advancements and noticed some... strange progress in the advancements tab, which is all I really have to go off of for progress.
![Capture](https://user-images.githubusercontent.com/17040113/132106279-22b2f494-962b-4b68-9fa9-058a10025484.PNG)
As you can see, I have bred 44, yet it only counts 41. Furthermore, it shows 11 remaining, yet only 10 left until 51.

To make matters more complicated, as you can see in [The Spreadsheet I've made,](https://docs.google.com/spreadsheets/d/1xmT22Dc4zi0rOvUgPzFrbl4Zpvq8cOkdKrZ00W9d1Vo/edit?usp=sharing) I have successfully bred 7 additional mobs which did not count towards this advancement.

My question is:
Is this list autogenerated or manually created? Is this behavior intentional, with some mobs left out?
Can you confirm if those 7 mobs _should_ have counted or not?
Considering this is an official e6 challenge quest I am having a difficult time finding anyone else who has any information on completing it.

Regardless, I thought you should know this is happening in case it needs to be fixed.
Thank you!

### Have you modified the modpack?

No

### User Modifications

Server has been updated from 0.5.9 -> 0.5.10 -> 0.5.11 in case that may be a contributing factor.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment] 2021-09-04 19:57
Thanks for the report! @ochotonida do you have any light to shed on this? :)

**Comment by ochotonida** [comment] 2021-09-05 11:55
Thanks for the very detailed report, the spreadsheet helped a lot :).

The lists of mobs that count towards the taming & breeding advancements are manually maintained, so there's always a possibility I missed something. From the 7 mobs you couldn't get to count, cockroach is the only one that should have counted. Tarantula hawk breeding isn't possible to detect afaik, so I can't add that one to the advancement. The other 5 simply weren't added to the list. The book from Alex's Mobs doesn't mention breeding for 4 of these, so I'm not surprised I missed them.

The incorrect count is caused by environmental. Its mobs currently don't actually count toward the advancement despite showing up in the list, this is also fixed in my PR.

**Comment by zedekblue** [comment] 2021-09-05 13:17
> From the 7 mobs you couldn't get to count, cockroach is the only one that should have counted. 
I retried, and looks like it worked. Maybe it doesn't like cockroaches spawned from a mob duplicator, or maybe I killed them too soon afterwards, I dunno.

> The book from Alex's Mobs doesn't mention breeding for 4 of these, so I'm not surprised I missed them.
I was pretty surprised they were breedable, myself. I started just trying to feed everything after a while.

> The incorrect count is caused by environmental. Its mobs currently don't actually count toward the advancement despite showing up in the list, this is also fixed in my PR.
Thank you for your work!

I'll go ahead and close since the PR should resolve the actual issue. (even though I still have yet to find the last 2 breedables... 😭)

**Comment by MuteTiefling** [comment] 2021-09-05 13:54
We leave them open until the update containing the fix is released.

**Closed** 2021-09-24 19:32 UTC
Labels: Bug, Status: Fixed In Next Release
