### ISSUE TITLE
Indefinite Duplication with Dank/Null and unlimited XP using insightful crystal.

### ISSUE THREAD

**Issue by brickdrums** [NillerMedDild/Enigmatica6#2218] opened 2021-05-19 07:24 UTC
**Modpack version**
0.4.13
**Describe the bug**
You can use danks to duplicate stackable items indefinitely by placing two of an item in a dank and clogging up your inventory
then ctrl right clicking the item you want to duplicate that is inside the dank

Everytime you use xp you have to keep insightful crystal on your hand while doing it and after spending your xp QUICKLY
shift right click with the insightful crystal

**Comment by NillerMedDild** [comment] 2021-05-19 07:25
Thanks for the report, I'll investigate :)

Part 2 is a duplicate of #1938

**Comment by brickdrums** [comment] 2021-05-19 08:06
Great!
also about #1938, i didnt really know about that issue being reported so i included both, thanks for the response!

**Comment by NillerMedDild** [comment] 2021-05-19 18:15
It is indeed Inventory Essentials. I have disabled it's ctrl-click functionality to fix this, and #1864

**Closed** 2021-05-20 17:33 UTC
Labels: Mod Issue, Status: Fixed In Next Release
