### ISSUE TITLE
[0.4.8] Missing Soapstone recipes

### ISSUE THREAD

**Issue by Lyx2k** [NillerMedDild/Enigmatica6#1988] opened 2021-04-14 22:37 UTC
Screenshot from E6 0.4.8
![grafik](https://user-images.githubusercontent.com/29131229/114788607-0cbdb280-9d82-11eb-993f-bf76120a75e5.png)

The soapstone is missing some recipes. In another custom modpack instance soapstone comes with this recipes.
Screenshot custom pack:
![grafik](https://user-images.githubusercontent.com/29131229/114788744-50182100-9d82-11eb-90d5-52ccd3e7a48f.png)

The BYG versions are both the same.

But maybe instead of adding the default behaviour it could be cooler to add default stone type recipes for soapstone. Like 2x2 soapstone for polished soapstone. The default stair recipe for soapstone and polished soapstone.

Greetz

**Comment by NillerMedDild** [comment] 2021-04-15 06:24
Duplicate of #1911

**Closed by NillerMedDild** 2021-04-15 06:24 UTC
Labels: Bug
