### ISSUE TITLE
Modular Router Placer Conflict with Claimed Chunks

### ISSUE THREAD

**Issue by MFWalter** [NillerMedDild/Enigmatica6#2838] opened 2021-07-29 05:31 UTC
**Modpack version**
0.5.6

**Describe the bug**
When a modular router with a placer module is placer in a claimed chunk it will not place. The player has verified that fake players are allowed in the FTB teams settings. The player unclaimed the chunk and the router placed blocks correctly. When the chunk was claimed again the router stopped placing blocks.

**Comment by NillerMedDild** [comment] 2021-07-29 18:29
Relayed to the mod devs, thanks for the report!

**Comment by NillerMedDild** [comment] 2021-07-30 06:17
Would you mind updating to 0.5.8 and see if the issue persists?

**Comment by ThreePonies** [comment] 2021-07-30 07:04
Due to scheduling by streamers, we won't be able to update until very late Sunday or sometime Monday but after that, will verify if the issue is resolved or still exists.

**Comment by NillerMedDild** [comment] 2021-07-30 08:25
Appears to be fixed in 0.5.8 :)

**Closed by NillerMedDild** 2021-07-30 08:25 UTC
Labels: Mod Issue, Status: Fixed In Next Release
