### ISSUE TITLE
Chisel & Bits has buggy display and affected items seem to switch textures/item IDs with other blocks whenever modpack is updated

### ISSUE THREAD

**Issue by toothmonsterr** [NillerMedDild/Enigmatica6#1092] opened 2021-01-27 05:40 UTC
*0.3.10**

**Describe the bug**
Buggy display:
Items chiseled or bitsawed will frequently have no inventory icon, or the icon/in-hand model will flicker in and out of existence. Block placement is very difficult as the overlay for placement doesn't properly appear most of the time, and scrolling to rotate does not function as intended.

Replaced by other blocks:
When updating from 0.3.7 to 0.3.8, items I sawed from Mangroove Logs become Palo Verde Leaves sawed blocks. When updating from 0.3.8 to 0.3.10, the replaced Mangroove Logs became Redwood Logs, and Slate Bricks I had also sawed instead used the texture of Slate Brick Stairs, causing a strange skewed effect.

**Comment by NillerMedDild** [comment] 2021-01-27 20:02
Part two is a duplicate of #1086 
Will look into part 1 :)

**Comment by NillerMedDild** [comment] 2021-01-27 21:44
I couldn't reproduce issue 1, are you using Optifine?

**Comment by toothmonsterr** [comment] 2021-01-27 21:49
I'm not, no.
If it helps, I've only used the bitsaw and on modded blocks. Rainbow Eucalyptus Logs, Mangrove Logs, and Slate Bricks.

**Comment by toothmonsterr** [comment] 2021-01-27 21:54
[Here's a video of the issue.](https://www.dropbox.com/s/wpwfy3c4cz83vfb/jan-27-2021%2016-53-07.mp4?dl=0)

**Comment by NillerMedDild** [comment] 2021-01-27 22:05
Heh that was very easy to reproduce now, thanks :D will relay

**Closed** 2021-03-21 20:42 UTC
Labels: Mod Issue, Status: Fixed In Next Release
