### ISSUE TITLE
Sophistcated backpacks/Inventory tweaks upgrade duplication bug

### ISSUE THREAD

**Issue by Glogiator** [NillerMedDild/Enigmatica6#676] opened 2020-12-29 13:25 UTC
**Modpack version**
0.3.2

**Issue**
Can duplicate upgrades using Inventory tweaks' middle click sorting

Steps to reproduce:
1. Open backpack.
2. Put upgrade into upgrade slot.
3. Sort backpack with Inventory tweaks.
4. Repeat steps 2 and 3.

**Comment by NillerMedDild** [comment] 2020-12-29 18:42
duplicate of #645, thanks though :)

**Closed by NillerMedDild** 2020-12-29 18:42 UTC
Labels: Duplicate
