### ISSUE TITLE
Uraninite 

### ISSUE THREAD

**Issue by framundahcheese** [NillerMedDild/Enigmatica6#1666] opened 2021-03-12 17:09 UTC
**Description**
In the Powah mod you can make uraninite crystals for the reactor. I was gifted blocks of uraninite (9 crystals together like ingot blocks) and there is no way to get it back to its crystal form.  It just tells me the ore is removed and you need to get it from the mod pack.

![2021-03-12_11 07 58](https://user-images.githubusercontent.com/80524425/110973788-50587300-8323-11eb-8f1d-f62f10d7c223.png)

**Comment by Halfdeaf** [comment] 2021-03-12 18:29
Duplicate of #1546

**Closed** 2021-03-12 18:49 UTC
Labels: Suggestion
