### ISSUE TITLE
Crafting Raw Bacon Voids Filet Knives

### ISSUE THREAD

**Issue by Figulus88** [NillerMedDild/Enigmatica6#514] opened 2020-12-12 11:47 UTC
**Modpack version**
0.3.0

**Issue**
When crafting Simple Farming's Raw Bacon from a Raw Porkchop, using a Filet Knife from Aquaculture 2 (tested with wood, stone, iron, gold, and diamond variants), the knife is voided in the process.

**Logs**
N/A

**Comment by NillerMedDild** [comment] 2020-12-12 18:46
duplicate of #428, has been fixed and will be a part of 0.3.1 :) thanks for the report!

**Closed by NillerMedDild** 2020-12-12 18:46 UTC
