### ISSUE TITLE
Apotheosis Spawners are Overpowered

### ISSUE THREAD

**Issue by lunulu** [NillerMedDild/Enigmatica6#963] opened 2021-01-19 18:36 UTC
**Modpack version**
0.35

Apotheosis mob spawners are too strong imo.

![2021-01-19_21 33 31](https://user-images.githubusercontent.com/65171793/105077797-147cfc00-5a9e-11eb-81c7-ffbf9c7151b9.png)

**Comment by NillerMedDild** [comment] 2021-01-19 18:54
What did you put in the spawner? O_o

**Comment by lunulu** [comment] 2021-01-19 19:33
Wither Skeletons. I had 7k heads before wither auto-farm

**Comment by lunulu** [comment] 2021-01-19 19:37
And I also have 300k rotten flesh, 30k blaze rods, 20k ender pearls, 40k spider web. It is completely broken.

**Comment by Thiana** [comment] 2021-01-19 19:45
And how long did it take to collect those items? If it was hours then definitely OP, but days+ and it's no different than any other mob spawning machinery.

**Comment by MuteTiefling** [comment] 2021-01-19 19:55
Max speed with a high number of spawns per actin.... You can see thousands of mobs per minute. At that point its just a question of moving items fast enough.

And speeding it up only costs sugar, so...

**Comment by Thiana** [comment] 2021-01-19 20:02
If you are able to get thousands of mobs per minute then something definitely needs tweaking because that will just kill most servers.

**Comment by lunulu** [comment] 2021-01-19 20:03
> And how long did it take to collect those items? If it was hours then definitely OP, but days+ and it's no different than any other mob spawning machinery.

Exactly one night. 
79 clocks + sugar = crazy spawner
crazy spawner + mob crusher = the craziest farm potential

**Comment by lunulu** [comment] 2021-01-19 20:09
Btw, I've bought by accident a sword from a Wandering Trader for 40 emeralds  with Sharpness 5, Luck 3, Unbreaking 3 and Vorpal 3. I think it's broken too.

**Comment by NillerMedDild** [comment] 2021-01-19 20:17
The spawner needs nerfing for sure, we'll get on that.

**Comment by Thiana** [comment] 2021-01-19 20:56
The problem isnt being able to speed up the spawners, the problem is how far you can do so. Instead of completely nuking the ability to change the spawner stats, changing ` I:max_value=99999` to something reasonable like 8-12 might be better.

**Comment by Thiana** [comment] 2021-01-19 20:59
Ideally the values should be benchmarked against the IF spawners so the spawn rates and speeds are similar for fully upgraded builds.

**Comment by NillerMedDild** [comment] 2021-01-19 21:01
You can still change stats, just not min/max delay, which seems to be where the bulk of the issue lies. Seeing as Apotheosis spawners are essentially free, I think it's fair to remove the delay change.

**Comment by lunulu** [comment] 2021-01-19 21:43
Short demonstration.

https://youtu.be/yjs2mGVmwLk

**Closed** 2021-01-20 21:41 UTC
Labels: Bug, Status: Fixed In Next Release
