### ISSUE TITLE
crafting farmland dupe

### ISSUE THREAD

**Issue by FastHit** [NillerMedDild/Enigmatica6#1115] opened 2021-01-28 13:38 UTC
**Modpack version**
0.3.10

**Describe the bug**
crafting dirt/rich soil to farmland in RS crafting grid does not consume the dirt/rich soil if not using shift click.
in other words, if you shift click to craft it it works fine, but if you normal click it, it does not consume the dirt/rich soil as well of not using durability on the hoe, but still gives you the farmland

there is a video showing the dupe.(the video shows only rich soil but works the same for dirt and probably for any other varient of farmland)
https://imgur.com/a/LM7uNLE

**Comment by Darkere** [comment] 2021-01-28 13:46
Duplicate of #920 

Fixed for RS 1.9.12 whenever that gets released.

**Closed by Darkere** 2021-01-28 13:46 UTC
Labels: Bug
