### ISSUE TITLE
0.4.7 Worn Notebook - Many entries broken and showing 2d cubes

### ISSUE THREAD

**Issue by Trostmm** [NillerMedDild/Enigmatica6#1826] opened 2021-03-27 01:56 UTC
0.4.7

Worn notebook from Ars Nourveau has many broken entries. Shows only 2d cubes.

![image](https://user-images.githubusercontent.com/10382598/112706956-15efe980-8e7e-11eb-8974-a5068a62d4bc.png)

**Comment by Trostmm** [comment] 2021-03-27 01:59
Tested in both a fresh single player world and reported by thrill in an upgraded world.
Also logged on and tested w/ a multiplayer world. Same issue.

**Comment by NillerMedDild** [comment] 2021-03-27 20:07
I believe this is caused by the unification we have for Nether Bricks - It doesn't look like glyph recipes accept tags, which is what we're changing nether bricks to be in recipe inputs. Fixed by adding an explicit recipe.

**Closed** 2021-03-27 20:16 UTC
Labels: Bug, Status: Fixed In Next Release
