### ISSUE TITLE
Ticking world error TemptGoal

### ISSUE THREAD

**Issue by DrFrycook** [NillerMedDild/Enigmatica6#1606] opened 2021-03-09 13:49 UTC
**Modpack Version**
Version 0.4.3

**Describe the bug**
Simple Farming mod causing an Exception Ticking World error forcing server to crash/restart when a chunk is loaded with an unsupported mob for tempt.

Seems this error is known on the simple Farming GitHub.

**Logs**
Paste bin for crash
https://pastebin.com/jExxR88L

Link to discussion on simple farming GitHub
https://github.com/cweckerl/simplefarming/issues/128

**Comment by Darkere** [comment] 2021-03-09 14:29
There is a download to a version that actually fixes the issue rather than just removing it in the github issue.

**Comment by DrFrycook** [comment] 2021-03-09 14:58
> There is a download to a version that actually fixes the issue rather than just removing it in the github issue.
Are you talking about the fix posted by @coderepo

**Comment by theboo** [comment] 2021-03-09 15:04
If you're playing single player, just put it in to your mods folder and remove the version that is in there already

**Comment by DrFrycook** [comment] 2021-03-09 15:16
I'm running this on a server, and I can swap the jars easy enough and test it later tonight. 
All the clients connecting would need to be swapped too I assume, right?

Wasn't sure whether that was an edited version of the simple farming mod or if it was a separate jar made to fix the issue that needed to be added in addition.

I appreciate the help 😃

**Comment by DrFrycook** [comment] 2021-03-09 15:36
Thanks!
 I'll report back after I get the chance to do some testing.

**Comment by NillerMedDild** [comment] 2021-03-09 19:12
Duplicate of #813

**Closed** 2021-03-09 20:01 UTC
Labels: Duplicate
