### ISSUE TITLE
Occultism lumberjack causes massive server lag

### ISSUE THREAD

**Issue by bthomp23** [NillerMedDild/Enigmatica6#3269] opened 2021-09-18 02:55 UTC
### Modpack Version

0.5.11

### Describe your issue

When the occultism lumberjack is in the world the server falls 400+ ticks behind

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment] 2021-09-18 03:48
reported here: https://github.com/NillerMedDild/Enigmatica6/issues/3269

**Comment by theboo** [comment] 2021-09-18 05:52
just realized this is a dupe of https://github.com/NillerMedDild/Enigmatica6/issues/3269

**Closed** 2021-09-18 05:52 UTC
Labels: Duplicate

**Comment by NillerMedDild** [comment] 2021-09-18 06:14
Duplicate of #1680 not #3269 :P

**Comment by theboo** [comment] 2021-09-18 06:22
wow, i literally linked this issue... i should go to bed lmao
