### ISSUE TITLE
Viewing recipies in the Fluid Sieving machine causes crash

### ISSUE THREAD

**Issue by samPi0314** [NillerMedDild/Enigmatica6#2776] opened 2021-07-19 19:46 UTC
0.5.6

Viewing the usages for raw ore meat in the Fluid Sieving Machine causes an immediate crash. 
Crash report:
https://pastebin.com/1VLtU03W

**Comment by NillerMedDild** [comment] 2021-07-20 06:03
Duplicate of #2771

**Closed by NillerMedDild** 2021-07-20 06:03 UTC
Labels: Bug
