### ISSUE TITLE
Unbreakable Compact Machines Walls

### ISSUE THREAD

**Issue by ManiacRobert1** [NillerMedDild/Enigmatica6#1577] opened 2021-03-07 20:23 UTC
You can't break machine wall when you place it down, i tried with pickaxe and dissasambler.

P.S : If someone have same problem, blocks can be "exchanged" with exchanging gadget.

0.4.3

https://user-images.githubusercontent.com/39351347/110253540-94e6b600-7f93-11eb-8bcb-2b0f864250cf.mp4

**Comment by OneLemonyBoi** [comment] 2021-03-07 20:24
Duplicate of #1534. Someone close please!

**Closed** 2021-03-07 20:25 UTC
Labels: Bug
