### ISSUE TITLE
Issue between Lootr and certain world-gen mods causing some chests to not convert and others to not function at all.

### ISSUE THREAD

**Issue by Rekalty** [NillerMedDild/Enigmatica6#3047] opened 2021-08-20 20:40 UTC
### Modpack Version

0.5.11

### Describe your issue

Chests in specific world-gen dungeons and structures aren't behaving properly, aren't being converted to Lootr chests and in some cases, simply do not work. I'm not certain which mods in particular that are the issue, but the dungeons/structures that I have found issues with so far are:

Mineshaft and Ocean Mineshaft: Minecart with Chest isn't converted into its lootr version.

Ocean Ruins: (named ocean_ruin in /locate ) Chests aren't converted to lootr and cannot be opened or accessed. Breaking them doesn't drop their content, if they have any. Seems to be an issue for both large and small ocean ruins.

![Jre-legacy Screenshot 2021 08 20 - 21 38 20 72](https://user-images.githubusercontent.com/89275462/130290917-9581f2f8-1a1f-4339-8bdb-82213bcb9935.jpg)
![Jre-legacy Screenshot 2021 08 20 - 21 37 31 50](https://user-images.githubusercontent.com/89275462/130290946-9a59fdda-c61a-4172-a497-bcdd55d38069.jpg)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment] 2021-08-21 05:07
Thank you for the report, I will investigate the issue.

**Comment by Walsy1988** [comment] 2021-09-02 05:39
I can confirm this bug, specifically with the ocean ruins chests being waterlogged and unable to be opened; when broken, only a regular empty chest is added to the inventory with no additional loot.

I've also found an issue with Mekanism's Personal Chest wherein it wont open in my inventory and wont be placed when in hand.  Judging from other reported issues, this is likely due to containing too many nested (and some full) wooden/reinforced storage crates.  I'll try to make a way to automate unloading it before really stressing about it, but I felt that it was worth mentioning.

**Comment by NillerMedDild** [comment] 2021-09-02 11:55
This should be fixed in 0.5.12 :)

**Closed** 2021-09-24 19:33 UTC
Labels: Status: Fixed In Next Release, Mod Issue
