### ISSUE TITLE
[0.4.7] Botany pots emptied after server update

### ISSUE THREAD

**Issue by miguetdev** [NillerMedDild/Enigmatica6#1834] opened 2021-03-27 18:11 UTC
**0.4.7**

**Describe the bug**
On first server start after update to 0.4.7 all botany pots with planted items/soil in them have been emptied. 

**Logs**
Sample of console output describing botany pots found after noticing issue
https://pastebin.com/suzjpV2u

**Screenshots**
![2021-03-27_14 07 38](https://user-images.githubusercontent.com/1209079/112730134-3f545800-8f06-11eb-8067-5383e7be4f98.png)
![2021-03-27_14 06 33](https://user-images.githubusercontent.com/1209079/112730137-41b6b200-8f06-11eb-9423-c055d9468d0b.png)

**Comment by miguetdev** [comment] 2021-03-27 18:20
Image of botany pot area shown above just before update:
![2021-03-25_21 32 15](https://user-images.githubusercontent.com/1209079/112730375-9c9cd900-8f07-11eb-87af-70ffec637537.png)

**Comment by shibeobi12** [comment] 2021-03-27 18:21
To add to this report from our server, I did not have this happen from 0.4.5-0.4.7, but from 0.4.3-0.4.5 it did.

**Comment by miguetdev** [comment] 2021-03-27 18:27
Ah good detail to add yes. I just updated from 0.4.3 -> 0.4.7

**Comment by ochotonida** [comment] 2021-03-27 19:46
This is a duplicate of #1789, the log does help though. It seems this is caused by a shift in recipe id's generated by kubejs, and botany pots caching the recipes

**Comment by NillerMedDild** [comment] 2021-03-27 19:48
Oh that makes sense! Nothing we can do about that though :/

**Closed** 2021-04-06 20:10 UTC
Labels: Bug, Info
