### ISSUE TITLE
Comparators are dupable

### ISSUE THREAD

**Issue by Puupuls** [NillerMedDild/Enigmatica6#997] opened 2021-01-22 15:20 UTC
0.6.3

**Describe the bug**
The comparator can be placed on side of the block and duplicated

**Logs**

**Screenshots**

**Comment by Merlo17** [comment] 2021-01-22 15:29
Duplicate of https://github.com/NillerMedDild/Enigmatica6/issues/939 and also fixed in 0.3.7, please update

**Closed by Merlo17** 2021-01-22 15:29 UTC
Labels: Bug
