### ISSUE TITLE
0.3.10 - Server that was upgraded from 0.3.9, the end seems to be non-functional

### ISSUE THREAD

**Issue by Trostmm** [NillerMedDild/Enigmatica6#1090] opened 2021-01-27 01:25 UTC
**Modpack version**
0.3.10
**Describe the bug**
Existing End portal does not work, waypoints to the end don't work to teleport too,
**Logs**
![standinportal](https://user-images.githubusercontent.com/10382598/105928925-80b6ad00-6014-11eb-937e-b463b6b29b75.png)
No log output, it just does.. nothing ;)

**Screenshots**

**Comment by MuteTiefling** [comment] 2021-01-27 02:10
![image](https://user-images.githubusercontent.com/9543430/105932410-d2623600-601a-11eb-8e93-2a448a868b2e.png)

Not sure what's broken, but it would seem that the end just isn't even a dimension right now.

**Comment by MuteTiefling** [comment] 2021-01-27 02:26
Alright, looks like this is going to be an issue for every existing world. I had a test world from 1.16.4 where I had never gone to the End. When I attempted it, I encountered the same issue as on the server.

Brand new worlds are fine.

**Comment by toothmonsterr** [comment] 2021-01-27 04:00
Can confirm, having the same issue.

**Comment by Starfang42** [comment] 2021-01-27 04:38
Issue may be related to Minecraft or Forge version upgrade. I had a save that was upgraded to MC1.16.5/FML36.0.1, but was otherwise kept on Enigmatica 6 0.3.8, and same issue with The End happened there.

**Comment by r-mc2** [comment] 2021-01-27 06:12
As a bit of a workaround what happens if you:
* Make a backup of your End dimension folder (-1, right?)
* Generate a new world and a new End dimension in a fresh version of v0.3.10
* Save off the End dimension folder from this fresh world
* Upgrade your existing E6 instance to v0.3.10
* Then copy the fresh End dimension folder over to your upgraded previously existing E6 instance
Does that at least get The End back and working?

After that, see if copying just the region files from your backup End dimension folder back into the current v0.3.10 End dimension folder? Does that restore the original End and is working in v0.3.10?

**Comment by BlueAgent** [comment] 2021-01-27 07:08
Could be related to https://github.com/MinecraftForge/MinecraftForge/issues/7586 ?

**Comment by Darkere** [comment] 2021-01-27 08:33
Can anyone try upgrading to a newer forge?

Both directly from a 0.3.9 world and from a broken one.

**Comment by NillerMedDild** [comment] 2021-01-27 09:03
Updating to the newest Forge (36.0.7 at the time of writing) seems to not break existing worlds. If you have already loaded your world, you will need to fix it by following the steps below:

* Download NBTExplorer if you don't have it already. You can download NBTExplorer (here)[https://github.com/jaquadro/NBTExplorer/releases], or (this direct link)[https://github.com/jaquadro/NBTExplorer/releases/download/v2.8.0-win/NBTExplorer-2.8.0.msi].
* Open your world's `level.dat` with NBTExplorer
* Collapse Data > WorldGenSettings > Dimensions
* Click dimensions. It should have 3 entries if your save is bugged, 4 if not
* Click add compound tag (upper right corner), name it "minecraft:the_end" and press ok
	* Click the newly made tag, and Add string tag (Aa icon, upper right) named "type"
	* Click edit on the newly made string tag, call it "minecraft:the_end"
* Click minecraft:the_end and make another compound tag, named "generator"
	* Click the newly made tag, and Add 2 string tags named "type" and "settings"
	* Edit type, call it "minecraft:noise"
	* Edit settings, call it "minecraft:end"
	* Add a long tag (L icon, upper center) named "seed"
	* Edit it and put a seed as a numeric value. I used "842363299823994397"
* Click generator and make another compound tag, named "biome_source"
	* Click the newly made tag, and Add string tag named "type"
	* Click edit on the newly made string tag, call it "byg:bygend"
	* Add a long tag named "seed"
	* Edit it and put a seed as a numeric value. Must match the seed you entered under generator

End result should look similar to this:

![billede](https://user-images.githubusercontent.com/21295394/105964615-be521f00-6082-11eb-8385-202bc3a9246d.png)

**Comment by Darkere** [comment] 2021-01-27 09:15
It should be possible to copy this over from a backup?

**Comment by jinkhya** [comment] 2021-01-27 09:59
Hello, I saw this issue before updating the server to 0.3.10 (from 0.3.8). I started it with forge 36.0.7 and end won't load anyway.
Which makes sense it wiped the end entry in level.dat : 
![image](https://user-images.githubusercontent.com/10158963/105974810-9072d780-608e-11eb-9a91-93ef1cfc260c.png)
I'll proceed with the fix Niller posted.

**Comment by Starfang42** [comment] 2021-01-27 16:33
Small thing on the NBTExplorer fix above: I check the other WorldGenSettings entries and they all use the same seed values, so I used that value for the seed entries when following the steps. May cut down on biome generation weirdness.

**Comment by r-mc2** [comment] 2021-01-27 22:18
Is there any chance KubeJS or one of the CLI NBT editors could automate this for some people? Throw it into a script to run along side the v0.3.10 update?

Looking around there's [nbt2yaml](https://pypi.org/project/nbt2yaml/) and I assume there's something like XSLT for YAML to find the right portion of the `level.dat` and make these additions? Perhaps even inspect the existing dimensions and copy over the correct seed. Although I dunno if LoE on this is worth it with everyone knowing v0.4.0 will be an expected world reset anyway. But maybe some value in if a situation like this arises again?

**Comment by NillerMedDild** [comment] 2021-01-27 22:27
That's a very good idea. Unfortunately KubeJS can't, it cannot access the worldfolder. Will look into nbt2yaml.

**Comment by NillerMedDild** [comment] 2021-01-27 22:43
Installing nbt2yaml might be harder than to make the NBT edits in NBTExplorer tbh.

**Comment by TheCurle** [comment] 2021-01-27 23:02
To shed some light on the issue:
This bug was initially created by Forge, by accident.
It was caused by build 1.16.4-35.0.15, by [this PR](https://github.com/MinecraftForge/MinecraftForge/pull/7445) which changed how the dimensions Codecs were saved to disk. Any world made on or after this version (but before the fix) essentially has no end dragon fight, and in some extreme cases the nether and end are outright deleted from the world data. Their chunks remain, but portals become inoperable (which is what we see here).

And it was fixed in [this PR](https://github.com/MinecraftForge/MinecraftForge/pull/7527) on build 35.1.32, meaning any world initially created on a version later than this no longer has the problem. There is a retroactive fix in the works, but it's a ways off right now. However, this is a proactive fix, meaning if you load a world created 35.0.15->35.1.31 on 35.1.32, it will remain broken.

There's another related issue [here](https://github.com/MinecraftForge/MinecraftForge/pull/7613) with a similar cause and fix - the datafixerupper tools are too fragile...

We're looking into this [on our end](https://github.com/MinecraftForge/MinecraftForge/pull/7603), but for now I suggest advising against a straight update through 1.16.5.

**Comment by NillerMedDild** [comment] 2021-01-27 23:07
Dammit, thank you for the explaination, I'll look into downgrading to 1.16.4 tomorrow.

**Comment by TheCurle** [comment] 2021-01-28 00:09
A quick update. 
We merged [a hotfix](https://github.com/MinecraftForge/MinecraftForge/pull/7599) for this issue, and 1.16.5-36.0.8 will retroactively fix worlds that are missing the end and the nether.

You should be able to upgrade to this version with a few minor mod updates, notably RandomPatches, and users hopefully won't even notice the issue happened in the first place.

Cheers,
Curle - Forge Triage

**Comment by TheCurle** [comment] 2021-01-28 01:32
Another quick update. 36.0.8 has an unintended side effect of breaking everything else.. a [hotfix hotfix](https://github.com/MinecraftForge/MinecraftForge/pull/7626) is out, and 1.16.5-36.0.9 should be fully working.

**Comment by NillerMedDild** [comment] 2021-01-28 18:35
Update update: 36.0.9 should not be used, please wait for 36.0.10

**Comment by TheCurle** [comment] 2021-01-28 18:39
(the fix for breaking everything, broke the ender dragon... again.)

**Comment by TheCurle** [comment] 2021-01-28 21:23
Update update update. 
Forge 36.0.10 is out. 
This should be the end (heh) of these issues.
Please notify me if this returns.

**Closed** 2021-01-29 22:29 UTC
Labels: Bug, Status: Fixed In Next Release
