### ISSUE TITLE
Simply Backpacks Keybind Opens Fake, Blank Backpack When No Backpack Is Present

### ISSUE THREAD

**Issue by MaxFirestorm** [NillerMedDild/Enigmatica6#191] opened 2020-08-23 15:50 UTC
**Modpack version**
0.2.12

**Issue**
By default of the pack, Simply Backpacks "Open Backpack" keybind is set to B. Pressing this key opens a large, "false" backpack that is entirely empty, is named "Air" and also appears to show your inventory empty as well. This only happens when there is no backpack from the mod present in your inventory.

Screenshot - 
![2020-08-23 16_48_12-Window](https://user-images.githubusercontent.com/11296552/90982659-7de4f700-e560-11ea-8dbc-c01b444523fa.jpg)

**Notes**
I discovered this when I crafted a backpack from _Useful_ Backpacks and used the keybind from _Simply_ Backpacks by accident. By default, there is no keybind set to open a backpack from Useful Backpacks and got the mods confused when looking through keybinds. >>;

**Comment by NillerMedDild** [comment] 2020-08-23 18:20
Thanks for the report! It seems that Simply Backpacks is actually openeing the Useful Backpack, as I cannot reproduce this issue without a Useful Backpack.

**Comment by NillerMedDild** [comment] 2020-08-23 18:22
Reported here: https://github.com/Flanks255/simplybackpacks/issues/26

**Comment by NillerMedDild** [comment] 2020-08-23 18:51
Won't be fixed until we make the jump to 1.16.2 unfortunately.

**Closed by NillerMedDild** 2020-08-23 18:51 UTC
Labels: Mod Issue, Status: Won't Fix
