### ISSUE TITLE
Astral Sorcery stone enrichment transforming chiseled marble

### ISSUE THREAD

**Issue by Brendan-James** [NillerMedDild/Enigmatica6#2131] opened 2021-05-09 21:53 UTC
**Modpack version**
0.4.10
**Describe the bug**
The stone enrichment attunement perk from astral sorcery can transform the marble in multiblock structures into ore, ruining them.

**Comment by NillerMedDild** [comment] 2021-05-09 21:55
Duplicate of #1147

**Closed** 2021-05-09 22:00 UTC
Labels: Duplicate
