### ISSUE TITLE
Villager didn't change the job to fletcher even thought fletcher table are near them

### ISSUE THREAD

**Issue by hkpyro08** [NillerMedDild/Enigmatica6#1275] opened 2021-02-09 11:44 UTC
**Modpack version**
0.3.13
**Describe the bug**
I think there is a bug that don't change the villager job to fletcher when a fletcher table near them. I'm not quite sure it's a bug or just me, I don't know

**Comment by theboo** [comment] 2021-02-09 12:35
Duplicate of #767

**Closed by theboo** 2021-02-09 12:35 UTC
Labels: Bug
