### ISSUE TITLE
[0.4.3 and up] Short clip of a music playing

### ISSUE THREAD

**Issue by SexyRoyalBlue** [NillerMedDild/Enigmatica6#1926] opened 2021-04-06 20:46 UTC
On Version 0.4.3 up

 It's not really a bug but rather a music from ingame playing after a random amount of time, at least it seems like that to me, which is not influence by the game volume for standard minecraft music
It's a real jammer tho BUT it stops after a few seconds the first time it popped up and everytime it plays again a tiny bit more of the track is played

Now, is that maybe the offcial music of Enigmatica 6 and it's just a bug that it won't play fully for me? Or is it not intended that this music is playing and it's maybe from a mod? I at least couldn't find anything in the web to this music

**Comment by sk-1982** [comment] 2021-04-06 21:21
I suspect you're hearing the music disk "Bearfan - Nourish" from Simple Farming. If so, this is an issue with how Minecraft handles stereo .ogg files and Sophisticated Backpacks spawning mobs with jukebox upgrades in backpacks. See [this related issue on Simple Farming.](https://github.com/cweckerl/simplefarming/issues/159)

**Comment by NillerMedDild** [comment] 2021-04-07 17:38
Duplicate of #1838 
This is intended, the music comes from mobs wearing backpacks that play music :P

**Closed by NillerMedDild** 2021-04-07 17:38 UTC
Labels: Bug
