### ISSUE TITLE
Add Tinkers' Construct books to the Akashic Tome

### ISSUE THREAD

**Issue by surfacelevelspeck** [NillerMedDild/Enigmatica6#2512] opened 2021-06-23 20:39 UTC
**Description**
As the title says, it would be nice if all 5 of the Tinkers' Construct books could be added to the list of valid books that can be put in the Akashic Tome.

**Why would you like this added/changed?**
Tinkers' Construct has 5 books for the mod, which is a lot of books to check for specific information. Having them in the Akashic Tome would make it easier to reference them by letting you freely swap between them without taking up half a hotbar.

**Screenshots if applicable.**
![2021-06-23_15 38 42](https://user-images.githubusercontent.com/17912442/123164881-1ece6800-d439-11eb-8da4-781f56335bc5.png)

**Comment by NillerMedDild** [comment] 2021-06-23 20:48
Duplicate of #2351

**Closed by NillerMedDild** 2021-06-23 20:48 UTC
Labels: Suggestion
