### ISSUE TITLE
Astral Crystals dupe

### ISSUE THREAD

**Issue by desertkid** [NillerMedDild/Enigmatica6#3270] opened 2021-09-18 04:25 UTC
### Modpack Version

0.5.11

### Describe your issue

I put astral crystal in golden chest when i put the mekanism carboard box on it to move it it spits out a choppy of all the crystals inside it while retaining its original inventory

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment] 2021-09-18 04:29
duplicate of https://github.com/NillerMedDild/Enigmatica6/issues/1847 xD

**Closed** 2021-09-18 04:29 UTC
Labels: Duplicate
