### ISSUE TITLE
[Mos Suggestion]Ice and Fire: Dragons

### ISSUE THREAD

**Issue by chcknlvr** [NillerMedDild/Enigmatica6#989] opened 2021-01-22 01:09 UTC
https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons
Ice and fire is a good mod with dragons and more creatures

This mod will make the modpack greatly inproved

**Comment by TemperedFool** [comment] 2021-01-22 01:12
This is a dupe of https://github.com/NillerMedDild/Enigmatica6/issues/312

**Closed** 2021-01-22 07:12 UTC
Labels: Suggestion
