### ISSUE TITLE
Mod request: Building Gadgets by Direwolf20

### ISSUE THREAD

**Issue by tonyvans** [NillerMedDild/Enigmatica6#161] opened 2020-08-17 15:18 UTC
Mod request: Building Gadgets by Direwolf20

Mod request https://www.curseforge.com/minecraft/mc-mods/building-gadgets

Was one of my favorite mods from Enigmatica 5

Thanks

**Comment by brckts** [comment] 2020-08-17 15:22
It has already been added in 0.2.7 iirc

**Comment by NillerMedDild** [comment] 2020-08-17 17:28
duplicate of #137

**Closed by NillerMedDild** 2020-08-17 17:28 UTC
Labels: Duplicate

**Comment by tonyvans** [comment] 2020-08-17 17:52
Amazing.Thank you.
