### ISSUE TITLE
JEI only loads in some recipes after loading singleplayer

### ISSUE THREAD

**Issue by Okabiz** [NillerMedDild/Enigmatica6#2966] opened 2021-08-12 14:26 UTC
**Modpack version**
0.5.9

**Describe the bug**
Recipes for some Apotheosis bookshelves, ie the endshelf, (and maybe items from other mods but I have not found them) go missing if you join a server without loading a singleplayer world at least once beforehand.

**Logs**
[2021-08-12-3.log.gz](https://github.com/NillerMedDild/Enigmatica6/files/6976138/2021-08-12-3.log.gz)
I know this isn't the latest.log but I think this one might be more of interest, in this one, I join a server, then leave to load a singleplayer world, then come back to the server.

**Comment by NillerMedDild** [comment] 2021-08-12 14:27
Duplicate of #2945 #2928

**Closed by NillerMedDild** 2021-08-12 14:27 UTC
Labels: Bug
