### ISSUE TITLE
When In Inventory and shift+clicking dismounts you

### ISSUE THREAD

**Issue by NetIsPrograming** [NillerMedDild/Enigmatica6#3382] opened 2021-10-05 20:55 UTC
### Modpack Version

0.5.14

### Describe your issue.

Title says it all.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment] 2021-10-06 04:52
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment] 2021-10-10 17:31
Cannot reproduce, possibly fixed by mod updates though :)

**Closed by NillerMedDild** 2021-10-10 17:31 UTC
Labels: Bug
