### ISSUE TITLE
Crash on trying to open Chisels and Bits radial menu

### ISSUE THREAD

**Issue by Rodg88** [NillerMedDild/Enigmatica6#3928] opened 2021-12-18 20:44 UTC
### Modpack Version

Dev expert 19/dec

### Describe your issue.

While holding a tape measure, I pressed the key to bring up the C&B menu (rebound to F, which did have conflicts), and the game crashed. Tried again with a different keybind, with no conflicts, still crashed.

chiselsandbits-1.0.43

### Crash Report

https://gist.github.com/Rodg88/5ae8ac064129cb3e0d4d2a8dd8ef1593

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by theboo** [comment] 2021-12-18 21:11
duplicate of #3754, no fix yet sadly :(

**Closed** 2021-12-18 21:11 UTC
Labels: Duplicate
