### ISSUE TITLE
4.10 doesn't include the building gadgets patterns directory structure

### ISSUE THREAD

**Issue by DoomSquirter** [NillerMedDild/Enigmatica6#2156] opened 2021-05-13 10:55 UTC
**Modpack version**
4.10

**Describe the bug**
downloaded 4.10 using mmc and I didn't have the above mentioned directory in my install

**Logs**
n/a

**Screenshots**
n/a

**Comment by TemperedFool** [comment] 2021-05-13 10:58
Dupe of #2113 - this is addressed in dev and will be fixed in the next update ^_^

**Closed** 2021-05-13 11:39 UTC
Labels: Bug

**Comment by DoomSquirter** [comment] 2021-05-13 14:30
sorry, I should have searched first.  I usually do that actually.  -1 to gryffindor

**Comment by TemperedFool** [comment] 2021-05-13 14:34
Nah, it's not a big deal - easy to answer a duplicate issue, hard to deal with one that's unreported!
