### ISSUE TITLE
Client crashes on Elementium Ore processing recipes by Occultism and Pedestals

### ISSUE THREAD

**Issue by NurikSakura** [NillerMedDild/Enigmatica6#3248] opened 2021-09-16 00:54 UTC
### Modpack Version

0.5.11

### Describe your issue

If trying to check JEI usage on Elementium Ore from MythicBotania, the client crashes as soon as you try to switch to Pedestal's Crusher tab or Occultism's Crusher Spirit tab. This only happens to Elementium Ore, at least, any other ore I checked was displaying normally, including the Gold Ore from MythicBotania.

Crash report (the error and stack trace) is identical for both cases.

### Crash Report

https://pastebin.com/dhSCfw87

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment] 2021-09-16 00:56
Duplicate of https://github.com/NillerMedDild/Enigmatica6/issues/3068

**Closed** 2021-09-16 00:56 UTC
Labels: Duplicate
