### ISSUE TITLE
Crash when attempting to load certain chunks

### ISSUE THREAD

**Issue by dixonw2** [NillerMedDild/Enigmatica6#869] opened 2021-01-12 23:13 UTC
**Modpack version**
0.3.5

**Issue**
I've had a few instances where moving and loading presumably new/unloaded for a while chunks will freeze the game for about 10-15 seconds before crashing. 

**Logs**
https://pastebin.com/SCCua4CD

**Comment by NillerMedDild** [comment] 2021-01-13 20:14
Thanks for the report!
duplicate of #813 though.

**Comment by dixonw2** [comment] 2021-01-13 20:15
> Thanks for the report!
> duplicate of #813 though.

Oh sorry hadn't seen that, my bad! Glad you're aware!

**Closed** 2021-01-13 23:03 UTC
Labels: Duplicate
