### ISSUE TITLE
[0.4.1 Server] Information on Resourceful Bees unavailable in JEI for all server members

### ISSUE THREAD

**Issue by wubbles417** [NillerMedDild/Enigmatica6#1483] opened 2021-03-01 06:19 UTC
0.4.1 - Server

JEI for Resourceful Bees not showing any bees, just eggs. No way to view data about individual bees.
Checked with all members of server - nobody has been able to view them since the update.

[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6059488/latest.log)

**Comment by NillerMedDild** [comment] 2021-03-01 19:27
Duplicate of #1424

**Closed by NillerMedDild** 2021-03-01 19:27 UTC
Labels: Bug

**Comment by Dracos99** [comment] 2021-03-05 17:40
/reload does not seem to be fixing the missing Bee JEI info in 0.4.3 server
