### ISSUE TITLE
Mind-Shielding Plate uncraftable

### ISSUE THREAD

**Issue by g0urra** [NillerMedDild/Enigmatica6#2618] opened 2021-07-04 02:23 UTC
**Modpack version**
0.5.2 server

**Describe the bug**
Mind-Shielding Plate from Eidolon only accepts Eidolon Lead Ingots, making it uncraftable.

**Screenshots**
![image](https://user-images.githubusercontent.com/12349921/124371171-75c90e00-dc7f-11eb-8fed-c0e8f56b83ef.png)
![image](https://user-images.githubusercontent.com/12349921/124371164-6e096980-dc7f-11eb-970d-ee845c244a6b.png)

**Comment by NillerMedDild** [comment] 2021-07-04 06:09
Duplicate of #794

**Closed by NillerMedDild** 2021-07-04 06:09 UTC
Labels: Bug
